@echo off
setlocal EnableDelayedExpansion
rem ============================================================================
rem  generateManifestList.bat
rem
rem  Generates the per-function enable header for the Release_XL_Manifest
rem  AQ_XLL config (CLAUDE.md Sec 4.4/9.5). Every AQ_XLL worksheet function is
rem  wrapped `#if AQ_XLL_ENABLED(name) ... #endif`; AQ_XLL_ENABLED is defined
rem  once in src\AQ_XLL\include\xllSupport.h as:
rem
rem      #define AQ_XLL_ENABLED(name)  (!AQ_XLL_MANIFEST_BUILD || AQ_XLL_ENABLE_##name)
rem
rem  Pure cmd.exe - no Python, no PowerShell, nothing to install beyond
rem  Windows itself. Ground truth for "known function names" is the AQ_XLL
rem  source itself (every XLO_FUNC_START site), scanned fresh every run.
rem
rem  The manifest file is plain text, not JSON (cmd.exe has no JSON parser):
rem  see activeList.txt in this same folder for the format and inline
rem  comments.
rem
rem  Every file this script writes (the two temp lists and the output header)
rem  is written via ONE grouped ( ... ) > "file" redirection rather than many
rem  small >> appends, deliberately - opening/closing a file hundreds of times
rem  in a tight loop is a well-known way to collide with antivirus real-time
rem  scanning or an IDE's file-change watcher, surfacing as an intermittent
rem  "The process cannot access the file because it is being used by another
rem  process" - harmless-looking (this script still finishes and the content
rem  is usually still correct) but not something to leave in place, since an
rem  unlucky collision could silently drop a line. Grouping keeps the file
rem  open for the whole write instead of hundreds of separate opens.
rem
rem  Usage:
rem    generateManifestList.bat AQ_LIB_root manifest.txt output_header.h
rem
rem  Exit code 1 if AQ_LIB_root doesn't look right, the manifest file is
rem  missing, or the manifest names a function that doesn't exist in AQ_XLL.
rem ============================================================================

if "%~3"=="" (
    echo Usage: generateManifestList.bat AQ_LIB_root manifest.txt output_header.h
    exit /b 1
)

set "ROOT=%~1"
set "MANIFEST=%~2"
set "OUT=%~3"
set "SRC_DIR=%ROOT%\src\AQ_XLL\src"

if not exist "%SRC_DIR%\" (
    echo ERROR: no src\AQ_XLL\src found under AQ_LIB_root: %ROOT%
    echo        ^(looked for: %SRC_DIR%^)
    exit /b 1
)

if not exist "%MANIFEST%" (
    echo ERROR: manifest file not found: %MANIFEST%
    exit /b 1
)

set "TMPDIR=%TEMP%\aq_xll_manifest_%RANDOM%_%RANDOM%"
mkdir "%TMPDIR%" >nul 2>nul
set "KNOWN=%TMPDIR%\known.txt"
set "REQ=%TMPDIR%\requested.txt"

rem --- 1. scan every .cpp for XLO_FUNC_START(name -----------------------------
rem     one grouped write - KNOWN is opened once, not once per function.
(
    for %%F in ("%SRC_DIR%\*.cpp") do (
        for /f "usebackq delims=" %%L in (`findstr /r /c:"^XLO_FUNC_START(" "%%F"`) do (
            set "REST=%%L"
            set "REST=!REST:XLO_FUNC_START(=!"
            for /f "tokens=1 delims=( " %%N in ("!REST!") do (
                echo %%N
            )
        )
    )
) > "%KNOWN%"

rem --- 2. parse the manifest: "edition:<name>", "*", one name per line -------
rem     lines starting with # are comments (skipped by eol=#); blank lines
rem     are skipped by the "if not ..." check below. EDITION/ALL are ordinary
rem     side effects of this block (grouping with parens does not create a
rem     new variable scope), so they are still set correctly after it closes.
set "EDITION=%~n2"
set "ALL=0"
(
    for /f "usebackq eol=# tokens=* delims=" %%R in ("%MANIFEST%") do (
        set "LINE=%%R"
        if not "!LINE!"=="" (
            echo !LINE!| findstr /b /c:"edition:" >nul
            if not errorlevel 1 (
                for /f "tokens=1* delims=:" %%A in ("!LINE!") do set "EDITION=%%B"
            ) else if "!LINE!"=="*" (
                set "ALL=1"
            ) else (
                echo !LINE!
            )
        )
    )
) > "%REQ%"

rem --- 3. validate every requested name exists (skip entirely if "*") --------
set "UNKNOWN_FOUND=0"
if "!ALL!"=="0" (
    for /f "usebackq delims=" %%R in ("%REQ%") do (
        findstr /x /c:"%%R" "%KNOWN%" >nul
        if errorlevel 1 (
            if "!UNKNOWN_FOUND!"=="0" echo ERROR: manifest names functions that do not exist in AQ_XLL:
            echo   %%R
            set "UNKNOWN_FOUND=1"
        )
    )
)
if "!UNKNOWN_FOUND!"=="1" (
    rd /s /q "%TMPDIR%" >nul 2>nul
    exit /b 1
)

rem --- 4. write the header: one #define per known function --------------------
rem     one grouped write - OUT is opened once, not once per function.
for %%D in ("%OUT%") do set "OUTDIR=%%~dpD"
if not exist "%OUTDIR%" mkdir "%OUTDIR%"

set /a ENABLED_COUNT=0
set /a TOTAL_COUNT=0
(
    echo #pragma once
    echo(
    echo // GENERATED by generateManifestList.bat -- do not edit.
    echo // Source manifest: %MANIFEST%  (edition: %EDITION%^)
    echo(
    for /f "usebackq delims=" %%N in ("%KNOWN%") do (
        set /a TOTAL_COUNT+=1
        set "VAL=0"
        if "!ALL!"=="1" (
            set "VAL=1"
        ) else (
            findstr /x /c:"%%N" "%REQ%" >nul
            if not errorlevel 1 set "VAL=1"
        )
        if "!VAL!"=="1" set /a ENABLED_COUNT+=1
        echo #define AQ_XLL_ENABLE_%%N !VAL!
    )
    echo(
) > "%OUT%"

rd /s /q "%TMPDIR%" >nul 2>nul

echo Wrote %OUT%: %ENABLED_COUNT%/%TOTAL_COUNT% functions enabled for edition '%EDITION%'.
exit /b 0
