# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _AlgoQuantLib
else:
    import _AlgoQuantLib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _AlgoQuantLib.delete_SwigPyIterator

    def value(self) -> "PyObject *":
        return _AlgoQuantLib.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _AlgoQuantLib.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _AlgoQuantLib.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _AlgoQuantLib.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _AlgoQuantLib.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _AlgoQuantLib.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _AlgoQuantLib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _AlgoQuantLib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _AlgoQuantLib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _AlgoQuantLib.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _AlgoQuantLib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _AlgoQuantLib:
_AlgoQuantLib.SwigPyIterator_swigregister(SwigPyIterator)


def cdata(ptr: 'void *', nelements: 'size_t'=1) -> "SWIGCDATA":
    return _AlgoQuantLib.cdata(ptr, nelements)

def memmove(data: 'void *', indata: 'void const *') -> "void":
    return _AlgoQuantLib.memmove(data, indata)
class VecInteger(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecInteger_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecInteger___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecInteger___bool__(self)

    def __len__(self) -> "std::vector< int >::size_type":
        return _AlgoQuantLib.VecInteger___len__(self)

    def __getslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "std::vector< int,std::allocator< int > > *":
        return _AlgoQuantLib.VecInteger___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecInteger___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "void":
        return _AlgoQuantLib.VecInteger___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecInteger___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< int >::value_type const &":
        return _AlgoQuantLib.VecInteger___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecInteger___setitem__(self, *args)

    def pop(self) -> "std::vector< int >::value_type":
        return _AlgoQuantLib.VecInteger_pop(self)

    def append(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _AlgoQuantLib.VecInteger_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecInteger_empty(self)

    def size(self) -> "std::vector< int >::size_type":
        return _AlgoQuantLib.VecInteger_size(self)

    def swap(self, v: 'VecInteger') -> "void":
        return _AlgoQuantLib.VecInteger_swap(self, v)

    def begin(self) -> "std::vector< int >::iterator":
        return _AlgoQuantLib.VecInteger_begin(self)

    def end(self) -> "std::vector< int >::iterator":
        return _AlgoQuantLib.VecInteger_end(self)

    def rbegin(self) -> "std::vector< int >::reverse_iterator":
        return _AlgoQuantLib.VecInteger_rbegin(self)

    def rend(self) -> "std::vector< int >::reverse_iterator":
        return _AlgoQuantLib.VecInteger_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecInteger_clear(self)

    def get_allocator(self) -> "std::vector< int >::allocator_type":
        return _AlgoQuantLib.VecInteger_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecInteger_pop_back(self)

    def erase(self, *args) -> "std::vector< int >::iterator":
        return _AlgoQuantLib.VecInteger_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecInteger_swiginit(self, _AlgoQuantLib.new_VecInteger(*args))

    def push_back(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _AlgoQuantLib.VecInteger_push_back(self, x)

    def front(self) -> "std::vector< int >::value_type const &":
        return _AlgoQuantLib.VecInteger_front(self)

    def back(self) -> "std::vector< int >::value_type const &":
        return _AlgoQuantLib.VecInteger_back(self)

    def assign(self, n: 'std::vector< int >::size_type', x: 'std::vector< int >::value_type const &') -> "void":
        return _AlgoQuantLib.VecInteger_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecInteger_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecInteger_insert(self, *args)

    def reserve(self, n: 'std::vector< int >::size_type') -> "void":
        return _AlgoQuantLib.VecInteger_reserve(self, n)

    def capacity(self) -> "std::vector< int >::size_type":
        return _AlgoQuantLib.VecInteger_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecInteger

# Register VecInteger in _AlgoQuantLib:
_AlgoQuantLib.VecInteger_swigregister(VecInteger)

class VecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecDouble___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecDouble___bool__(self)

    def __len__(self) -> "std::vector< double >::size_type":
        return _AlgoQuantLib.VecDouble___len__(self)

    def __getslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "std::vector< double,std::allocator< double > > *":
        return _AlgoQuantLib.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecDouble___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "void":
        return _AlgoQuantLib.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< double >::value_type const &":
        return _AlgoQuantLib.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecDouble___setitem__(self, *args)

    def pop(self) -> "std::vector< double >::value_type":
        return _AlgoQuantLib.VecDouble_pop(self)

    def append(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _AlgoQuantLib.VecDouble_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecDouble_empty(self)

    def size(self) -> "std::vector< double >::size_type":
        return _AlgoQuantLib.VecDouble_size(self)

    def swap(self, v: 'VecDouble') -> "void":
        return _AlgoQuantLib.VecDouble_swap(self, v)

    def begin(self) -> "std::vector< double >::iterator":
        return _AlgoQuantLib.VecDouble_begin(self)

    def end(self) -> "std::vector< double >::iterator":
        return _AlgoQuantLib.VecDouble_end(self)

    def rbegin(self) -> "std::vector< double >::reverse_iterator":
        return _AlgoQuantLib.VecDouble_rbegin(self)

    def rend(self) -> "std::vector< double >::reverse_iterator":
        return _AlgoQuantLib.VecDouble_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecDouble_clear(self)

    def get_allocator(self) -> "std::vector< double >::allocator_type":
        return _AlgoQuantLib.VecDouble_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecDouble_pop_back(self)

    def erase(self, *args) -> "std::vector< double >::iterator":
        return _AlgoQuantLib.VecDouble_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecDouble_swiginit(self, _AlgoQuantLib.new_VecDouble(*args))

    def push_back(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _AlgoQuantLib.VecDouble_push_back(self, x)

    def front(self) -> "std::vector< double >::value_type const &":
        return _AlgoQuantLib.VecDouble_front(self)

    def back(self) -> "std::vector< double >::value_type const &":
        return _AlgoQuantLib.VecDouble_back(self)

    def assign(self, n: 'std::vector< double >::size_type', x: 'std::vector< double >::value_type const &') -> "void":
        return _AlgoQuantLib.VecDouble_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecDouble_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecDouble_insert(self, *args)

    def reserve(self, n: 'std::vector< double >::size_type') -> "void":
        return _AlgoQuantLib.VecDouble_reserve(self, n)

    def capacity(self) -> "std::vector< double >::size_type":
        return _AlgoQuantLib.VecDouble_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecDouble

# Register VecDouble in _AlgoQuantLib:
_AlgoQuantLib.VecDouble_swigregister(VecDouble)

class VecString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecString___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecString___bool__(self)

    def __len__(self) -> "std::vector< std::string >::size_type":
        return _AlgoQuantLib.VecString___len__(self)

    def __getslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> "std::vector< std::string,std::allocator< std::string > > *":
        return _AlgoQuantLib.VecString___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecString___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::string >::difference_type', j: 'std::vector< std::string >::difference_type') -> "void":
        return _AlgoQuantLib.VecString___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecString___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::string >::value_type const &":
        return _AlgoQuantLib.VecString___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecString___setitem__(self, *args)

    def pop(self) -> "std::vector< std::string >::value_type":
        return _AlgoQuantLib.VecString_pop(self)

    def append(self, x: 'std::vector< std::string >::value_type const &') -> "void":
        return _AlgoQuantLib.VecString_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecString_empty(self)

    def size(self) -> "std::vector< std::string >::size_type":
        return _AlgoQuantLib.VecString_size(self)

    def swap(self, v: 'VecString') -> "void":
        return _AlgoQuantLib.VecString_swap(self, v)

    def begin(self) -> "std::vector< std::string >::iterator":
        return _AlgoQuantLib.VecString_begin(self)

    def end(self) -> "std::vector< std::string >::iterator":
        return _AlgoQuantLib.VecString_end(self)

    def rbegin(self) -> "std::vector< std::string >::reverse_iterator":
        return _AlgoQuantLib.VecString_rbegin(self)

    def rend(self) -> "std::vector< std::string >::reverse_iterator":
        return _AlgoQuantLib.VecString_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecString_clear(self)

    def get_allocator(self) -> "std::vector< std::string >::allocator_type":
        return _AlgoQuantLib.VecString_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecString_pop_back(self)

    def erase(self, *args) -> "std::vector< std::string >::iterator":
        return _AlgoQuantLib.VecString_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecString_swiginit(self, _AlgoQuantLib.new_VecString(*args))

    def push_back(self, x: 'std::vector< std::string >::value_type const &') -> "void":
        return _AlgoQuantLib.VecString_push_back(self, x)

    def front(self) -> "std::vector< std::string >::value_type const &":
        return _AlgoQuantLib.VecString_front(self)

    def back(self) -> "std::vector< std::string >::value_type const &":
        return _AlgoQuantLib.VecString_back(self)

    def assign(self, n: 'std::vector< std::string >::size_type', x: 'std::vector< std::string >::value_type const &') -> "void":
        return _AlgoQuantLib.VecString_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecString_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecString_insert(self, *args)

    def reserve(self, n: 'std::vector< std::string >::size_type') -> "void":
        return _AlgoQuantLib.VecString_reserve(self, n)

    def capacity(self) -> "std::vector< std::string >::size_type":
        return _AlgoQuantLib.VecString_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecString

# Register VecString in _AlgoQuantLib:
_AlgoQuantLib.VecString_swigregister(VecString)

class VecVecInteger(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecVecInteger_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecVecInteger___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecVecInteger___bool__(self)

    def __len__(self) -> "std::vector< std::vector< int > >::size_type":
        return _AlgoQuantLib.VecVecInteger___len__(self)

    def __getslice__(self, i: 'std::vector< std::vector< int > >::difference_type', j: 'std::vector< std::vector< int > >::difference_type') -> "std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > *":
        return _AlgoQuantLib.VecVecInteger___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecInteger___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::vector< int > >::difference_type', j: 'std::vector< std::vector< int > >::difference_type') -> "void":
        return _AlgoQuantLib.VecVecInteger___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecInteger___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::vector< int > >::value_type const &":
        return _AlgoQuantLib.VecVecInteger___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecInteger___setitem__(self, *args)

    def pop(self) -> "std::vector< std::vector< int > >::value_type":
        return _AlgoQuantLib.VecVecInteger_pop(self)

    def append(self, x: 'VecInteger') -> "void":
        return _AlgoQuantLib.VecVecInteger_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecVecInteger_empty(self)

    def size(self) -> "std::vector< std::vector< int > >::size_type":
        return _AlgoQuantLib.VecVecInteger_size(self)

    def swap(self, v: 'VecVecInteger') -> "void":
        return _AlgoQuantLib.VecVecInteger_swap(self, v)

    def begin(self) -> "std::vector< std::vector< int > >::iterator":
        return _AlgoQuantLib.VecVecInteger_begin(self)

    def end(self) -> "std::vector< std::vector< int > >::iterator":
        return _AlgoQuantLib.VecVecInteger_end(self)

    def rbegin(self) -> "std::vector< std::vector< int > >::reverse_iterator":
        return _AlgoQuantLib.VecVecInteger_rbegin(self)

    def rend(self) -> "std::vector< std::vector< int > >::reverse_iterator":
        return _AlgoQuantLib.VecVecInteger_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecVecInteger_clear(self)

    def get_allocator(self) -> "std::vector< std::vector< int > >::allocator_type":
        return _AlgoQuantLib.VecVecInteger_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecVecInteger_pop_back(self)

    def erase(self, *args) -> "std::vector< std::vector< int > >::iterator":
        return _AlgoQuantLib.VecVecInteger_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecVecInteger_swiginit(self, _AlgoQuantLib.new_VecVecInteger(*args))

    def push_back(self, x: 'VecInteger') -> "void":
        return _AlgoQuantLib.VecVecInteger_push_back(self, x)

    def front(self) -> "std::vector< std::vector< int > >::value_type const &":
        return _AlgoQuantLib.VecVecInteger_front(self)

    def back(self) -> "std::vector< std::vector< int > >::value_type const &":
        return _AlgoQuantLib.VecVecInteger_back(self)

    def assign(self, n: 'std::vector< std::vector< int > >::size_type', x: 'VecInteger') -> "void":
        return _AlgoQuantLib.VecVecInteger_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecVecInteger_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecVecInteger_insert(self, *args)

    def reserve(self, n: 'std::vector< std::vector< int > >::size_type') -> "void":
        return _AlgoQuantLib.VecVecInteger_reserve(self, n)

    def capacity(self) -> "std::vector< std::vector< int > >::size_type":
        return _AlgoQuantLib.VecVecInteger_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecVecInteger

# Register VecVecInteger in _AlgoQuantLib:
_AlgoQuantLib.VecVecInteger_swigregister(VecVecInteger)

class VecVecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecVecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecVecDouble___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecVecDouble___bool__(self)

    def __len__(self) -> "std::vector< std::vector< double > >::size_type":
        return _AlgoQuantLib.VecVecDouble___len__(self)

    def __getslice__(self, i: 'std::vector< std::vector< double > >::difference_type', j: 'std::vector< std::vector< double > >::difference_type') -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > *":
        return _AlgoQuantLib.VecVecDouble___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecDouble___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::vector< double > >::difference_type', j: 'std::vector< std::vector< double > >::difference_type') -> "void":
        return _AlgoQuantLib.VecVecDouble___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecDouble___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::vector< double > >::value_type const &":
        return _AlgoQuantLib.VecVecDouble___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecDouble___setitem__(self, *args)

    def pop(self) -> "std::vector< std::vector< double > >::value_type":
        return _AlgoQuantLib.VecVecDouble_pop(self)

    def append(self, x: 'VecDouble') -> "void":
        return _AlgoQuantLib.VecVecDouble_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecVecDouble_empty(self)

    def size(self) -> "std::vector< std::vector< double > >::size_type":
        return _AlgoQuantLib.VecVecDouble_size(self)

    def swap(self, v: 'VecVecDouble') -> "void":
        return _AlgoQuantLib.VecVecDouble_swap(self, v)

    def begin(self) -> "std::vector< std::vector< double > >::iterator":
        return _AlgoQuantLib.VecVecDouble_begin(self)

    def end(self) -> "std::vector< std::vector< double > >::iterator":
        return _AlgoQuantLib.VecVecDouble_end(self)

    def rbegin(self) -> "std::vector< std::vector< double > >::reverse_iterator":
        return _AlgoQuantLib.VecVecDouble_rbegin(self)

    def rend(self) -> "std::vector< std::vector< double > >::reverse_iterator":
        return _AlgoQuantLib.VecVecDouble_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecVecDouble_clear(self)

    def get_allocator(self) -> "std::vector< std::vector< double > >::allocator_type":
        return _AlgoQuantLib.VecVecDouble_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecVecDouble_pop_back(self)

    def erase(self, *args) -> "std::vector< std::vector< double > >::iterator":
        return _AlgoQuantLib.VecVecDouble_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecVecDouble_swiginit(self, _AlgoQuantLib.new_VecVecDouble(*args))

    def push_back(self, x: 'VecDouble') -> "void":
        return _AlgoQuantLib.VecVecDouble_push_back(self, x)

    def front(self) -> "std::vector< std::vector< double > >::value_type const &":
        return _AlgoQuantLib.VecVecDouble_front(self)

    def back(self) -> "std::vector< std::vector< double > >::value_type const &":
        return _AlgoQuantLib.VecVecDouble_back(self)

    def assign(self, n: 'std::vector< std::vector< double > >::size_type', x: 'VecDouble') -> "void":
        return _AlgoQuantLib.VecVecDouble_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecVecDouble_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecVecDouble_insert(self, *args)

    def reserve(self, n: 'std::vector< std::vector< double > >::size_type') -> "void":
        return _AlgoQuantLib.VecVecDouble_reserve(self, n)

    def capacity(self) -> "std::vector< std::vector< double > >::size_type":
        return _AlgoQuantLib.VecVecDouble_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecVecDouble

# Register VecVecDouble in _AlgoQuantLib:
_AlgoQuantLib.VecVecDouble_swigregister(VecVecDouble)

class VecVecString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _AlgoQuantLib.VecVecString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _AlgoQuantLib.VecVecString___nonzero__(self)

    def __bool__(self) -> "bool":
        return _AlgoQuantLib.VecVecString___bool__(self)

    def __len__(self) -> "std::vector< std::vector< std::string > >::size_type":
        return _AlgoQuantLib.VecVecString___len__(self)

    def __getslice__(self, i: 'std::vector< std::vector< std::string > >::difference_type', j: 'std::vector< std::vector< std::string > >::difference_type') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > > *":
        return _AlgoQuantLib.VecVecString___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecString___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< std::vector< std::string > >::difference_type', j: 'std::vector< std::vector< std::string > >::difference_type') -> "void":
        return _AlgoQuantLib.VecVecString___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecString___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::vector< std::string > >::value_type const &":
        return _AlgoQuantLib.VecVecString___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _AlgoQuantLib.VecVecString___setitem__(self, *args)

    def pop(self) -> "std::vector< std::vector< std::string > >::value_type":
        return _AlgoQuantLib.VecVecString_pop(self)

    def append(self, x: 'VecString') -> "void":
        return _AlgoQuantLib.VecVecString_append(self, x)

    def empty(self) -> "bool":
        return _AlgoQuantLib.VecVecString_empty(self)

    def size(self) -> "std::vector< std::vector< std::string > >::size_type":
        return _AlgoQuantLib.VecVecString_size(self)

    def swap(self, v: 'VecVecString') -> "void":
        return _AlgoQuantLib.VecVecString_swap(self, v)

    def begin(self) -> "std::vector< std::vector< std::string > >::iterator":
        return _AlgoQuantLib.VecVecString_begin(self)

    def end(self) -> "std::vector< std::vector< std::string > >::iterator":
        return _AlgoQuantLib.VecVecString_end(self)

    def rbegin(self) -> "std::vector< std::vector< std::string > >::reverse_iterator":
        return _AlgoQuantLib.VecVecString_rbegin(self)

    def rend(self) -> "std::vector< std::vector< std::string > >::reverse_iterator":
        return _AlgoQuantLib.VecVecString_rend(self)

    def clear(self) -> "void":
        return _AlgoQuantLib.VecVecString_clear(self)

    def get_allocator(self) -> "std::vector< std::vector< std::string > >::allocator_type":
        return _AlgoQuantLib.VecVecString_get_allocator(self)

    def pop_back(self) -> "void":
        return _AlgoQuantLib.VecVecString_pop_back(self)

    def erase(self, *args) -> "std::vector< std::vector< std::string > >::iterator":
        return _AlgoQuantLib.VecVecString_erase(self, *args)

    def __init__(self, *args):
        _AlgoQuantLib.VecVecString_swiginit(self, _AlgoQuantLib.new_VecVecString(*args))

    def push_back(self, x: 'VecString') -> "void":
        return _AlgoQuantLib.VecVecString_push_back(self, x)

    def front(self) -> "std::vector< std::vector< std::string > >::value_type const &":
        return _AlgoQuantLib.VecVecString_front(self)

    def back(self) -> "std::vector< std::vector< std::string > >::value_type const &":
        return _AlgoQuantLib.VecVecString_back(self)

    def assign(self, n: 'std::vector< std::vector< std::string > >::size_type', x: 'VecString') -> "void":
        return _AlgoQuantLib.VecVecString_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _AlgoQuantLib.VecVecString_resize(self, *args)

    def insert(self, *args) -> "void":
        return _AlgoQuantLib.VecVecString_insert(self, *args)

    def reserve(self, n: 'std::vector< std::vector< std::string > >::size_type') -> "void":
        return _AlgoQuantLib.VecVecString_reserve(self, n)

    def capacity(self) -> "std::vector< std::vector< std::string > >::size_type":
        return _AlgoQuantLib.VecVecString_capacity(self)
    __swig_destroy__ = _AlgoQuantLib.delete_VecVecString

# Register VecVecString in _AlgoQuantLib:
_AlgoQuantLib.VecVecString_swigregister(VecVecString)


def setUpMLIB(*args) -> "std::string":
    return _AlgoQuantLib.setUpMLIB(*args)

def setupMLIB(*args) -> "std::string":
    return _AlgoQuantLib.setupMLIB(*args)

def initMLIB(*args) -> "std::string":
    return _AlgoQuantLib.initMLIB(*args)

def tearDownMLIB() -> "std::string":
    return _AlgoQuantLib.tearDownMLIB()

def echoInt(i: 'int') -> "int":
    return _AlgoQuantLib.echoInt(i)

def echoDouble(d: 'double') -> "double":
    return _AlgoQuantLib.echoDouble(d)

def echoChar(c: 'char') -> "char":
    return _AlgoQuantLib.echoChar(c)

def echoBool(b: 'bool') -> "bool":
    return _AlgoQuantLib.echoBool(b)

def echoString(s: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.echoString(s)

def echoVectorInt(v: 'VecInteger') -> "std::vector< int,std::allocator< int > >":
    return _AlgoQuantLib.echoVectorInt(v)

def echoVectorDouble(v: 'VecDouble') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.echoVectorDouble(v)

def echoVectorString(v: 'VecString') -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.echoVectorString(v)

def echoMatrixInt(m: 'VecVecInteger') -> "std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >":
    return _AlgoQuantLib.echoMatrixInt(m)

def echoMatrixDouble(m: 'VecVecDouble') -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >":
    return _AlgoQuantLib.echoMatrixDouble(m)

def echoMatrixString(m: 'VecVecString') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.echoMatrixString(m)

def exampleInt() -> "int":
    return _AlgoQuantLib.exampleInt()

def exampleDouble() -> "double":
    return _AlgoQuantLib.exampleDouble()

def exampleChar() -> "char":
    return _AlgoQuantLib.exampleChar()

def exampleBool() -> "bool":
    return _AlgoQuantLib.exampleBool()

def exampleString() -> "std::string":
    return _AlgoQuantLib.exampleString()

def exampleVectorInt() -> "std::vector< int,std::allocator< int > >":
    return _AlgoQuantLib.exampleVectorInt()

def exampleVectorDouble() -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.exampleVectorDouble()

def exampleVectorString() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.exampleVectorString()

def exampleMatrixInt() -> "std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >":
    return _AlgoQuantLib.exampleMatrixInt()

def exampleMatrixDouble() -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >":
    return _AlgoQuantLib.exampleMatrixDouble()

def exampleMatrixString() -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.exampleMatrixString()

def getInt() -> "int":
    return _AlgoQuantLib.getInt()

def getDouble() -> "double":
    return _AlgoQuantLib.getDouble()

def getChar() -> "char":
    return _AlgoQuantLib.getChar()

def getBool() -> "bool":
    return _AlgoQuantLib.getBool()

def getStdString() -> "std::string":
    return _AlgoQuantLib.getStdString()

def getVectorOfInt() -> "std::vector< int,std::allocator< int > > const":
    return _AlgoQuantLib.getVectorOfInt()

def getVectorOfVectorOfInt() -> "std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > const":
    return _AlgoQuantLib.getVectorOfVectorOfInt()

def getVectorOfDouble() -> "std::vector< double,std::allocator< double > > const":
    return _AlgoQuantLib.getVectorOfDouble()

def getVectorOfVectorOfDouble() -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > const":
    return _AlgoQuantLib.getVectorOfVectorOfDouble()

def getVectorOfString() -> "std::vector< std::string,std::allocator< std::string > > const":
    return _AlgoQuantLib.getVectorOfString()

def getVectorOfVectorOfString() -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > > const":
    return _AlgoQuantLib.getVectorOfVectorOfString()

def testVectorOfVectorOfDoubles(_in: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.testVectorOfVectorOfDoubles(_in)

def throwAnException() -> "int const":
    return _AlgoQuantLib.throwAnException()

def throwAnIllegalArgumentException() -> "int const":
    return _AlgoQuantLib.throwAnIllegalArgumentException()

def sumUp(*args) -> "double const":
    return _AlgoQuantLib.sumUp(*args)

def doSomeFormula(z: 'double const') -> "double":
    return _AlgoQuantLib.doSomeFormula(z)

def mirSetUpOISCurve(CurveID: 'std::string const &', MarketName: 'std::string const &', GeneralProps: 'VecVecString', OISConv: 'VecVecString', OISRates: 'VecVecString', CurveNames: 'std::string const &', OISHistRates: 'VecVecString', LOBasisRates: 'VecVecString', SwapConv: 'VecVecString', SwapRates: 'VecVecString', LOBasisConv: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.mirSetUpOISCurve(CurveID, MarketName, GeneralProps, OISConv, OISRates, CurveNames, OISHistRates, LOBasisRates, SwapConv, SwapRates, LOBasisConv)

def mirSetUpSwapCurve(CurveID: 'std::string const &', MarketName: 'std::string const &', YldData: 'VecVecString', MData: 'VecVecString', LData: 'VecVecString', LGrid: 'VecVecString', SData: 'VecVecString', SGrid: 'VecVecString', FRAData: 'VecVecString', FRA3MGrid: 'VecVecString', FRA6MGrid: 'VecVecString', FData: 'VecVecString', FGrid: 'VecVecString', AdjData: 'VecVecString', AdjGrid: 'VecVecString', CurveNames: 'std::string const &', CurveName_DF2: 'std::string const &') -> "std::string const":
    return _AlgoQuantLib.mirSetUpSwapCurve(CurveID, MarketName, YldData, MData, LData, LGrid, SData, SGrid, FRAData, FRA3MGrid, FRA6MGrid, FData, FGrid, AdjData, AdjGrid, CurveNames, CurveName_DF2)

def mirSetUpBasisSwapCurve(*args) -> "std::string const":
    return _AlgoQuantLib.mirSetUpBasisSwapCurve(*args)

def mirGetDateFromTerm(FromDate: 'std::string const &', TermY: 'double', DayCount: 'std::string const &', IncludeLast: 'bool') -> "std::string const":
    return _AlgoQuantLib.mirGetDateFromTerm(FromDate, TermY, DayCount, IncludeLast)

def mirGetDate(*args) -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.mirGetDate(*args)

def mirGetIMMDate1(Year: 'int', Month: 'int', Calendar: 'std::string const &', SlidingRule: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.mirGetIMMDate1(Year, Month, Calendar, SlidingRule)

def mirGetIMMDate2(Year: 'int', Number: 'int', Calendar: 'std::string const &', SlidingRule: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.mirGetIMMDate2(Year, Number, Calendar, SlidingRule)

def mirGetIMMDate3(BaseDate: 'std::string const &', Number: 'int', Calendar: 'std::string const &', SlidingRule: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.mirGetIMMDate3(BaseDate, Number, Calendar, SlidingRule)

def mirGetParRate4(EffDt: 'std::string const &', Mat: 'std::string const &', CrvID: 'std::string const &', XFreq: 'std::string const &', XDayCt: 'std::string const &', XRollCnv: 'std::string const &', XCal: 'std::string const &', XFirstStub: 'std::string const &', XLastStub: 'std::string const &', XRollDay: 'std::string const &', XPayLag: 'std::string const &', XStub: 'std::string const &', TFreq: 'std::string const &', TDayCt: 'std::string const &', TRollCnv: 'std::string const &', TCal: 'std::string const &', TFirstStub: 'std::string const &', TLastStub: 'std::string const &', TRollDay: 'std::string const &', TFixLag: 'std::string const &', TFirstFix: 'double', TLastFix: 'double', TPayLag: 'std::string const &', TStub: 'std::string const &', Interp: 'std::string const &', Fcrv: 'std::string const &', Dcrv: 'std::string const &', InterpFwds: 'bool', EomRoll: 'bool', TSpd: 'double', UseFwdData: 'bool') -> "double":
    return _AlgoQuantLib.mirGetParRate4(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData)

def mirGetParRate5(EffDt: 'std::string const &', Mat: 'std::string const &', CrvID: 'std::string const &', XFreq: 'std::string const &', XDayCt: 'std::string const &', XRollCnv: 'std::string const &', XCal: 'std::string const &', XFirstStub: 'std::string const &', XLastStub: 'std::string const &', XRollDay: 'std::string const &', XPayLag: 'std::string const &', XStub: 'std::string const &', TFreq: 'std::string const &', TDayCt: 'std::string const &', TRollCnv: 'std::string const &', TCal: 'std::string const &', TFirstStub: 'std::string const &', TLastStub: 'std::string const &', TRollDay: 'std::string const &', TFixLag: 'std::string const &', TFirstFix: 'double', TLastFix: 'double', TPayLag: 'std::string const &', TStub: 'std::string const &', Interp: 'std::string const &', Fcrv: 'std::string const &', Dcrv: 'std::string const &', InterpFwds: 'bool', EomRoll: 'bool', TSpd: 'double', UseFwdData: 'bool', TFixCalc: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirGetParRate5(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData, TFixCalc)

def mirGetParRate3(fromDate: 'std::string const &', toDate: 'std::string const &', curveId: 'std::string const &', frequency: 'std::string const &', dayCount: 'std::string const &', slidingRule: 'std::string const &', calendar: 'std::string const &', interpolation: 'std::string const &', firstOddDate: 'std::string const &', lastOddDate: 'std::string const &', paymentDay: 'std::string const &', foreCurveName: 'std::string const &', dfCurveName: 'std::string const &', interpFwds: 'bool', eomRoll: 'bool') -> "double":
    return _AlgoQuantLib.mirGetParRate3(fromDate, toDate, curveId, frequency, dayCount, slidingRule, calendar, interpolation, firstOddDate, lastOddDate, paymentDay, foreCurveName, dfCurveName, interpFwds, eomRoll)

def mirOISParRate(EffDt: 'std::string const &', Mat: 'std::string const &', CrvID: 'std::string const &', XFreq: 'std::string const &', XDayCt: 'std::string const &', XRollCnv: 'std::string const &', XCal: 'std::string const &', XFirstStub: 'std::string const &', XLastStub: 'std::string const &', XRollDay: 'std::string const &', XPayLag: 'std::string const &', XStub: 'std::string const &', TFreq: 'std::string const &', TDayCt: 'std::string const &', TRollCnv: 'std::string const &', TCal: 'std::string const &', TFirstStub: 'std::string const &', TLastStub: 'std::string const &', TRollDay: 'std::string const &', TFixLag: 'std::string const &', TFirstFix: 'double', TLastFix: 'double', TPayLag: 'std::string const &', TStub: 'std::string const &', Interp: 'std::string const &', Fcrv: 'std::string const &', Dcrv: 'std::string const &', EomRoll: 'bool', TSpd: 'double', CompMethod: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirOISParRate(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, TSpd, CompMethod)

def mirOISSwapPV(notional: 'double', PayRec: 'std::string const &', EffDt: 'std::string const &', Mat: 'std::string const &', CrvID: 'std::string const &', XRt: 'double', XFreq: 'std::string const &', XDayCt: 'std::string const &', XRollCnv: 'std::string const &', XCal: 'std::string const &', XFirstStub: 'std::string const &', XLastStub: 'std::string const &', XRollDay: 'std::string const &', XPayLag: 'std::string const &', XStub: 'std::string const &', TSpd: 'double', TFreq: 'std::string const &', TDayCt: 'std::string const &', TRollCnv: 'std::string const &', TCal: 'std::string const &', TFirstStub: 'std::string const &', TLastStub: 'std::string const &', TRollDay: 'std::string const &', TFixLag: 'std::string const &', TFirstFix: 'double', TLastFix: 'double', TPayLag: 'std::string const &', TStub: 'std::string const &', Interp: 'std::string const &', Fcrv: 'std::string const &', Dcrv: 'std::string const &', EomRoll: 'bool', CompMethod: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirOISSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, CompMethod)

def mirSwapPV(notional: 'double', PayRec: 'std::string const &', EffDt: 'std::string const &', Mat: 'std::string const &', CrvID: 'std::string const &', XRt: 'double', XFreq: 'std::string const &', XDayCt: 'std::string const &', XRollCnv: 'std::string const &', XCal: 'std::string const &', XFirstStub: 'std::string const &', XLastStub: 'std::string const &', XRollDay: 'std::string const &', XPayLag: 'std::string const &', XStub: 'std::string const &', TSpd: 'double', TFreq: 'std::string const &', TDayCt: 'std::string const &', TRollCnv: 'std::string const &', TCal: 'std::string const &', TFirstStub: 'std::string const &', TLastStub: 'std::string const &', TRollDay: 'std::string const &', TFixLag: 'std::string const &', TFirstFix: 'double', TLastFix: 'double', TPayLag: 'std::string const &', TStub: 'std::string const &', Interp: 'std::string const &', Fcrv: 'std::string const &', Dcrv: 'std::string const &', InterpFwds: 'bool', EomRoll: 'bool') -> "double":
    return _AlgoQuantLib.mirSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll)

def mirGetDF1(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetDF1(*args)

def mirGetDF2(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetDF2(*args)

def mirGetDF3(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetDF3(*args)

def mirGetDF4(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetDF4(*args)

def mirGetDF5(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetDF5(*args)

def mirGetPCAResults(ID: 'std::string const &', update: 'int') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.mirGetPCAResults(ID, update)

def mirSetupPCA(ID: 'std::string const &', data: 'VecVecDouble', IsScale: 'bool', FactorNum: 'int') -> "std::string":
    return _AlgoQuantLib.mirSetupPCA(ID, data, IsScale, FactorNum)

def mirInterpolation(array1: 'VecDouble', array2: 'VecDouble', point: 'double', interpolation: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirInterpolation(array1, array2, point, interpolation)

def mirGetForwardRate2(fromDates: 'VecString', toDates: 'VecString', curveId: 'std::string const &', frequency: 'std::string const &', dayCount: 'std::string const &', slidingRule: 'std::string const &', calendar: 'std::string const &', interpolation: 'std::string const &', curveName: 'std::string const &', isFwdInterp: 'bool', useFwdData: 'bool') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetForwardRate2(fromDates, toDates, curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp, useFwdData)

def mirSetUpFwdFXConstantCurve(CurveID: 'std::string const &', MarketName: 'std::string const &', GeneralProps: 'VecVecString', FwdFXConstantConv: 'VecVecString', CurveNames: 'std::string const &') -> "std::string const":
    return _AlgoQuantLib.mirSetUpFwdFXConstantCurve(CurveID, MarketName, GeneralProps, FwdFXConstantConv, CurveNames)

def mirSwapStubRate(EffDt: 'std::string const &', Mat: 'std::string const &', Freq: 'std::string const &', DayCt: 'std::string const &', RollCnv: 'std::string const &', Cal: 'std::string const &', RollDay: 'std::string const &', FixLag: 'std::string const &', EomRoll: 'bool', Interpolation: 'std::string const &', FirstStub: 'std::string const &', LastStub: 'std::string const &', StubType: 'std::string const &', CrvID: 'std::string const &', CurveNames: 'VecString', CurveTenors: 'VecString', TenorCurveFixings: 'VecDouble', UseCurveName: 'std::string const &', ToleranceTenor: 'std::string const &', IsFwdInterp: 'bool', UseFwdData: 'bool') -> "double":
    return _AlgoQuantLib.mirSwapStubRate(EffDt, Mat, Freq, DayCt, RollCnv, Cal, RollDay, FixLag, EomRoll, Interpolation, FirstStub, LastStub, StubType, CrvID, CurveNames, CurveTenors, TenorCurveFixings, UseCurveName, ToleranceTenor, IsFwdInterp, UseFwdData)

def mirGetZeroRate1(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetZeroRate1(*args)

def mirGetZeroRate2(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.mirGetZeroRate2(*args)

def mirOutputCurve(curveId: 'std::string const &', curveName: 'std::string const &') -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >":
    return _AlgoQuantLib.mirOutputCurve(curveId, curveName)

def mirSwapPV01(notional: 'double', payRec: 'std::string const &', effectDt: 'std::string const &', maturity: 'std::string const &', curveId: 'std::string const &', xFreq: 'std::string const &', xDayCount: 'std::string const &', xRollCnv: 'std::string const &', xCalendar: 'std::string const &', xFirstStub: 'std::string const &', xLastStub: 'std::string const &', xRollDay: 'std::string const &', xPayLag: 'std::string const &', xStub: 'std::string const &', tSpread: 'double', tFreq: 'std::string const &', tDayCount: 'std::string const &', tRollCnv: 'std::string const &', tCalendar: 'std::string const &', tFirstStub: 'std::string const &', tLastStub: 'std::string const &', tRollDay: 'std::string const &', tFixLag: 'std::string const &', tFirstFix: 'double', tLastFix: 'double', tPayLag: 'std::string const &', tStub: 'std::string const &', interpolation: 'std::string const &', forecastCurve: 'std::string const &', discountCurve: 'std::string const &', interpFwds: 'bool', eomRoll: 'bool') -> "double":
    return _AlgoQuantLib.mirSwapPV01(notional, payRec, effectDt, maturity, curveId, xFreq, xDayCount, xRollCnv, xCalendar, xFirstStub, xLastStub, xRollDay, xPayLag, xStub, tSpread, tFreq, tDayCount, tRollCnv, tCalendar, tFirstStub, tLastStub, tRollDay, tFixLag, tFirstFix, tLastFix, tPayLag, tStub, interpolation, forecastCurve, discountCurve, interpFwds, eomRoll)

def mirCompound3(*args) -> "double":
    return _AlgoQuantLib.mirCompound3(*args)

def mirGetAnnuity1(fromDate: 'std::string const &', toDate: 'std::string const &', curveId: 'std::string const &', frequency: 'std::string const &', slidingRule: 'std::string const &', calendar: 'std::string const &', firstOddDate: 'std::string const &', lastOddDate: 'std::string const &', paymentDay: 'std::string const &', dayCount: 'std::string const &', interpolation: 'std::string const &', curveName: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirGetAnnuity1(fromDate, toDate, curveId, frequency, slidingRule, calendar, firstOddDate, lastOddDate, paymentDay, dayCount, interpolation, curveName)

def mirGetAnnuity2(curveId: 'std::string const &', dates: 'VecString', dayCount: 'std::string const &', interpolation: 'std::string const &', curveName: 'std::string const &') -> "double":
    return _AlgoQuantLib.mirGetAnnuity2(curveId, dates, dayCount, interpolation, curveName)

def mirGetBusinessDays(fromDate: 'std::string const &', toDate: 'std::string const &', calendar: 'std::string const &') -> "int":
    return _AlgoQuantLib.mirGetBusinessDays(fromDate, toDate, calendar)

def mirGetECBStartDate(ecbDate: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.mirGetECBStartDate(ecbDate)

def mirGetNextCBDate(centralBankId: 'std::string const &', baseDate: 'std::string const &', strictlyAfter: 'bool') -> "std::string":
    return _AlgoQuantLib.mirGetNextCBDate(centralBankId, baseDate, strictlyAfter)

def mirGetNextECBDate(baseDate: 'std::string const &', strictlyAfter: 'bool') -> "std::string":
    return _AlgoQuantLib.mirGetNextECBDate(baseDate, strictlyAfter)

def mirGetTerm(fromDate: 'std::string const &', toDate: 'std::string const &', dayCount: 'std::string const &', includeLast: 'bool') -> "double":
    return _AlgoQuantLib.mirGetTerm(fromDate, toDate, dayCount, includeLast)

def mirSwapSchedule(accrualStartDate: 'std::string const &', accrualEndDateOrTenor: 'std::string const &', accrualDaycount: 'std::string const &', accrualFrequency: 'std::string const &', accrualSlidingRule: 'std::string const &', accrualCalendar: 'std::string const &', paymentFrequency: 'std::string const &', paymentSlidingRule: 'std::string const &', paymentCalendar: 'std::string const &', paymentLag: 'std::string const &', fixingSlidingRule: 'std::string const &', fixingCalendar: 'std::string const &', fixingLag: 'std::string const &', fixingAdvanceOrArrears: 'std::string const &', firstStub: 'std::string const &', lastStub: 'std::string const &', paymentRollDay: 'std::string const &', showColumnHeaders: 'bool') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.mirSwapSchedule(accrualStartDate, accrualEndDateOrTenor, accrualDaycount, accrualFrequency, accrualSlidingRule, accrualCalendar, paymentFrequency, paymentSlidingRule, paymentCalendar, paymentLag, fixingSlidingRule, fixingCalendar, fixingLag, fixingAdvanceOrArrears, firstStub, lastStub, paymentRollDay, showColumnHeaders)

def mirClearEntityPool() -> "std::string":
    return _AlgoQuantLib.mirClearEntityPool()

def meCurveCalibrateBasis(*args) -> "std::string const":
    return _AlgoQuantLib.meCurveCalibrateBasis(*args)

def meCurveCalibrateFXForwards(curveCollection: 'std::string const &', staticDataTable: 'std::string const &', curveIndex: 'std::string const &', curveConv: 'VecVecString', fxFwdConv: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.meCurveCalibrateFXForwards(curveCollection, staticDataTable, curveIndex, curveConv, fxFwdConv)

def meCurveCalibrateOIS(curveCollection: 'std::string const &', staticDataTable: 'std::string const &', curveIndex: 'std::string const &', curveConv: 'VecVecString', oisConv: 'VecVecString', oisRates: 'VecVecString', oisHistoricalRates: 'VecVecString', liborOisBasisConv: 'VecVecString', liborOisBasisRates: 'VecVecString', swapConv: 'VecVecString', swapRates: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.meCurveCalibrateOIS(curveCollection, staticDataTable, curveIndex, curveConv, oisConv, oisRates, oisHistoricalRates, liborOisBasisConv, liborOisBasisRates, swapConv, swapRates)

def meCurveCalibrateSwap(curveCollection: 'std::string const &', staticDataTable: 'std::string const &', curveIndex: 'std::string const &', curveConv: 'VecVecString', moneyMarketConv: 'VecVecString', liborConv: 'VecVecString', liborRates: 'VecVecString', swapConv: 'VecVecString', swapRates: 'VecVecString', fraConv: 'VecVecString', fra3mRates: 'VecVecString', fra6mRates: 'VecVecString', futureConv: 'VecVecString', futureRates: 'VecVecString', tenorBasisConv: 'VecVecString', tenorBasisRates: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.meCurveCalibrateSwap(curveCollection, staticDataTable, curveIndex, curveConv, moneyMarketConv, liborConv, liborRates, swapConv, swapRates, fraConv, fra3mRates, fra6mRates, futureConv, futureRates, tenorBasisConv, tenorBasisRates)

def meCurveCompoundRate(*args) -> "double":
    return _AlgoQuantLib.meCurveCompoundRate(*args)

def meCurveDiscountFactors(paymentDates: 'VecString', curveCollection: 'std::string const &', curveIndex: 'std::string const &') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactors(paymentDates, curveCollection, curveIndex)

def meCurveDiscountFactorsFromYearFractions(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactorsFromYearFractions(*args)

def meCurveDiscountFactorsFromTenors(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactorsFromTenors(*args)

def meCurveDiscountFactorsForwardStarting(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactorsForwardStarting(*args)

def meCurveDiscountFactorsForwardStartingFromYearFractions(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactorsForwardStartingFromYearFractions(*args)

def meCurveDiscountFactorsForwardStartingFromTenor(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveDiscountFactorsForwardStartingFromTenor(*args)

def meCurveDisplay(curveCollection: 'std::string const &', curveIndex: 'std::string const &') -> "std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >":
    return _AlgoQuantLib.meCurveDisplay(curveCollection, curveIndex)

def meCurveForwardRatesFromYearFraction(fromDates: 'VecString', yearFraction: 'double', curveCollection: 'std::string const &', curveIndex: 'std::string const &', dayCount: 'std::string const &') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveForwardRatesFromYearFraction(fromDates, yearFraction, curveCollection, curveIndex, dayCount)

def meCurveForwardRates(fixingDates: 'VecString', curveCollection: 'std::string const &', curveIndex: 'std::string const &') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveForwardRates(fixingDates, curveCollection, curveIndex)

def meCurveForwardRatesFromForwardDates(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveForwardRatesFromForwardDates(*args)

def meCurveZeroRatesFromYearFractions(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveZeroRatesFromYearFractions(*args)

def meCurveZeroRatesFromTenors(*args) -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meCurveZeroRatesFromTenors(*args)

def meDateFromTenor(*args) -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meDateFromTenor(*args)

def meDateFromYearFraction(startDate: 'std::string const &', yearFraction: 'double', dayCount: 'std::string const &') -> "std::string const":
    return _AlgoQuantLib.meDateFromYearFraction(startDate, yearFraction, dayCount)

def meDateBusinessDays(fromDate: 'std::string const &', toDate: 'std::string const &', calendar: 'std::string const &') -> "int":
    return _AlgoQuantLib.meDateBusinessDays(fromDate, toDate, calendar)

def meDateYearFraction(*args) -> "double":
    return _AlgoQuantLib.meDateYearFraction(*args)

def meLWOSwapUSDSpotDate(asOfDate: 'std::string const &', spotLag: 'std::string const &', fixingCalendar: 'std::string const &', paymentCalendar: 'std::string const &', businessDayAdj: 'std::string const &', rollConvention: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meLWOSwapUSDSpotDate(asOfDate, spotLag, fixingCalendar, paymentCalendar, businessDayAdj, rollConvention)

def meDateShiftedSpotDate(asOfDate: 'std::string const &', fixingLag: 'std::string const &', fixingCalendar: 'std::string const &', fixingBusDayAdj: 'std::string const &', paymentLag: 'std::string const &', paymentCalendar: 'std::string const &', paymentBusDayAdj: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateShiftedSpotDate(asOfDate, fixingLag, fixingCalendar, fixingBusDayAdj, paymentLag, paymentCalendar, paymentBusDayAdj)

def meDateCentralBank(centralBankId: 'std::string const &', date: 'std::string const &', strictlyAfter: 'bool') -> "std::string":
    return _AlgoQuantLib.meDateCentralBank(centralBankId, date, strictlyAfter)

def meDateECB(date: 'std::string const &', strictlyAfter: 'bool') -> "std::string":
    return _AlgoQuantLib.meDateECB(date, strictlyAfter)

def meDateECBSwapStart(date: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateECBSwapStart(date)

def meDateECBSwapEnd(date: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateECBSwapEnd(date)

def meDateIMMFromMonth(year: 'int', month: 'int', calendar: 'std::string const &', businessDayAdj: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateIMMFromMonth(year, month, calendar, businessDayAdj)

def meDateNthIMM(year: 'int', nth: 'int', calendar: 'std::string const &', businessDayAdj: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateNthIMM(year, nth, calendar, businessDayAdj)

def meDateNthIMMFromStartDate(startDate: 'std::string const &', nth: 'int', calendar: 'std::string const &', businessDayAdj: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meDateNthIMMFromStartDate(startDate, nth, calendar, businessDayAdj)

def meProductAssetSwapSpread(bondCleanPrice: 'double', assetSwapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductAssetSwapSpread(bondCleanPrice, assetSwapLVB, validateKeys)

def meProductAssetSwapSpreadLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductAssetSwapSpreadLVBKeys()

def meProductOISParRate(oisSwapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductOISParRate(oisSwapLVB, validateKeys)

def meProductOISParRateLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductOISParRateLVBKeys()

def meProductOISPV(oisSwapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductOISPV(oisSwapLVB, validateKeys)

def meProductOISPVLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductOISPVLVBKeys()

def meProductSwapDV01(swapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductSwapDV01(swapLVB, validateKeys)

def meProductSwapDV01LVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductSwapDV01LVBKeys()

def meProductSwapParRate(swapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductSwapParRate(swapLVB, validateKeys)

def meProductSwapParRateLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductSwapParRateLVBKeys()

def meProductSwapPV(swapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductSwapPV(swapLVB, validateKeys)

def tryMeProductSwapPVLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.tryMeProductSwapPVLVBKeys()

def meProductSwapPV01(swapLVB: 'VecVecString', validateKeys: 'bool'=True) -> "double":
    return _AlgoQuantLib.meProductSwapPV01(swapLVB, validateKeys)

def meProductSwapPV01LVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductSwapPV01LVBKeys()

def meProductSwapSchedule(showColumnHeaders: 'bool', swapScheduleLVB: 'VecVecString', validateKeys: 'bool'=True) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meProductSwapSchedule(showColumnHeaders, swapScheduleLVB, validateKeys)

def meProductSwapScheduleFixed(showColumnHeaders: 'bool', swapScheduleLVB: 'VecVecString') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meProductSwapScheduleFixed(showColumnHeaders, swapScheduleLVB)

def meProductSwapScheduleFloat(showColumnHeaders: 'bool', swapScheduleLVB: 'VecVecString') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meProductSwapScheduleFloat(showColumnHeaders, swapScheduleLVB)

def meProductSwapScheduleLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductSwapScheduleLVBKeys()

def meProductSwapStubRate(curveIndices: 'VecString', curveTenors: 'VecString', tenorCurveFixings: 'VecDouble', swapLVB: 'VecVecString', validateKeys: 'bool') -> "double":
    return _AlgoQuantLib.meProductSwapStubRate(curveIndices, curveTenors, tenorCurveFixings, swapLVB, validateKeys)

def meProductSwapStubRateLVBKeys() -> "std::vector< std::string,std::allocator< std::string > >":
    return _AlgoQuantLib.meProductSwapStubRateLVBKeys()

def meUtilityInterpolation(array1: 'VecDouble', array2: 'VecDouble', point: 'double', interpolation: 'std::string const &') -> "double":
    return _AlgoQuantLib.meUtilityInterpolation(array1, array2, point, interpolation)

def meUtilityPCA(key: 'std::string const &', data: 'VecVecDouble', useCorrelationMatrix: 'bool', nFactors: 'int') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meUtilityPCA(key, data, useCorrelationMatrix, nFactors)

def meUtilityRecord(enable: 'bool', folder: 'std::string const &', repeat: 'bool', startIndex: 'int', maxIndex: 'int') -> "std::string":
    return _AlgoQuantLib.meUtilityRecord(enable, folder, repeat, startIndex, maxIndex)

def meUtilityClearEntityPool() -> "std::string":
    return _AlgoQuantLib.meUtilityClearEntityPool()

def meUtilityClearLWOCache() -> "std::string":
    return _AlgoQuantLib.meUtilityClearLWOCache()

def meUtilityLoadCalendarFile(filepath: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meUtilityLoadCalendarFile(filepath)

def meUtilityLoadStaticData(filepath: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meUtilityLoadStaticData(filepath)

def meUtilityVersion() -> "std::string":
    return _AlgoQuantLib.meUtilityVersion()

def meUtilityParallelModeEnable(enable: 'bool const') -> "std::string":
    return _AlgoQuantLib.meUtilityParallelModeEnable(enable)

def meUtilityParallelModeStatus() -> "std::string":
    return _AlgoQuantLib.meUtilityParallelModeStatus()

def meCurveInterpolationJoinDate(curveCollection: 'std::string const &', curveIndex: 'std::string const &', interpolation: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meCurveInterpolationJoinDate(curveCollection, curveIndex, interpolation)

def meCurveDualBootstrap(curveCollection: 'std::string const &', curveName_db: 'std::string const &', curveName_OIS: 'std::string const &', curveName_swap: 'std::string const &', curveIndex_OIS: 'std::string const &', curveIndex_swap: 'std::string const &', commonParams: 'VecVecString', generateProp_OIS: 'VecVecString', oisRates_OIS: 'VecVecString', oisConv_OIS: 'VecVecString', histRates_OIS: 'VecVecString', lobasisRates_OIS: 'VecVecString', lobasisConv_OIS: 'VecVecString', swapConv_OIS: 'VecVecString', generateProp_swap: 'VecVecString', moneyConv_swap: 'VecVecString', liborRates_swap: 'VecVecString', liborConv_swap: 'VecVecString', swapRates_swap: 'VecVecString', swapConv_swap: 'VecVecString', fra3mRates_swap: 'VecVecString', fra6mRates_swap: 'VecVecString', fraConv_swap: 'VecVecString', futureRates_swap: 'VecVecString', futureConv_swap: 'VecVecString', tenorBasisConv_swap: 'VecVecString', tenorBasisRates_swap: 'VecVecString') -> "std::string const":
    return _AlgoQuantLib.meCurveDualBootstrap(curveCollection, curveName_db, curveName_OIS, curveName_swap, curveIndex_OIS, curveIndex_swap, commonParams, generateProp_OIS, oisRates_OIS, oisConv_OIS, histRates_OIS, lobasisRates_OIS, lobasisConv_OIS, swapConv_OIS, generateProp_swap, moneyConv_swap, liborRates_swap, liborConv_swap, swapRates_swap, swapConv_swap, fra3mRates_swap, fra6mRates_swap, fraConv_swap, futureRates_swap, futureConv_swap, tenorBasisConv_swap, tenorBasisRates_swap)

def meLWOSave(objectName: 'std::string const &', objectType: 'std::string const &', filePath: 'std::string const &') -> "std::string const":
    return _AlgoQuantLib.meLWOSave(objectName, objectType, filePath)

def meLWOLoad(filePath: 'std::string const &') -> "std::string const":
    return _AlgoQuantLib.meLWOLoad(filePath)

def meLWOBondCreate(bondObjectName: 'std::string const &', bondLVB: 'VecVecString', scheduleLVB: 'VecVecString', validateKeys: 'bool const') -> "std::string const":
    return _AlgoQuantLib.meLWOBondCreate(bondObjectName, bondLVB, scheduleLVB, validateKeys)

def meLWOBondCreateFromGenerator(bondObjectName: 'std::string const &', bondGeneratorName: 'std::string const &', bondExpressionLVB: 'VecVecString', validateKeys: 'bool const') -> "std::string const":
    return _AlgoQuantLib.meLWOBondCreateFromGenerator(bondObjectName, bondGeneratorName, bondExpressionLVB, validateKeys)

def meLWOBondPrice(bondObjectName: 'std::string const &', settlementDates: 'VecString', yields: 'VecDouble', yieldCalculationType: 'std::string const &') -> "std::vector< double,std::allocator< double > > const":
    return _AlgoQuantLib.meLWOBondPrice(bondObjectName, settlementDates, yields, yieldCalculationType)

def meLWOBondCleanPrice(bondObjectName: 'std::string const &', settlementDates: 'VecString', yields: 'VecDouble', yieldCalculationType: 'std::string const &') -> "std::vector< double,std::allocator< double > > const":
    return _AlgoQuantLib.meLWOBondCleanPrice(bondObjectName, settlementDates, yields, yieldCalculationType)

def meLWOBondDirtyPrice(bondObjectName: 'std::string const &', settlementDates: 'VecString', yields: 'VecDouble', yieldCalculationType: 'std::string const &') -> "std::vector< double,std::allocator< double > > const":
    return _AlgoQuantLib.meLWOBondDirtyPrice(bondObjectName, settlementDates, yields, yieldCalculationType)

def meLWOBondYield(bondObjectName: 'std::string const &', settlementDates: 'VecString', quotedPrices: 'VecDouble', yieldCalculationType: 'std::string const &', optimizePerformance: 'bool const &') -> "std::vector< double,std::allocator< double > > const":
    return _AlgoQuantLib.meLWOBondYield(bondObjectName, settlementDates, quotedPrices, yieldCalculationType, optimizePerformance)

def meLWOBondForwardPrice(bondObjectName: 'std::string const &', settleDate: 'std::string const &', forwardSettleDate: 'std::string const &', price: 'double const &', repoRate: 'double const &', repoDayCount: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOBondForwardPrice(bondObjectName, settleDate, forwardSettleDate, price, repoRate, repoDayCount)

def meUtilityLVBCreate(*args) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meUtilityLVBCreate(*args)

def meUtilityLVBAppendAndCreate(*args) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meUtilityLVBAppendAndCreate(*args)

def meUtilityLVBAdd(*args) -> "void":
    return _AlgoQuantLib.meUtilityLVBAdd(*args)

def meLWOSwapCreate(swapObjectName: 'std::string const &', swapLVB: 'VecVecString', xccyPropertiesLVB: 'VecVecString', isXccySwap: 'bool const', validateKeys: 'bool const') -> "std::string const":
    return _AlgoQuantLib.meLWOSwapCreate(swapObjectName, swapLVB, xccyPropertiesLVB, isXccySwap, validateKeys)

def meLWOSwapCreateFromGenerator(swapObjectName: 'std::string const &', swapGeneratorName: 'std::string const &', swapLVB: 'VecVecString', xccyPropertiesLVB: 'VecVecString', isXccySwap: 'bool const', validateKeys: 'bool const') -> "std::string const":
    return _AlgoQuantLib.meLWOSwapCreateFromGenerator(swapObjectName, swapGeneratorName, swapLVB, xccyPropertiesLVB, isXccySwap, validateKeys)

def meLWOSwapPV(swapName: 'std::string const &', valuationSettings: 'VecVecString', legName: 'std::string const &', fixingTableNames: 'VecVecString') -> "double":
    return _AlgoQuantLib.meLWOSwapPV(swapName, valuationSettings, legName, fixingTableNames)

def meLWOSwapPV01(swapName: 'std::string const &', valuationSettings: 'VecVecString', fixingTableNames: 'VecVecString') -> "double":
    return _AlgoQuantLib.meLWOSwapPV01(swapName, valuationSettings, fixingTableNames)

def meLWOSwapParRate(*args) -> "double":
    return _AlgoQuantLib.meLWOSwapParRate(*args)

def meLWOSwapAnnuity(swapName: 'std::string const &', valuationSettings: 'VecVecString', legName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOSwapAnnuity(swapName, valuationSettings, legName)

def meLWOSwapParSpread(swapName: 'std::string const &', valuationSettings: 'VecVecString', fixingTableNames: 'VecVecString', spreadLegName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOSwapParSpread(swapName, valuationSettings, fixingTableNames, spreadLegName)

def meLWOSwapSpread(swapName: 'std::string const &', valuationSettings: 'VecVecString', fixingTableNames: 'VecVecString', spreadLegName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOSwapSpread(swapName, valuationSettings, fixingTableNames, spreadLegName)

def meLWOSwapDisplayCashflows(swapName: 'std::string const &', valuationSettings: 'VecVecString', legName: 'std::string const &', fixingTableNames: 'VecVecString', showColumnHeaders: 'bool const') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOSwapDisplayCashflows(swapName, valuationSettings, legName, fixingTableNames, showColumnHeaders)
class NelsonSiegelSvenssonParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    beta0_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_beta0__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_beta0__set)
    beta1_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_beta1__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_beta1__set)
    beta2_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_beta2__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_beta2__set)
    lambda1_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_lambda1__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_lambda1__set)
    beta3_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_beta3__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_beta3__set)
    lambda2_ = property(_AlgoQuantLib.NelsonSiegelSvenssonParameters_lambda2__get, _AlgoQuantLib.NelsonSiegelSvenssonParameters_lambda2__set)

    def __init__(self, *args):
        _AlgoQuantLib.NelsonSiegelSvenssonParameters_swiginit(self, _AlgoQuantLib.new_NelsonSiegelSvenssonParameters(*args))
    __swig_destroy__ = _AlgoQuantLib.delete_NelsonSiegelSvenssonParameters

# Register NelsonSiegelSvenssonParameters in _AlgoQuantLib:
_AlgoQuantLib.NelsonSiegelSvenssonParameters_swigregister(NelsonSiegelSvenssonParameters)

class NelsonSiegelSvenssonCalibrationResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    parameters_ = property(_AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_parameters__get, _AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_parameters__set)
    leastSquaresError_ = property(_AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_leastSquaresError__get, _AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_leastSquaresError__set)
    iterations_ = property(_AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_iterations__get, _AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_iterations__set)

    def __init__(self):
        _AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_swiginit(self, _AlgoQuantLib.new_NelsonSiegelSvenssonCalibrationResults())
    __swig_destroy__ = _AlgoQuantLib.delete_NelsonSiegelSvenssonCalibrationResults

# Register NelsonSiegelSvenssonCalibrationResults in _AlgoQuantLib:
_AlgoQuantLib.NelsonSiegelSvenssonCalibrationResults_swigregister(NelsonSiegelSvenssonCalibrationResults)

class PolynomialCalibrationResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    coefficients_ = property(_AlgoQuantLib.PolynomialCalibrationResults_coefficients__get, _AlgoQuantLib.PolynomialCalibrationResults_coefficients__set)
    leastSquaresError_ = property(_AlgoQuantLib.PolynomialCalibrationResults_leastSquaresError__get, _AlgoQuantLib.PolynomialCalibrationResults_leastSquaresError__set)
    iterations_ = property(_AlgoQuantLib.PolynomialCalibrationResults_iterations__get, _AlgoQuantLib.PolynomialCalibrationResults_iterations__set)

    def __init__(self):
        _AlgoQuantLib.PolynomialCalibrationResults_swiginit(self, _AlgoQuantLib.new_PolynomialCalibrationResults())
    __swig_destroy__ = _AlgoQuantLib.delete_PolynomialCalibrationResults

# Register PolynomialCalibrationResults in _AlgoQuantLib:
_AlgoQuantLib.PolynomialCalibrationResults_swigregister(PolynomialCalibrationResults)


def meBondCurveNelsonSiegelCalibrate(bondMaturities: 'VecDouble', bondYields: 'VecDouble', initialGuess: 'NelsonSiegelSvenssonParameters', maxIterations: 'unsigned int const &', maxStationaryStateIterations: 'unsigned int const &', lowerBounds: 'VecDouble', upperBounds: 'VecDouble') -> "swig::NelsonSiegelSvenssonCalibrationResults":
    return _AlgoQuantLib.meBondCurveNelsonSiegelCalibrate(bondMaturities, bondYields, initialGuess, maxIterations, maxStationaryStateIterations, lowerBounds, upperBounds)

def meBondCurveSvenssonCalibrate(bondMaturities: 'VecDouble', bondYields: 'VecDouble', initialGuess: 'NelsonSiegelSvenssonParameters', maxIterations: 'unsigned int const &', maxStationaryStateIterations: 'unsigned int const &', lowerBounds: 'VecDouble', upperBounds: 'VecDouble') -> "swig::NelsonSiegelSvenssonCalibrationResults":
    return _AlgoQuantLib.meBondCurveSvenssonCalibrate(bondMaturities, bondYields, initialGuess, maxIterations, maxStationaryStateIterations, lowerBounds, upperBounds)

def meBondCurvePolynomialCalibrate(polynomialOrder: 'unsigned int const', bondMaturities: 'VecDouble', bondYields: 'VecDouble', maxIterations: 'unsigned int const &', maxStationaryStateIterations: 'unsigned int const', lowerBound: 'double const', upperBound: 'double const') -> "swig::PolynomialCalibrationResults":
    return _AlgoQuantLib.meBondCurvePolynomialCalibrate(polynomialOrder, bondMaturities, bondYields, maxIterations, maxStationaryStateIterations, lowerBound, upperBound)

def meBondCurveNelsonSiegelYield(beta0: 'double const &', beta1: 'double const &', beta2: 'double const &', _lambda: 'double const &', bondMaturities: 'VecDouble') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meBondCurveNelsonSiegelYield(beta0, beta1, beta2, _lambda, bondMaturities)

def meBondCurveSvenssonYield(beta0: 'double const &', beta1: 'double const &', beta2: 'double const &', beta3: 'double const &', lambda1: 'double const &', lambda2: 'double const &', bondMaturities: 'VecDouble') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meBondCurveSvenssonYield(beta0, beta1, beta2, beta3, lambda1, lambda2, bondMaturities)

def meBondCurvePolynomialYield(coefficients: 'VecDouble', bondMaturities: 'VecDouble') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meBondCurvePolynomialYield(coefficients, bondMaturities)

def meLWOBondDisplayCashflows(*args) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOBondDisplayCashflows(*args)

def meLWOBondDisplaySchedule(*args) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOBondDisplaySchedule(*args)

def meLWOCreditModelCreate(objectName: 'std::string const &', key1: 'std::string const &', dataBlock1: 'VecVecString', key2: 'std::string const &', dataBlock2: 'VecVecString') -> "std::string":
    return _AlgoQuantLib.meLWOCreditModelCreate(objectName, key1, dataBlock1, key2, dataBlock2)

def meLWOCreditModelSurvivalProbability(creditModelName: 'std::string const &', toDate: 'std::string const &', fromDate: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditModelSurvivalProbability(creditModelName, toDate, fromDate)

def meLWOCreditModelDefaultProbability(creditModelName: 'std::string const &', toDate: 'std::string const &', fromDate: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditModelDefaultProbability(creditModelName, toDate, fromDate)

def meLWOCreditModelHazardRate(creditModelName: 'std::string const &', paymentDate: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditModelHazardRate(creditModelName, paymentDate)

def meLWOCreditModelRiskyDiscountFactor(creditModelName: 'std::string const &', paymentDate: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditModelRiskyDiscountFactor(creditModelName, paymentDate)

def meLWOCreditModelRiskyDiscountFactors(creditModelName: 'std::string const &', paymentDates: 'VecString') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meLWOCreditModelRiskyDiscountFactors(creditModelName, paymentDates)

def meLWOCreditDefaultSwapPV(swapName: 'std::string const &', creditModelName: 'std::string const &', legName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditDefaultSwapPV(swapName, creditModelName, legName)

def meLWOCreditDefaultSwapRiskyAnnuity(swapName: 'std::string const &', creditModelName: 'std::string const &', legName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditDefaultSwapRiskyAnnuity(swapName, creditModelName, legName)

def meLWOCreditDefaultSwapCS01(swapName: 'std::string const &', creditModelName: 'std::string const &', legName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditDefaultSwapCS01(swapName, creditModelName, legName)

def meLWOCreditDefaultSwapParSpread(swapName: 'std::string const &', creditModelName: 'std::string const &', premiumLegName: 'std::string const &', protectionLegName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOCreditDefaultSwapParSpread(swapName, creditModelName, premiumLegName, protectionLegName)

def meLWOTotalReturnSwapPV(*args) -> "double":
    return _AlgoQuantLib.meLWOTotalReturnSwapPV(*args)

def meLWOTotalReturnSwapParRate(*args) -> "double":
    return _AlgoQuantLib.meLWOTotalReturnSwapParRate(*args)

def meLWOTotalReturnSwapParSpread(*args) -> "double":
    return _AlgoQuantLib.meLWOTotalReturnSwapParSpread(*args)

def meLWOTotalReturnSwapAnnuity(swapName: 'std::string const &', creditModelName: 'std::string const &', legName: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOTotalReturnSwapAnnuity(swapName, creditModelName, legName)

def meCurveResultsDisplayDiscountFactors(curveCollection: 'std::string const &', curveIndex: 'std::string const &') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meCurveResultsDisplayDiscountFactors(curveCollection, curveIndex)

def meLWOCurveDisplay(curveHandle: 'std::string const &') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOCurveDisplay(curveHandle)

def meLWOCurveMarketDataDisplay(marketDataObjectName: 'std::string const &', marketDataKey: 'std::string const') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOCurveMarketDataDisplay(marketDataObjectName, marketDataKey)

def meLWOCurveMarketDataDisplayFromCurve(curveObjectName: 'std::string const &', marketDataKey: 'std::string const') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOCurveMarketDataDisplayFromCurve(curveObjectName, marketDataKey)

def meLWOCurveCalibrate(objectName: 'std::string const &', lwoCurveGeneratorName: 'std::string const &', lwoCurveMarketDataName: 'std::string const &', domesticCurveCollection: 'std::string const &', foreignCurveCollection: 'std::string const &') -> "std::string":
    return _AlgoQuantLib.meLWOCurveCalibrate(objectName, lwoCurveGeneratorName, lwoCurveMarketDataName, domesticCurveCollection, foreignCurveCollection)

def meLWOCurveMarketDataCreate(objectName: 'std::string const &', key1: 'std::string const &', value1: 'VecVecString', key2: 'std::string const &', value2: 'VecVecString', key3: 'std::string const &', value3: 'VecVecString', key4: 'std::string const &', value4: 'VecVecString') -> "std::string":
    return _AlgoQuantLib.meLWOCurveMarketDataCreate(objectName, key1, value1, key2, value2, key3, value3, key4, value4)

def meLWOCurveMarketDataCreateUsingMultipleBlocks(objectName: 'std::string const &', keyVector: 'VecString', valueVector: 'std::vector< std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >,std::allocator< std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > > > > const &') -> "std::string":
    return _AlgoQuantLib.meLWOCurveMarketDataCreateUsingMultipleBlocks(objectName, keyVector, valueVector)

def meLWOFixingTableCreate(tableName: 'std::string const &', currency: 'std::string const &', curveTenor: 'std::string const &', fixingDates: 'VecString', fixingValues: 'VecDouble') -> "std::string":
    return _AlgoQuantLib.meLWOFixingTableCreate(tableName, currency, curveTenor, fixingDates, fixingValues)

def meLWOFixingTableDisplay(tableName: 'std::string const &') -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOFixingTableDisplay(tableName)

def meLWOFixingTableValue(tableName: 'std::string const &', fixingDate: 'std::string const &') -> "double":
    return _AlgoQuantLib.meLWOFixingTableValue(tableName, fixingDate)

def meLWOFixingTableValues(tableName: 'std::string const &', fixingDates: 'VecString') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meLWOFixingTableValues(tableName, fixingDates)

def meLWOCurveDiscountFactorsWithSpread(paymentDates: 'VecString', curveCollection: 'std::string const &', curveIndex: 'std::string const &', spread: 'double const &', fixingTableName: 'std::string const &') -> "std::vector< double,std::allocator< double > >":
    return _AlgoQuantLib.meLWOCurveDiscountFactorsWithSpread(paymentDates, curveCollection, curveIndex, spread, fixingTableName)

def meLWOGridDisplay(objectName: 'std::string const &', displayColumnNames: 'bool const &'=False) -> "std::vector< std::vector< std::string,std::allocator< std::string > >,std::allocator< std::vector< std::string,std::allocator< std::string > > > >":
    return _AlgoQuantLib.meLWOGridDisplay(objectName, displayColumnNames)


