#pragma once

#ifdef __GNUG__
#pragma interface
#endif

#include "AQLCoreAppError.h"
#include "AQLString.h"
#include "AQLObjectHolder.h"

// map of Object registered in the Object Pool(Object name and Object Holder)
typedef std::map<AQLString, AQLObjectHolder>				   EntityPool;

// iterator of map registered in the Object Pool(Object name and Object Holder)
typedef std::map<AQLString, AQLObjectHolder>::iterator	   EntityIter;

// constant iterator of map registered in the Object Pool(Object name and Object Holder)
typedef std::map<AQLString, AQLObjectHolder>::const_iterator EntityConstIter; 

class AQLDataInstance;


/*! 
    @brief Class to register and master the referenced Object by name.

	not hold ownership of the referenced Object, and this class generete only one instance for the application.
*/
class AQLCoreReferencePool
{
friend class AQLObjectPool;
public:
    // return the number of registered Entities
    /*!
        @return the number of registered Entities
    */
	int                 getSize() const {return mReferencee.size();}

    // get the Object Holder of the selected name from the Object registered in the Reference Pool
	AQLObjectHolder&		getReference(const AQLString& name);

    // return an iterator pointing to the top of the Object Holder map belonging to the ReferencePool
    /*!
        @return an iterator pointing to the top of the Object Holder map
    */
	EntityIter			begin() {return mReferencee.begin();} 
    // return an iterator pointing to the end of the Object Holder map belonging to the ReferencePool
    /*!
        @return an iterator pointing to the end of the Object Holder map
    */
	EntityIter			end() {return mReferencee.end();}
    // return a constant iterator pointing to the top of the Object Holder map belonging to the ReferencePool
    /*!
        @return a constant iterator pointing to the top of the Object Holder map
    */
	EntityConstIter     begin(void) const {return mReferencee.begin();}
    // return a constant iterator pointing to the end of the Object Holder map belonging to the ReferencePool
    /*!
        @return a constant iterator pointing to the end of the Object Holder map
    */
	EntityConstIter     end(void) const {return mReferencee.end();}

    // set the referenced Object from the Reference Pool
	AQLObjectHolder&		setReference(const AQLString& name);

	// delete the referenced Object from the Reference Pool
	void				delReference(const AQLString& name);

	// delete the referenced Object from the Reference Pool
	void				delReferenceNoCheck(const AQLString& name);

	// resolve unresolved references as possible
	void				completeDependency(void);

private:
	// clear the Reference information
	void				clear();

	EntityPool			mReferencee;		// Object data of Reference Pool
	AQLDataInstance*		mpDataInstance;      // AQLDataInstance object this Reference Pool belongs to

	//  impossible to be generated by its own(used as member variable of AQLObjectPool)

    // default constructor
	AQLCoreReferencePool();

    // destructor
	~AQLCoreReferencePool();

	// copy has no meaning because it is impsseble to generate the object alone, however let only define the funtion
    // assignment operator(return the reference to itself)
	AQLCoreReferencePool& operator=(const AQLCoreReferencePool& e) {return copy(e);}

    // not copy the selected Reference bool, but return the reference to itself
	AQLCoreReferencePool& copy(const AQLCoreReferencePool& rp);

    // set the AQLDataInstance object
	void setDataInstance(AQLDataInstance* dataInstance);
	
	AQLObjectHolder NULL_OBJECT_HOLDER;
};

