#pragma once

#ifdef __GNUG__
#pragma interface
#endif

#include "LACoreAppError.h"
#include "LAString.h"
#include "LAObjectHolder.h"

// map of Object registered in the Object Pool(Object name and Object Holder)
typedef std::map<LAString, LAObjectHolder>				   EntityPool;

// iterator of map registered in the Object Pool(Object name and Object Holder)
typedef std::map<LAString, LAObjectHolder>::iterator	   EntityIter;

// constant iterator of map registered in the Object Pool(Object name and Object Holder)
typedef std::map<LAString, LAObjectHolder>::const_iterator EntityConstIter; 

class LADataInstance;


/*! 
    @brief Class to register and master the referenced Object by name.

	not hold ownership of the referenced Object, and this class generete only one instance for the application.
*/
class LACoreReferencePool
{
friend class LAObjectPool;
public:
	//  QUERY
    // return the number of registered Entities
    /*!
        @return the number of registered Entities
    */
	int                 getSize() const {return mReferencee.size();}

    // get the Object Holder of the selected name from the Object registered in the Reference Pool
	LAObjectHolder&		getReference(const LAString& name);

    // return an iterator pointing to the top of the Object Holder map belonging to the ReferencePool
    /*!
        @return an iterator pointing to the top of the Object Holder map
    */
	EntityIter			begin() {return mReferencee.begin();} 
    // return an iterator pointing to the end of the Object Holder map belonging to the ReferencePool
    /*!
        @return an iterator pointing to the end of the Object Holder map
    */
	EntityIter			end() {return mReferencee.end();}
    // return a constant iterator pointing to the top of the Object Holder map belonging to the ReferencePool
    /*!
        @return a constant iterator pointing to the top of the Object Holder map
    */
	EntityConstIter     begin(void) const {return mReferencee.begin();}
    // return a constant iterator pointing to the end of the Object Holder map belonging to the ReferencePool
    /*!
        @return a constant iterator pointing to the end of the Object Holder map
    */
	EntityConstIter     end(void) const {return mReferencee.end();}

//  OPERATION
    // set the referenced Object from the Reference Pool
	LAObjectHolder&		setReference(const LAString& name);

	// delete the referenced Object from the Reference Pool
	void				delReference(const LAString& name);

	// delete the referenced Object from the Reference Pool
	void				delReferenceNoCheck(const LAString& name);

	// resolve unresolved references as possible
	void				completeDependency(void);

private:
	// clear the Reference information
	void				clear();

	EntityPool			mReferencee;		// Object data of Reference Pool
	LADataInstance*		mpDataInstance;      // LADataInstance object this Reference Pool belongs to

	//  impossible to be generated by its own(used as member variable of LAObjectPool)

    // default constructor
	LACoreReferencePool();

    // destructor
	~LACoreReferencePool();

	// copy has no meaning because it is impsseble to generate the object alone, however let only define the funtion
    // assignment operator(return the reference to itself)
	LACoreReferencePool& operator=(const LACoreReferencePool& e) {return copy(e);}

    // not copy the selected Reference bool, but return the reference to itself
	LACoreReferencePool& copy(const LACoreReferencePool& rp);

    // set the LADataInstance object
	void setDataInstance(LADataInstance* dataInstance);
	
	LAObjectHolder NULL_OBJECT_HOLDER;
};

