/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecInteger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecInteger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecInteger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecInteger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecInteger() {
    this(SwigMLIBJNI.new_VecInteger__SWIG_0(), true);
  }

  public VecInteger(long n) {
    this(SwigMLIBJNI.new_VecInteger__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecInteger_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecInteger_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecInteger_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecInteger_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecInteger_clear(swigCPtr, this);
  }

  public void add(int x) {
    SwigMLIBJNI.VecInteger_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return SwigMLIBJNI.VecInteger_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    SwigMLIBJNI.VecInteger_set(swigCPtr, this, i, val);
  }

}
