/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecVecInteger {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecInteger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecInteger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecVecInteger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecInteger() {
    this(SwigMLIBJNI.new_VecVecInteger__SWIG_0(), true);
  }

  public VecVecInteger(long n) {
    this(SwigMLIBJNI.new_VecVecInteger__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecVecInteger_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecVecInteger_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecVecInteger_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecVecInteger_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecVecInteger_clear(swigCPtr, this);
  }

  public void add(VecInteger x) {
    SwigMLIBJNI.VecVecInteger_add(swigCPtr, this, VecInteger.getCPtr(x), x);
  }

  public VecInteger get(int i) {
    return new VecInteger(SwigMLIBJNI.VecVecInteger_get(swigCPtr, this, i), false);
  }

  public void set(int i, VecInteger val) {
    SwigMLIBJNI.VecVecInteger_set(swigCPtr, this, i, VecInteger.getCPtr(val), val);
  }

}
