/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecVecDouble {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecVecDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecDouble() {
    this(SwigMLIBJNI.new_VecVecDouble__SWIG_0(), true);
  }

  public VecVecDouble(long n) {
    this(SwigMLIBJNI.new_VecVecDouble__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecVecDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecVecDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecVecDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecVecDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecVecDouble_clear(swigCPtr, this);
  }

  public void add(VecDouble x) {
    SwigMLIBJNI.VecVecDouble_add(swigCPtr, this, VecDouble.getCPtr(x), x);
  }

  public VecDouble get(int i) {
    return new VecDouble(SwigMLIBJNI.VecVecDouble_get(swigCPtr, this, i), false);
  }

  public void set(int i, VecDouble val) {
    SwigMLIBJNI.VecVecDouble_set(swigCPtr, this, i, VecDouble.getCPtr(val), val);
  }

}
