//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PolynomialCalibrationResults : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PolynomialCalibrationResults(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PolynomialCalibrationResults obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PolynomialCalibrationResults() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MLIB_CLIENT_APIPINVOKE.delete_PolynomialCalibrationResults(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_DoubleVector coefficients_ {
    set {
      MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_coefficients__set(swigCPtr, SWIGTYPE_p_DoubleVector.getCPtr(value));
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_DoubleVector ret = new SWIGTYPE_p_DoubleVector(MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_coefficients__get(swigCPtr), true);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double leastSquaresError_ {
    set {
      MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_leastSquaresError__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_leastSquaresError__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double iterations_ {
    set {
      MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_iterations__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.PolynomialCalibrationResults_iterations__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PolynomialCalibrationResults() : this(MLIB_CLIENT_APIPINVOKE.new_PolynomialCalibrationResults(), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

}
