@echo off

REM EXCEL_VERSIONS
set EXCEL_OFFICE2016_X64="C:\Program Files\Microsoft Office\Office16\EXCEL.exe"
set EXCEL_OFFICE2016_X86="C:\Program Files (x86)\Microsoft Office\Office16\EXCEL.exe"
set EXCEL_OFFICE2010_X64="C:\Program Files\Microsoft Office\Office14\EXCEL.exe"
set EXCEL_OFFICE2010_X86="C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.exe"

REM SET THE EXCEL VERSION
if EXIST %EXCEL_OFFICE2016_X64% (
	set EXCEL=%EXCEL_OFFICE2016_X64%
	set IS_64_BIT=TRUE
	set ARCHITECTURE=PRODUCTION_X64
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2016_X86% (
	set EXCEL=%EXCEL_OFFICE2016_X86%
	set IS_64_BIT=FALSE
	set ARCHITECTURE=PRODUCTION
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2010_X64% (
	set EXCEL=%EXCEL_OFFICE2010_X64%
	set IS_64_BIT=TRUE
	set ARCHITECTURE=PRODUCTION_X64
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2010_X86% (
	set EXCEL=%EXCEL_OFFICE2010_X86%
	set IS_64_BIT=FALSE
	set ARCHITECTURE=PRODUCTION
	GOTO :EXCEL_SET
)

:EXCEL_NOT_SET
echo .
echo Failed to Detect Excel Version
echo .
EXIT

:EXCEL_SET

echo .
echo EXCEL Configuration
echo -------------------
echo Excel Version: %EXCEL%
echo Using 64 Bit Excel: %IS_64_BIT%
echo .

REM EXCEL ADDIN & PRICING TOOLKIT FOLDERS
set EXCEL_ADDIN=\\tkfsfsgbl01.topflagship.mizuho-sc.com\shrgbl\LN\ln_rstac\Fixed Income Trading\MLIB_Excel_Addin\MLIBQ_ADDIN
set PRICING_TOOLKIT=\\tkfsfsgbl01.topflagship.mizuho-sc.com\shrgbl\LN\ln_rstac\Fixed Income Trading\PricingTools
set UTILITIES=\\tkfsfsgbl01.topflagship.mizuho-sc.com\shrgbl\LN\ln_rstac\Fixed Income Trading\Utilities

REM MLIB VERSION CONTROL FOR UAT
set MLIB_CURRENT="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-03.1\MLIBQ_ADDIN.xll"
set MLIB_BACKUP="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"

REM MLIB VERSION CONTROL FOR TRADING DESKS
set MLIB_AUD_BOND_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_EUR_SWAPS_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_USD_SWAPS_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_JGB_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"

REM MLIB TOOLBAR VERSION CONTROL
set MLIB_TOOLBAR="%UTILITIES%\Toolbar\ExcelToolbar.xlam"

REM CURVE CALIBRATION TOOL
SET CURVE_BUILDER="%PRICING_TOOLKIT%\CurveCalibrationTool\CurveCalibrationTool-12.9.xlsb"

REM SWAP PRICER VERSION CONTROL
set MLIB_SWAP_PRICER="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-08.1\MLIBQ_ADDIN.xll"
set SWAP_PRICER="%PRICING_TOOLKIT%\SwapsPricer\SwapsPricerV2.2.xlsm"

REM BOND PRICER VERSION CONTROL
set BOND_PRICER="%PRICING_TOOLKIT%\BondPricer\BondPricer-0.2.xlsm"

REM FX PRICER VERSION CONTROL
set FX_PRICER="set URIDASHI_PRICER="%PRICING_TOOLKIT%\FXPricer-0.1.xlsx"

REM XCCY_PRICER VERSION CONTROL
set MLIB_XCCY_DESK_PROD="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.1\MLIBQ_ADDIN.xll"
set XCCY_PRICER_PROD="%PRICING_TOOLKIT%\XccyPricer\XccyPricerV7.4.xlsb"

set MLIB_XCCY_DESK_UAT="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.1\MLIBQ_ADDIN.xll"
set XCCY_PRICER_UAT="%PRICING_TOOLKIT%\XccyPricer\XccyPricerV7.4.xlsb"
