AUSTRALIAN_GOVT_TYPE23_CLEAN.JSON
AUSTRALIAN_GOVT_TYPE23_DIRTY.JSON
FRENCH_OAT_TYPE89.JSON
GERMAN_BUND_TYPE60.JSON
EUR_FLOATER_TYPE21.JSON
EUR_FLOATER_TYPE21_ACTACT.JSON
EUR_FLOATER_TYPE21_ACTACT_UNADJUSTED.JSON
EUR_FLOATER_TYPE21_UNADJUSTED.JSON
USD_FLOATER_TYPE21.JSON
GBP_FLOATER_TYPE21.JSON
GBP_FLOATER_TYPE21_UNADJUSTED.JSON
ITALIAN_BTPS_TYPE523.JSON
ITALIAN_BTPS_TYPE527.JSON
ITALIAN_BTPS_TYPE529.JSON
JAPAN_JGB_TYPE51.JSON
US_TREASURY_TYPE1.JSON
AUD_FUTURE_3Y_NOTIONAL_BOND.JSON
AUD_FUTURE_10Y_NOTIONAL_BOND.JSON
UK_GILT_TYPE26.JSON
SPANISH_GOVT_TYPE1029.JSON
SPANISH_TBILL_TYPE730.JSON