@echo off

REM MLIBQ_LOCATION SETTINGS
REM ======================================
IF DEFINED MLIBQ_LOCATION (
   REM MLIBQ_LOACATION HAS BEEN ALREADY DEFINED
) ELSE (
   SET MLIBQ_LOCATION=UK
   REM SET MLIBQ_LOCATION=JP
   REM SET MLIBQ_LOCATION=US
)
REM GLOBAL SETTING
REM ======================================
SET BATCH_FILE_FOLDER=%MLIBQ%\resource\utilities\BatchFiles\_GIT

REM LOAD REGIONAL FOLDER SETTINGS
IF /I %MLIBQ_LOCATION%==UK CALL %BATCH_FILE_FOLDER%\FolderControl\MLIBQ_FOLDERS_UK.bat
IF /I %MLIBQ_LOCATION%==JP CALL %BATCH_FILE_FOLDER%\FolderControl\MLIBQ_FOLDERS_JP.bat
IF /I %MLIBQ_LOCATION%==US CALL %BATCH_FILE_FOLDER%\FolderControl\MLIBQ_FOLDERS_US.bat

REM SWITCH TO CONTROL NESTED FOLDER CALLS
SET FOLDERS_UPDATED=TRUE