/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecDouble {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecDouble() {
    this(SwigMLIBJNI.new_VecDouble__SWIG_0(), true);
  }

  public VecDouble(long n) {
    this(SwigMLIBJNI.new_VecDouble__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecDouble_clear(swigCPtr, this);
  }

  public void add(double x) {
    SwigMLIBJNI.VecDouble_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return SwigMLIBJNI.VecDouble_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    SwigMLIBJNI.VecDouble_set(swigCPtr, this, i, val);
  }

}
