/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecString() {
    this(SwigMLIBJNI.new_VecString__SWIG_0(), true);
  }

  public VecString(long n) {
    this(SwigMLIBJNI.new_VecString__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecString_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecString_clear(swigCPtr, this);
  }

  public void add(String x) {
    SwigMLIBJNI.VecString_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return SwigMLIBJNI.VecString_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    SwigMLIBJNI.VecString_set(swigCPtr, this, i, val);
  }

}
