/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mizuho.mlib;

public class VecVecString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VecVecString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VecVecString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigMLIBJNI.delete_VecVecString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VecVecString() {
    this(SwigMLIBJNI.new_VecVecString__SWIG_0(), true);
  }

  public VecVecString(long n) {
    this(SwigMLIBJNI.new_VecVecString__SWIG_1(n), true);
  }

  public long size() {
    return SwigMLIBJNI.VecVecString_size(swigCPtr, this);
  }

  public long capacity() {
    return SwigMLIBJNI.VecVecString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SwigMLIBJNI.VecVecString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SwigMLIBJNI.VecVecString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigMLIBJNI.VecVecString_clear(swigCPtr, this);
  }

  public void add(VecString x) {
    SwigMLIBJNI.VecVecString_add(swigCPtr, this, VecString.getCPtr(x), x);
  }

  public VecString get(int i) {
    return new VecString(SwigMLIBJNI.VecVecString_get(swigCPtr, this, i), false);
  }

  public void set(int i, VecString val) {
    SwigMLIBJNI.VecVecString_set(swigCPtr, this, i, VecString.getCPtr(val), val);
  }

}
