AUSTRALIAN_GOVT_TYPE23_CLEAN.JSON
AUSTRALIAN_GOVT_TYPE23_DIRTY.JSON
FRENCH_OAT_TYPE89.JSON
GERMAN_BUND_TYPE60.JSON
ITALIAN_BTPS_TYPE523.JSON
ITALIAN_BTPS_TYPE527.JSON
ITALIAN_BTPS_TYPE529.JSON
JAPAN_JGB_TYPE51.JSON
US_TREASURY_TYPE1.JSON