//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MLIB_CLIENT_API {
  public static int getInt() {
    int ret = MLIB_CLIENT_APIPINVOKE.getInt();
    return ret;
  }

  public static double getDouble() {
    double ret = MLIB_CLIENT_APIPINVOKE.getDouble();
    return ret;
  }

  public static char getChar() {
    char ret = MLIB_CLIENT_APIPINVOKE.getChar();
    return ret;
  }

  public static bool getBool() {
    bool ret = MLIB_CLIENT_APIPINVOKE.getBool();
    return ret;
  }

  public static string getConstChar() {
    string ret = MLIB_CLIENT_APIPINVOKE.getConstChar();
    return ret;
  }

  public static string getStdString() {
    string ret = MLIB_CLIENT_APIPINVOKE.getStdString();
    return ret;
  }

  public static VecInteger getVectorOfInt() {
    VecInteger ret = new VecInteger(MLIB_CLIENT_APIPINVOKE.getVectorOfInt(), true);
    return ret;
  }

  public static VecVecInteger getVectorOfVectorOfInt() {
    VecVecInteger ret = new VecVecInteger(MLIB_CLIENT_APIPINVOKE.getVectorOfVectorOfInt(), true);
    return ret;
  }

  public static VecDouble getVectorOfDouble() {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.getVectorOfDouble(), true);
    return ret;
  }

  public static VecVecDouble getVectorOfVectorOfDouble() {
    VecVecDouble ret = new VecVecDouble(MLIB_CLIENT_APIPINVOKE.getVectorOfVectorOfDouble(), true);
    return ret;
  }

  public static VecString getVectorOfString() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.getVectorOfString(), true);
    return ret;
  }

  public static VecVecString getVectorOfVectorOfString() {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.getVectorOfVectorOfString(), true);
    return ret;
  }

  public static string testVectorOfVectorOfDoubles(VecVecString arg0) {
    string ret = MLIB_CLIENT_APIPINVOKE.testVectorOfVectorOfDoubles(VecVecString.getCPtr(arg0));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int throwAnException() {
    int ret = MLIB_CLIENT_APIPINVOKE.throwAnException();
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int throwAnIllegalArgumentException() {
    int ret = MLIB_CLIENT_APIPINVOKE.throwAnIllegalArgumentException();
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double sumUp(SWIGTYPE_p_double inputArray, int sizeOfArray) {
    double ret = MLIB_CLIENT_APIPINVOKE.sumUp__SWIG_0(SWIGTYPE_p_double.getCPtr(inputArray), sizeOfArray);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double sumUp(VecDouble inputArray) {
    double ret = MLIB_CLIENT_APIPINVOKE.sumUp__SWIG_1(VecDouble.getCPtr(inputArray));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double doSomeFormula(double z) {
    double ret = MLIB_CLIENT_APIPINVOKE.doSomeFormula(z);
    return ret;
  }

  public static string setUpMLIB(string irPropsFullFilePath, string calendarFullFilePath) {
    string ret = MLIB_CLIENT_APIPINVOKE.setUpMLIB(irPropsFullFilePath, calendarFullFilePath);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string tearDownMLIB() {
    string ret = MLIB_CLIENT_APIPINVOKE.tearDownMLIB();
    return ret;
  }

  public static string mirSetUpOISCurve(string CurveID, string MarketName, VecVecString GeneralProps, VecVecString OISConv, VecVecString OISRates, string CurveNames, VecVecString OISHistRates, VecVecString LOBasisRates, VecVecString SwapConv, VecVecString SwapRates, VecVecString LOBasisConv) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetUpOISCurve(CurveID, MarketName, VecVecString.getCPtr(GeneralProps), VecVecString.getCPtr(OISConv), VecVecString.getCPtr(OISRates), CurveNames, VecVecString.getCPtr(OISHistRates), VecVecString.getCPtr(LOBasisRates), VecVecString.getCPtr(SwapConv), VecVecString.getCPtr(SwapRates), VecVecString.getCPtr(LOBasisConv));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirSetUpSwapCurve(string CurveID, string MarketName, VecVecString YldData, VecVecString MData, VecVecString LData, VecVecString LGrid, VecVecString SData, VecVecString SGrid, VecVecString FRAData, VecVecString FRA3MGrid, VecVecString FRA6MGrid, VecVecString FData, VecVecString FGrid, VecVecString AdjData, VecVecString AdjGrid, string CurveNames, string CurveName_DF2) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetUpSwapCurve(CurveID, MarketName, VecVecString.getCPtr(YldData), VecVecString.getCPtr(MData), VecVecString.getCPtr(LData), VecVecString.getCPtr(LGrid), VecVecString.getCPtr(SData), VecVecString.getCPtr(SGrid), VecVecString.getCPtr(FRAData), VecVecString.getCPtr(FRA3MGrid), VecVecString.getCPtr(FRA6MGrid), VecVecString.getCPtr(FData), VecVecString.getCPtr(FGrid), VecVecString.getCPtr(AdjData), VecVecString.getCPtr(AdjGrid), CurveNames, CurveName_DF2);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirSetUpBasisSwapCurve(string CurveID, string MarketName, VecVecString GeneralProps, VecVecString BasisConv, VecVecString BasisRates, string CurveNames, VecVecString FwdConv, VecVecString FwdFXs, VecVecString SpotFXs) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetUpBasisSwapCurve__SWIG_0(CurveID, MarketName, VecVecString.getCPtr(GeneralProps), VecVecString.getCPtr(BasisConv), VecVecString.getCPtr(BasisRates), CurveNames, VecVecString.getCPtr(FwdConv), VecVecString.getCPtr(FwdFXs), VecVecString.getCPtr(SpotFXs));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirSetUpBasisSwapCurve(string CurveID, string MarketName, VecVecString GeneralProps, VecVecString BasisConv, VecVecString BasisRates, string CurveNames, VecVecString FwdConv, VecVecString FwdFXs, VecVecString SpotFXs, VecVecString FRAConv, VecVecString FRARates) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetUpBasisSwapCurve__SWIG_1(CurveID, MarketName, VecVecString.getCPtr(GeneralProps), VecVecString.getCPtr(BasisConv), VecVecString.getCPtr(BasisRates), CurveNames, VecVecString.getCPtr(FwdConv), VecVecString.getCPtr(FwdFXs), VecVecString.getCPtr(SpotFXs), VecVecString.getCPtr(FRAConv), VecVecString.getCPtr(FRARates));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetDateFromTerm(string FromDate, double TermY, string DayCount, bool IncludeLast) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetDateFromTerm(FromDate, TermY, DayCount, IncludeLast);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetDate(string BaseDate, string Term, string SlidingRule, string Calendar, string RollConvention) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetDate__SWIG_0(BaseDate, Term, SlidingRule, Calendar, RollConvention);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString mirGetDate(VecString BaseDates, string Term, string SlidingRule, string Calendar, string RollConvention) {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.mirGetDate__SWIG_1(VecString.getCPtr(BaseDates), Term, SlidingRule, Calendar, RollConvention), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetIMMDate1(int Year, int Month, string Calendar, string SlidingRule) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetIMMDate1(Year, Month, Calendar, SlidingRule);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetIMMDate2(int Year, int Number, string Calendar, string SlidingRule) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetIMMDate2(Year, Number, Calendar, SlidingRule);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetIMMDate3(string BaseDate, int Number, string Calendar, string SlidingRule) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetIMMDate3(BaseDate, Number, Calendar, SlidingRule);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetParRate4(string EffDt, string Mat, string CrvID, string XFreq, string XDayCt, string XRollCnv, string XCal, string XFirstStub, string XLastStub, string XRollDay, string XPayLag, string XStub, string TFreq, string TDayCt, string TRollCnv, string TCal, string TFirstStub, string TLastStub, string TRollDay, string TFixLag, double TFirstFix, double TLastFix, string TPayLag, string TStub, string Interp, string Fcrv, string Dcrv, bool InterpFwds, bool EomRoll, double TSpd, bool UseFwdData) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetParRate4(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetParRate5(string EffDt, string Mat, string CrvID, string XFreq, string XDayCt, string XRollCnv, string XCal, string XFirstStub, string XLastStub, string XRollDay, string XPayLag, string XStub, string TFreq, string TDayCt, string TRollCnv, string TCal, string TFirstStub, string TLastStub, string TRollDay, string TFixLag, double TFirstFix, double TLastFix, string TPayLag, string TStub, string Interp, string Fcrv, string Dcrv, bool InterpFwds, bool EomRoll, double TSpd, bool UseFwdData, string TFixCalc) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetParRate5(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData, TFixCalc);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetParRate3(string fromDate, string toDate, string curveId, string frequency, string dayCount, string slidingRule, string calendar, string interpolation, string firstOddDate, string lastOddDate, string paymentDay, string foreCurveName, string dfCurveName, bool interpFwds, bool eomRoll) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetParRate3(fromDate, toDate, curveId, frequency, dayCount, slidingRule, calendar, interpolation, firstOddDate, lastOddDate, paymentDay, foreCurveName, dfCurveName, interpFwds, eomRoll);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirOISParRate(string EffDt, string Mat, string CrvID, string XFreq, string XDayCt, string XRollCnv, string XCal, string XFirstStub, string XLastStub, string XRollDay, string XPayLag, string XStub, string TFreq, string TDayCt, string TRollCnv, string TCal, string TFirstStub, string TLastStub, string TRollDay, string TFixLag, double TFirstFix, double TLastFix, string TPayLag, string TStub, string Interp, string Fcrv, string Dcrv, bool EomRoll, double TSpd, string CompMethod) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirOISParRate(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, TSpd, CompMethod);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirOISSwapPV(double notional, string PayRec, string EffDt, string Mat, string CrvID, double XRt, string XFreq, string XDayCt, string XRollCnv, string XCal, string XFirstStub, string XLastStub, string XRollDay, string XPayLag, string XStub, double TSpd, string TFreq, string TDayCt, string TRollCnv, string TCal, string TFirstStub, string TLastStub, string TRollDay, string TFixLag, double TFirstFix, double TLastFix, string TPayLag, string TStub, string Interp, string Fcrv, string Dcrv, bool EomRoll, string CompMethod) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirOISSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, CompMethod);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirSwapPV(double notional, string PayRec, string EffDt, string Mat, string CrvID, double XRt, string XFreq, string XDayCt, string XRollCnv, string XCal, string XFirstStub, string XLastStub, string XRollDay, string XPayLag, string XStub, double TSpd, string TFreq, string TDayCt, string TRollCnv, string TCal, string TFirstStub, string TLastStub, string TRollDay, string TFixLag, double TFirstFix, double TLastFix, string TPayLag, string TStub, string Interp, string Fcrv, string Dcrv, bool InterpFwds, bool EomRoll) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetDF1(double Term, string CurveID, string DayCount, string Interpolation, bool IsBasisFlag, string CurveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetDF1__SWIG_0(Term, CurveID, DayCount, Interpolation, IsBasisFlag, CurveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetDF1(VecDouble Terms, string CurveID, string DayCount, string Interpolation, bool IsBasisFlag, string CurveName) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetDF1__SWIG_1(VecDouble.getCPtr(Terms), CurveID, DayCount, Interpolation, IsBasisFlag, CurveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetDF2(string Term, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetDF2__SWIG_0(Term, CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetDF2(VecString Terms, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetDF2__SWIG_1(VecString.getCPtr(Terms), CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetDF3(string FromDate, string ToDate, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetDF3__SWIG_0(FromDate, ToDate, CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetDF3(string FromDate, VecString ToDates, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetDF3__SWIG_1(FromDate, VecString.getCPtr(ToDates), CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetDF4(string FromDate, double Term, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetDF4__SWIG_0(FromDate, Term, CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetDF4(VecString FromDates, VecDouble Terms, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetDF4__SWIG_1(VecString.getCPtr(FromDates), VecDouble.getCPtr(Terms), CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetDF5(string FromDate, string TermTenor, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetDF5__SWIG_0(FromDate, TermTenor, CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetDF5(VecString FromDates, string TermTenor, string CurveID, string DayCount, string SlidingRule, string Calendar, string Interpolation, bool IsBasisFlag, string CurveName) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetDF5__SWIG_1(VecString.getCPtr(FromDates), TermTenor, CurveID, DayCount, SlidingRule, Calendar, Interpolation, IsBasisFlag, CurveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecString mirGetPCAResults(string ID, int update) {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.mirGetPCAResults(ID, update), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirSetupPCA(string ID, VecVecDouble data, bool IsScale, int FactorNum) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetupPCA(ID, VecVecDouble.getCPtr(data), IsScale, FactorNum);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirInterpolation(VecDouble array1, VecDouble array2, double point, string interpolation) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirInterpolation(VecDouble.getCPtr(array1), VecDouble.getCPtr(array2), point, interpolation);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetForwardRate2(VecString fromDates, VecString toDates, string curveId, string frequency, string dayCount, string slidingRule, string calendar, string interpolation, string curveName, bool isFwdInterp, bool useFwdData) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetForwardRate2(VecString.getCPtr(fromDates), VecString.getCPtr(toDates), curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp, useFwdData), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirSetUpFwdFXConstantCurve(string CurveID, string MarketName, VecVecString GeneralProps, VecVecString FwdFXConstantConv, string CurveNames) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirSetUpFwdFXConstantCurve(CurveID, MarketName, VecVecString.getCPtr(GeneralProps), VecVecString.getCPtr(FwdFXConstantConv), CurveNames);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirSwapStubRate(string EffDt, string Mat, string Freq, string DayCt, string RollCnv, string Cal, int RollDay, string FixLag, bool EomRoll, string Interpolation, string FirstStub, string LastStub, string StubType, string CrvID, VecString CurveNames, VecString CurveTenors, VecDouble TenorCurveFixings, string UseCurveName, string ToleranceTenor, bool IsFwdInterp, bool UseFwdData) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirSwapStubRate(EffDt, Mat, Freq, DayCt, RollCnv, Cal, RollDay, FixLag, EomRoll, Interpolation, FirstStub, LastStub, StubType, CrvID, VecString.getCPtr(CurveNames), VecString.getCPtr(CurveTenors), VecDouble.getCPtr(TenorCurveFixings), UseCurveName, ToleranceTenor, IsFwdInterp, UseFwdData);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetZeroRate1(double Term, string curveId, string frequency, string dayCount, string interpolation, string curveName, bool isFwdInterp) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetZeroRate1__SWIG_0(Term, curveId, frequency, dayCount, interpolation, curveName, isFwdInterp);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetZeroRate1(VecDouble Terms, string curveId, string frequency, string dayCount, string interpolation, string curveName, bool isFwdInterp) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetZeroRate1__SWIG_1(VecDouble.getCPtr(Terms), curveId, frequency, dayCount, interpolation, curveName, isFwdInterp), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetZeroRate2(string Term, string curveId, string frequency, string dayCount, string slidingRule, string calendar, string interpolation, string curveName, bool isFwdInterp) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetZeroRate2__SWIG_0(Term, curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirGetZeroRate2(VecString Terms, string curveId, string frequency, string dayCount, string slidingRule, string calendar, string interpolation, string curveName, bool isFwdInterp) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirGetZeroRate2__SWIG_1(VecString.getCPtr(Terms), curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecDouble mirOutputCurve(string curveId, string curveName) {
    VecVecDouble ret = new VecVecDouble(MLIB_CLIENT_APIPINVOKE.mirOutputCurve(curveId, curveName), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirSwapPV01(double notional, string payRec, string effectDt, string maturity, string curveId, string xFreq, string xDayCount, string xRollCnv, string xCalendar, string xFirstStub, string xLastStub, string xRollDay, string xPayLag, string xStub, double tSpread, string tFreq, string tDayCount, string tRollCnv, string tCalendar, string tFirstStub, string tLastStub, string tRollDay, string tFixLag, double tFirstFix, double tLastFix, string tPayLag, string tStub, string interpolation, string forecastCurve, string discountCurve, bool interpFwds, bool eomRoll) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirSwapPV01(notional, payRec, effectDt, maturity, curveId, xFreq, xDayCount, xRollCnv, xCalendar, xFirstStub, xLastStub, xRollDay, xPayLag, xStub, tSpread, tFreq, tDayCount, tRollCnv, tCalendar, tFirstStub, tLastStub, tRollDay, tFixLag, tFirstFix, tLastFix, tPayLag, tStub, interpolation, forecastCurve, discountCurve, interpFwds, eomRoll);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble mirCompound3(VecString startDates, VecString endDates, string curveId, string forecastCurve, string frequency, double spread, bool isStartRoll, string rollConvention, string calendar, string slidingRule, string dayCount, string interpolation, string compoundType, string firstOddDate, string lastOddDate) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.mirCompound3__SWIG_0(VecString.getCPtr(startDates), VecString.getCPtr(endDates), curveId, forecastCurve, frequency, spread, isStartRoll, rollConvention, calendar, slidingRule, dayCount, interpolation, compoundType, firstOddDate, lastOddDate), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirCompound3(string startDate, string endDate, string curveId, string forecastCurve, string frequency, double spread, bool isStartRoll, string rollConvention, string calendar, string slidingRule, string dayCount, string interpolation, string compoundType, string firstOddDate, string lastOddDate) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirCompound3__SWIG_1(startDate, endDate, curveId, forecastCurve, frequency, spread, isStartRoll, rollConvention, calendar, slidingRule, dayCount, interpolation, compoundType, firstOddDate, lastOddDate);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetAnnuity1(string fromDate, string toDate, string curveId, string frequency, string slidingRule, string calendar, string firstOddDate, string lastOddDate, string paymentDay, string dayCount, string interpolation, string curveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetAnnuity1(fromDate, toDate, curveId, frequency, slidingRule, calendar, firstOddDate, lastOddDate, paymentDay, dayCount, interpolation, curveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetAnnuity2(string curveId, VecString dates, string dayCount, string interpolation, string curveName) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetAnnuity2(curveId, VecString.getCPtr(dates), dayCount, interpolation, curveName);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int mirGetBusinessDays(string fromDate, string toDate, string calendar) {
    int ret = MLIB_CLIENT_APIPINVOKE.mirGetBusinessDays(fromDate, toDate, calendar);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetECBStartDate(string ecbDate) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetECBStartDate(ecbDate);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetNextCBDate(string centralBankId, string baseDate, bool strictlyAfter) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetNextCBDate(centralBankId, baseDate, strictlyAfter);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirGetNextECBDate(string baseDate, bool strictlyAfter) {
    string ret = MLIB_CLIENT_APIPINVOKE.mirGetNextECBDate(baseDate, strictlyAfter);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double mirGetTerm(string fromDate, string toDate, string dayCount, bool includeLast) {
    double ret = MLIB_CLIENT_APIPINVOKE.mirGetTerm(fromDate, toDate, dayCount, includeLast);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecString mirSwapSchedule(string accrualStartDate, string accrualEndDateOrTenor, string accrualDaycount, string accrualFrequency, string accrualSlidingRule, string accrualCalendar, string paymentFrequency, string paymentSlidingRule, string paymentCalendar, string paymentLag, string fixingSlidingRule, string fixingCalendar, string fixingLag, string fixingAdvanceOrArrears, string firstStub, string lastStub, string paymentRollDay, bool showColumnHeaders) {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.mirSwapSchedule(accrualStartDate, accrualEndDateOrTenor, accrualDaycount, accrualFrequency, accrualSlidingRule, accrualCalendar, paymentFrequency, paymentSlidingRule, paymentCalendar, paymentLag, fixingSlidingRule, fixingCalendar, fixingLag, fixingAdvanceOrArrears, firstStub, lastStub, paymentRollDay, showColumnHeaders), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string mirClearEntityPool() {
    string ret = MLIB_CLIENT_APIPINVOKE.mirClearEntityPool();
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meCurveCalibrateBasis(string curveCollection, string staticDataTable, string curveIndex, VecVecString curveConv, VecVecString basisConv, VecVecString basisRates, VecVecString fxFwdConv, VecVecString fxFwdRates, VecVecString spotFxRates) {
    string ret = MLIB_CLIENT_APIPINVOKE.meCurveCalibrateBasis__SWIG_0(curveCollection, staticDataTable, curveIndex, VecVecString.getCPtr(curveConv), VecVecString.getCPtr(basisConv), VecVecString.getCPtr(basisRates), VecVecString.getCPtr(fxFwdConv), VecVecString.getCPtr(fxFwdRates), VecVecString.getCPtr(spotFxRates));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meCurveCalibrateBasis(string curveCollection, string staticDataTable, string curveIndex, VecVecString curveConv, VecVecString basisConv, VecVecString basisRates, VecVecString fxFwdConv, VecVecString fxFwdRates, VecVecString spotFxRates, VecVecString FRAConv, VecVecString FRARates) {
    string ret = MLIB_CLIENT_APIPINVOKE.meCurveCalibrateBasis__SWIG_1(curveCollection, staticDataTable, curveIndex, VecVecString.getCPtr(curveConv), VecVecString.getCPtr(basisConv), VecVecString.getCPtr(basisRates), VecVecString.getCPtr(fxFwdConv), VecVecString.getCPtr(fxFwdRates), VecVecString.getCPtr(spotFxRates), VecVecString.getCPtr(FRAConv), VecVecString.getCPtr(FRARates));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meCurveCalibrateFXForwards(string curveCollection, string staticDataTable, string curveIndex, VecVecString curveConv, VecVecString fxFwdConv) {
    string ret = MLIB_CLIENT_APIPINVOKE.meCurveCalibrateFXForwards(curveCollection, staticDataTable, curveIndex, VecVecString.getCPtr(curveConv), VecVecString.getCPtr(fxFwdConv));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meCurveCalibrateOIS(string curveCollection, string staticDataTable, string curveIndex, VecVecString curveConv, VecVecString oisConv, VecVecString oisRates, VecVecString oisHistoricalRates, VecVecString liborOisBasisConv, VecVecString liborOisBasisRates, VecVecString swapConv, VecVecString swapRates) {
    string ret = MLIB_CLIENT_APIPINVOKE.meCurveCalibrateOIS(curveCollection, staticDataTable, curveIndex, VecVecString.getCPtr(curveConv), VecVecString.getCPtr(oisConv), VecVecString.getCPtr(oisRates), VecVecString.getCPtr(oisHistoricalRates), VecVecString.getCPtr(liborOisBasisConv), VecVecString.getCPtr(liborOisBasisRates), VecVecString.getCPtr(swapConv), VecVecString.getCPtr(swapRates));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meCurveCalibrateSwap(string curveCollection, string staticDataTable, string curveIndex, VecVecString curveConv, VecVecString moneyMarketConv, VecVecString liborConv, VecVecString liborRates, VecVecString swapConv, VecVecString swapRates, VecVecString fraConv, VecVecString fra3mRates, VecVecString fra6mRates, VecVecString futureConv, VecVecString futureRates, VecVecString convexityAdjConv, VecVecString convexityAdjRates) {
    string ret = MLIB_CLIENT_APIPINVOKE.meCurveCalibrateSwap(curveCollection, staticDataTable, curveIndex, VecVecString.getCPtr(curveConv), VecVecString.getCPtr(moneyMarketConv), VecVecString.getCPtr(liborConv), VecVecString.getCPtr(liborRates), VecVecString.getCPtr(swapConv), VecVecString.getCPtr(swapRates), VecVecString.getCPtr(fraConv), VecVecString.getCPtr(fra3mRates), VecVecString.getCPtr(fra6mRates), VecVecString.getCPtr(futureConv), VecVecString.getCPtr(futureRates), VecVecString.getCPtr(convexityAdjConv), VecVecString.getCPtr(convexityAdjRates));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveCompoundRate(VecString startDates, VecString endDates, string curveCollection, string forecastCurveIndex, string frequency, double spread, string stubType, string rollDayInput, string calendar, string businessDayAdj, string dayCount, string interpolation, string compoundType, string firstStubDate, string lastStubDate) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveCompoundRate__SWIG_0(VecString.getCPtr(startDates), VecString.getCPtr(endDates), curveCollection, forecastCurveIndex, frequency, spread, stubType, rollDayInput, calendar, businessDayAdj, dayCount, interpolation, compoundType, firstStubDate, lastStubDate), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveCompoundRate(string startDate, string endDate, string curveCollection, string forecastCurveIndex, string frequency, double spread, string stubType, string rollDayInput, string calendar, string businessDayAdj, string dayCount, string interpolation, string compoundType, string firstStubDate, string lastStubDate) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveCompoundRate__SWIG_1(startDate, endDate, curveCollection, forecastCurveIndex, frequency, spread, stubType, rollDayInput, calendar, businessDayAdj, dayCount, interpolation, compoundType, firstStubDate, lastStubDate);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveDiscountFactorsFromYearFractions(double yearFraction, string dayCount, string curveCollection, string curveIndex) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsFromYearFractions__SWIG_0(yearFraction, dayCount, curveCollection, curveIndex);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveDiscountFactorsFromYearFractions(VecDouble yearFractions, string dayCount, string curveCollection, string curveIndex) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsFromYearFractions__SWIG_1(VecDouble.getCPtr(yearFractions), dayCount, curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveDiscountFactorsFromTenors(string tenor, string curveCollection, string curveIndex, string businessDayAdj, string calendar) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsFromTenors__SWIG_0(tenor, curveCollection, curveIndex, businessDayAdj, calendar);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveDiscountFactorsFromTenors(VecString tenors, string curveCollection, string curveIndex, string businessDayAdj, string calendar) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsFromTenors__SWIG_1(VecString.getCPtr(tenors), curveCollection, curveIndex, businessDayAdj, calendar), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveDiscountFactorsForwardStarting(string fromDate, string toDate, string curveCollection, string curveIndex) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStarting__SWIG_0(fromDate, toDate, curveCollection, curveIndex);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveDiscountFactorsForwardStarting(VecString fromDates, VecString toDates, string curveCollection, string curveIndex) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStarting__SWIG_1(VecString.getCPtr(fromDates), VecString.getCPtr(toDates), curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveDiscountFactorsForwardStartingFromYearFractions(string fromDate, double yearFraction, string dayCount, string curveCollection, string curveIndex) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_0(fromDate, yearFraction, dayCount, curveCollection, curveIndex);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveDiscountFactorsForwardStartingFromYearFractions(VecString fromDates, VecDouble yearFractions, string dayCount, string curveCollection, string curveIndex) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_1(VecString.getCPtr(fromDates), VecDouble.getCPtr(yearFractions), dayCount, curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveDiscountFactorsForwardStartingFromTenor(string fromDate, string tenor, string curveCollection, string curveIndex, string businessDayAdj, string calendar) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStartingFromTenor__SWIG_0(fromDate, tenor, curveCollection, curveIndex, businessDayAdj, calendar);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveDiscountFactorsForwardStartingFromTenor(VecString fromDates, string tenor, string curveCollection, string curveIndex, string businessDayAdj, string calendar) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDiscountFactorsForwardStartingFromTenor__SWIG_1(VecString.getCPtr(fromDates), tenor, curveCollection, curveIndex, businessDayAdj, calendar), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecDouble meCurveDisplay(string curveCollection, string curveIndex) {
    VecVecDouble ret = new VecVecDouble(MLIB_CLIENT_APIPINVOKE.meCurveDisplay(curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveForwardRatesFromYearFraction(VecString fromDates, double yearFraction, string curveCollection, string curveIndex, string dayCount) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveForwardRatesFromYearFraction(VecString.getCPtr(fromDates), yearFraction, curveCollection, curveIndex, dayCount), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveForwardRates(VecString fixingDates, string curveCollection, string curveIndex) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveForwardRates(VecString.getCPtr(fixingDates), curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveForwardRatesFromForwardDates(VecString fromDates, VecString toDates, string curveCollection, string curveIndex) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveForwardRatesFromForwardDates(VecString.getCPtr(fromDates), VecString.getCPtr(toDates), curveCollection, curveIndex), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveZeroRatesFromYearFractions(double yearFraction, string curveCollection, string curveIndex, string frequency, string dayCount) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveZeroRatesFromYearFractions__SWIG_0(yearFraction, curveCollection, curveIndex, frequency, dayCount);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveZeroRatesFromYearFractions(VecDouble yearFractions, string curveCollection, string curveIndex, string frequency, string dayCount) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveZeroRatesFromYearFractions__SWIG_1(VecDouble.getCPtr(yearFractions), curveCollection, curveIndex, frequency, dayCount), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meCurveZeroRatesFromTenors(string tenor, string curveCollection, string curveIndex, string frequency, string dayCount, string calendar, string businessDayAdj) {
    double ret = MLIB_CLIENT_APIPINVOKE.meCurveZeroRatesFromTenors__SWIG_0(tenor, curveCollection, curveIndex, frequency, dayCount, calendar, businessDayAdj);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecDouble meCurveZeroRatesFromTenors(VecString tenors, string curveCollection, string curveIndex, string frequency, string dayCount, string calendar, string businessDayAdj) {
    VecDouble ret = new VecDouble(MLIB_CLIENT_APIPINVOKE.meCurveZeroRatesFromTenors__SWIG_1(VecString.getCPtr(tenors), curveCollection, curveIndex, frequency, dayCount, calendar, businessDayAdj), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateFromTenor(string startDate, string tenor, string businessDayAdj, string calendar, string rollConvention) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateFromTenor__SWIG_0(startDate, tenor, businessDayAdj, calendar, rollConvention);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meDateFromTenor(VecString startDates, string tenor, string businessDayAdj, string calendar, string rollConvention) {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meDateFromTenor__SWIG_1(VecString.getCPtr(startDates), tenor, businessDayAdj, calendar, rollConvention), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateFromYearFraction(string startDate, double yearFraction, string dayCount) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateFromYearFraction(startDate, yearFraction, dayCount);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int meDateBusinessDays(string fromDate, string toDate, string calendar) {
    int ret = MLIB_CLIENT_APIPINVOKE.meDateBusinessDays(fromDate, toDate, calendar);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateCentralBank(string centralBankId, string date, bool strictlyAfter) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateCentralBank(centralBankId, date, strictlyAfter);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateECB(string date, bool strictlyAfter) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateECB(date, strictlyAfter);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateECBSwapStart(string date) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateECBSwapStart(date);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateECBSwapEnd(string date) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateECBSwapEnd(date);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateIMMFromMonth(int year, int month, string calendar, string businessDayAdj) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateIMMFromMonth(year, month, calendar, businessDayAdj);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateNthIMM(int year, int nth, string calendar, string businessDayAdj) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateNthIMM(year, nth, calendar, businessDayAdj);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meDateNthIMMFromStartDate(string startDate, int nth, string calendar, string businessDayAdj) {
    string ret = MLIB_CLIENT_APIPINVOKE.meDateNthIMMFromStartDate(startDate, nth, calendar, businessDayAdj);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductAssetSwapSpread(double bondCleanPrice, VecVecString assetSwapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductAssetSwapSpread__SWIG_0(bondCleanPrice, VecVecString.getCPtr(assetSwapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductAssetSwapSpread(double bondCleanPrice, VecVecString assetSwapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductAssetSwapSpread__SWIG_1(bondCleanPrice, VecVecString.getCPtr(assetSwapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductAssetSwapSpreadLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductAssetSwapSpreadLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductOISParRate(VecVecString oisSwapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductOISParRate__SWIG_0(VecVecString.getCPtr(oisSwapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductOISParRate(VecVecString oisSwapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductOISParRate__SWIG_1(VecVecString.getCPtr(oisSwapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductOISParRateLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductOISParRateLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductOISPV(VecVecString oisSwapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductOISPV__SWIG_0(VecVecString.getCPtr(oisSwapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductOISPV(VecVecString oisSwapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductOISPV__SWIG_1(VecVecString.getCPtr(oisSwapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductOISPVLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductOISPVLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapDV01(VecVecString swapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapDV01__SWIG_0(VecVecString.getCPtr(swapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapDV01(VecVecString swapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapDV01__SWIG_1(VecVecString.getCPtr(swapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductSwapDV01LVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductSwapDV01LVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapParRate(VecVecString swapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapParRate__SWIG_0(VecVecString.getCPtr(swapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapParRate(VecVecString swapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapParRate__SWIG_1(VecVecString.getCPtr(swapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductSwapParRateLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductSwapParRateLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapPV(VecVecString swapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapPV__SWIG_0(VecVecString.getCPtr(swapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapPV(VecVecString swapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapPV__SWIG_1(VecVecString.getCPtr(swapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString tryMeProductSwapPVLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.tryMeProductSwapPVLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapPV01(VecVecString swapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapPV01__SWIG_0(VecVecString.getCPtr(swapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapPV01(VecVecString swapLVB) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapPV01__SWIG_1(VecVecString.getCPtr(swapLVB));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductSwapPV01LVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductSwapPV01LVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecString meProductSwapSchedule(bool showColumnHeaders, VecVecString swapScheduleLVB, bool validateKeys) {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.meProductSwapSchedule__SWIG_0(showColumnHeaders, VecVecString.getCPtr(swapScheduleLVB), validateKeys), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecString meProductSwapSchedule(bool showColumnHeaders, VecVecString swapScheduleLVB) {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.meProductSwapSchedule__SWIG_1(showColumnHeaders, VecVecString.getCPtr(swapScheduleLVB)), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductSwapScheduleLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductSwapScheduleLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meProductSwapStubRate(VecString curveIndices, VecString curveTenors, VecDouble tenorCurveFixings, VecVecString swapLVB, bool validateKeys) {
    double ret = MLIB_CLIENT_APIPINVOKE.meProductSwapStubRate(VecString.getCPtr(curveIndices), VecString.getCPtr(curveTenors), VecDouble.getCPtr(tenorCurveFixings), VecVecString.getCPtr(swapLVB), validateKeys);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecString meProductSwapStubRateLVBKeys() {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.meProductSwapStubRateLVBKeys(), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double meUtilityInterpolation(VecDouble array1, VecDouble array2, double point, string interpolation) {
    double ret = MLIB_CLIENT_APIPINVOKE.meUtilityInterpolation(VecDouble.getCPtr(array1), VecDouble.getCPtr(array2), point, interpolation);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static VecVecString meUtilityPCA(string key, VecVecDouble data, bool useCorrelationMatrix, int nFactors) {
    VecVecString ret = new VecVecString(MLIB_CLIENT_APIPINVOKE.meUtilityPCA(key, VecVecDouble.getCPtr(data), useCorrelationMatrix, nFactors), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string tryMeUtilityRecord(bool enable, string folder, bool repeat, int startIndex, int maxIndex) {
    string ret = MLIB_CLIENT_APIPINVOKE.tryMeUtilityRecord(enable, folder, repeat, startIndex, maxIndex);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meUtilityClearEntityPool() {
    string ret = MLIB_CLIENT_APIPINVOKE.meUtilityClearEntityPool();
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meUtilityLoadCalendarFile(string filepath) {
    string ret = MLIB_CLIENT_APIPINVOKE.meUtilityLoadCalendarFile(filepath);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meUtilityLoadStaticData(string filepath) {
    string ret = MLIB_CLIENT_APIPINVOKE.meUtilityLoadStaticData(filepath);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string meUtilityVersion(int expiryMonth, int expiryYear) {
    string ret = MLIB_CLIENT_APIPINVOKE.meUtilityVersion(expiryMonth, expiryYear);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
