@echo off

REM Read Folder Control variables
IF NOT DEFINED FOLDERS_UPDATED CALL %~dp0..\FolderControl\MLIBQ_FOLDERS_MASTER.bat

REM FOLDER VARIABLES
REM %DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION%
REM %DEPLOYMENT_FOLDER_MLIBQ_UAT%

TITLE REFRESHING MLIB LICENCE
ECHO PLEASE ENTER THE MLIB XLL FOLDER NAME
ECHO -------------------------------------------------------------------------
ECHO Please Specify the Build Date YYYY-MM-DD and Version Number N (if any)
ECHO In the following Format : YYYY-MM-DD.N for example 2017-02-14.1
ECHO -------------------------------------------------------------------------

SET /P VERSION="Enter the MLIB XLL Folder Name : "

:SELECT_CONFIG
ECHO.
ECHO Select Configuration :
ECHO -------------------------------------------------------------------------
ECHO 1) PRODUCTION
ECHO 2) UAT
ECHO 3) PRODUCTION and UAT
ECHO -------------------------------------------------------------------------

SET /P CONFIG="Enter 1, 2 or 3 : "

:SELECT_BIT
ECHO.
ECHO Select bit architecture 32/64:
ECHO 1) 32 BIT
ECHO 2) 64 BIT

SET /P ARCH="Enter 1 or 2 : "

IF  %ARCH% == 1 GOTO :BIT_OK
IF  %ARCH% == 2 GOTO :BIT_OK
GOTO :SELECT_BIT

:BIT_OK

REM Set Folders Here
IF %ARCH% == 1 ( 
set UAT="%DEPLOYMENT_FOLDER_MLIBQ_UAT%\%VERSION%"
set PRODUCTION="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION%\%VERSION%"
)

IF %ARCH% == 2 ( 
set UAT="%DEPLOYMENT_FOLDER_MLIBQ_UAT_X64%\%VERSION%"
set PRODUCTION="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION_X64%\%VERSION%"
)

ECHO.
ECHO UAT  : %UAT%
ECHO PROD : %PRODUCTION%

REM REFRESH CORRECT CONFIG
IF %CONFIG% == 1 GOTO :REFRESH_PRODUCTION
IF %CONFIG% == 2 GOTO :REFRESH_UAT
IF %CONFIG% == 3 GOTO :REFRESH_UAT

REM ENSURE CONFIG VALID
GOTO :SELECT_CONFIG

:REFRESH_UAT
REM REFRESH THE UAT EXCEL ADDIN LICENCE IF THE FILE EXISTS
IF NOT EXIST "%UAT%" (
ECHO. 
ECHO UNABLE TO REFRESH UAT LICENCE
ECHO UAT FILE DOES NOT EXIST:
ECHO %UAT%
ECHO.
GOTO :REFRESH_PRODUCTION )

REM COPY THE UAT FOLDER AND UPDATE THE VERSION
TITLE UPDATING THE UAT VERSION %VERSION%
call %~dp0\UpdateFolderVersion.bat "%UAT%"
IF not exist "%NEW_FOLDER_PATH%" (mkdir "%NEW_FOLDER_PATH%")
xcopy /s /y "%UAT%" "%NEW_FOLDER_PATH%\"

REM RUN GODZILLA_VS_MLIB TO REGENERATE THE LICENCE KEY
TITLE REFRESHING MLIB LICENCE FOR UAT %VERSION%
CALL "%MLIBQ%\resource\utilities\BatchFiles\_GIT\GodzillaVsMLIB\GodzillaVsMLIB.exe" "%NEW_FOLDER_PATH%\MLIBQ_ADDIN.xll"

REM SKIP PRODUCTION IF ONLY UAT SELECTED
IF %CONFIG% == 2 GOTO :END_OF_FILE

:REFRESH_PRODUCTION
REM REFRESH THE PRODUCTION EXCEL ADDIN LICENCE IF THE FILE EXISTS
IF NOT EXIST "%PRODUCTION%" (
ECHO. 
ECHO UNABLE TO REFRESH PRODUCTION LICENCE
ECHO PRODUCTION FILE DOES NOT EXIST:
ECHO %PRODUCTION%
ECHO.
GOTO :END_OF_FILE )

REM COPY THE UAT FOLDER AND UPDATE THE VERSION
TITLE UPDATING THE PRODUCTION VERSION %VERSION%
call %~dp0\UpdateFolderVersion.bat "%PRODUCTION%"
IF not exist "%NEW_FOLDER_PATH%" (mkdir "%NEW_FOLDER_PATH%")
xcopy /s /y "%PRODUCTION%" "%NEW_FOLDER_PATH%\"

REM RUN GODZILLA_VS_MLIB TO REGENERATE THE LICENCE KEY
TITLE REFRESHING MLIB LICENCE FOR PRODUCTION %VERSION%
CALL "%MLIBQ%\resource\utilities\BatchFiles\_GIT\GodzillaVsMLIB\GodzillaVsMLIB.exe" "%NEW_FOLDER_PATH%\MLIBQ_ADDIN.xll"
GOTO :END_OF_FILE

:END_OF_FILE
TITLE FINISHED UPDATING XLL LICENCE(S) FROM VERSION %VERSION%
PAUSE