import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import com.mizuho.mlib.*;

public class NewJFrame extends javax.swing.JFrame {
    
    // in swing the directory has to be the current directory --- where is the issue here...
    private final String _irFullFilename = "X:\\Secure\\DIR_MLib_API\\ir.properties";
    private final String _calFullFilename = "X:\\Secure\\DIR_MLib_API\\Calendar.csv";
    
     // really better to initialize with double braces 
    private final ArrayList<Double> _doublesToPass = new ArrayList<>(Arrays.asList(2.0, 1.0, 0.5, 0.25, 0.0 , -0.25, -0.5, -1.0 , -2.0, -200.0 ));
    private final Random _randomEngine = new Random();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        initMLIB();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Run all the tests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showResult(_doublesToPass.stream().map(x -> {return Double.toString(SwigMLIB.doSomeFormula(x));}).collect(Collectors.joining(",")));
        showResult(Double.toString(SwigMLIB.doSomeFormula(_randomEngine.nextGaussian())));
        showResult(SwigMLIB.getDateFromTerm("20170115", 1.0, "Act/360", false));
        showResult(SwigMLIB.getDateFromTerm("20170115", -1.0, "Act/365", false));
        showResult(SwigMLIB.getDate("20170115", "3M", "MOD_FOLLOWING", "TGT"));
        try {
            int placeholder_int = com.mizuho.mlib.SwigMLIB.throwAnException();
        } catch(Exception ex) {
            showResult(ex.getMessage());
        } finally {
        }
        
        try {
            int placeholder_int = com.mizuho.mlib.SwigMLIB.throwAnIllegalArgumentException();
        } catch(IllegalArgumentException illArgEx) {
            showResult(illArgEx.getMessage());
        } catch(Exception ex) {
            showResult(ex.getMessage());
        } finally {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String finalizedOrNot = SwigMLIB.tearDownMLIB();
        JOptionPane.showMessageDialog(null, finalizedOrNot);
    }//GEN-LAST:event_formWindowClosing

    private void initMLIB() {
        showResult(SwigMLIB.setUpMLIB(_irFullFilename, _calFullFilename));
    }
    
    private void showResult(String toDisplay) {
        this.jTextArea1.append(toDisplay);
        this.jTextArea1.append("\n");        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
