//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class MLIB_CLIENT_APIPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="SWIGRegisterExceptionCallbacks_MLIB_CLIENT_API")]
    public static extern void SWIGRegisterExceptionCallbacks_MLIB_CLIENT_API(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_MLIB_CLIENT_API")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_MLIB_CLIENT_API(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_MLIB_CLIENT_API(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_MLIB_CLIENT_API(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(MLIB_CLIENT_APIPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(MLIB_CLIENT_APIPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="SWIGRegisterStringCallback_MLIB_CLIENT_API")]
    public static extern void SWIGRegisterStringCallback_MLIB_CLIENT_API(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_MLIB_CLIENT_API(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static MLIB_CLIENT_APIPINVOKE() {
  }


  protected class SWIGWStringHelper {

    public delegate string SWIGWStringDelegate(global::System.IntPtr message);
    static SWIGWStringDelegate wstringDelegate = new SWIGWStringDelegate(CreateWString);

    [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="SWIGRegisterWStringCallback_MLIB_CLIENT_API")]
    public static extern void SWIGRegisterWStringCallback_MLIB_CLIENT_API(SWIGWStringDelegate wstringDelegate);

    static string CreateWString([global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPWStr)]global::System.IntPtr cString) {
      return global::System.Runtime.InteropServices.Marshal.PtrToStringUni(cString);
    }

    static SWIGWStringHelper() {
      SWIGRegisterWStringCallback_MLIB_CLIENT_API(wstringDelegate);
    }
  }

  static protected SWIGWStringHelper swigWStringHelper = new SWIGWStringHelper();


  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Clear")]
  public static extern void VecInteger_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Add")]
  public static extern void VecInteger_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_size")]
  public static extern uint VecInteger_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_capacity")]
  public static extern uint VecInteger_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_reserve")]
  public static extern void VecInteger_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecInteger__SWIG_0")]
  public static extern global::System.IntPtr new_VecInteger__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecInteger__SWIG_1")]
  public static extern global::System.IntPtr new_VecInteger__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecInteger__SWIG_2")]
  public static extern global::System.IntPtr new_VecInteger__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_getitemcopy")]
  public static extern int VecInteger_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_getitem")]
  public static extern int VecInteger_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_setitem")]
  public static extern void VecInteger_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_AddRange")]
  public static extern void VecInteger_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_GetRange")]
  public static extern global::System.IntPtr VecInteger_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Insert")]
  public static extern void VecInteger_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_InsertRange")]
  public static extern void VecInteger_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_RemoveAt")]
  public static extern void VecInteger_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_RemoveRange")]
  public static extern void VecInteger_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Repeat")]
  public static extern global::System.IntPtr VecInteger_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Reverse__SWIG_0")]
  public static extern void VecInteger_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Reverse__SWIG_1")]
  public static extern void VecInteger_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_SetRange")]
  public static extern void VecInteger_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Contains")]
  public static extern bool VecInteger_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_IndexOf")]
  public static extern int VecInteger_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_LastIndexOf")]
  public static extern int VecInteger_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecInteger_Remove")]
  public static extern bool VecInteger_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecInteger")]
  public static extern void delete_VecInteger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Clear")]
  public static extern void VecVecInteger_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Add")]
  public static extern void VecVecInteger_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_size")]
  public static extern uint VecVecInteger_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_capacity")]
  public static extern uint VecVecInteger_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_reserve")]
  public static extern void VecVecInteger_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecInteger__SWIG_0")]
  public static extern global::System.IntPtr new_VecVecInteger__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecInteger__SWIG_1")]
  public static extern global::System.IntPtr new_VecVecInteger__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecInteger__SWIG_2")]
  public static extern global::System.IntPtr new_VecVecInteger__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_getitemcopy")]
  public static extern global::System.IntPtr VecVecInteger_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_getitem")]
  public static extern global::System.IntPtr VecVecInteger_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_setitem")]
  public static extern void VecVecInteger_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_AddRange")]
  public static extern void VecVecInteger_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_GetRange")]
  public static extern global::System.IntPtr VecVecInteger_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Insert")]
  public static extern void VecVecInteger_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_InsertRange")]
  public static extern void VecVecInteger_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_RemoveAt")]
  public static extern void VecVecInteger_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_RemoveRange")]
  public static extern void VecVecInteger_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Repeat")]
  public static extern global::System.IntPtr VecVecInteger_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Reverse__SWIG_0")]
  public static extern void VecVecInteger_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_Reverse__SWIG_1")]
  public static extern void VecVecInteger_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecInteger_SetRange")]
  public static extern void VecVecInteger_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecVecInteger")]
  public static extern void delete_VecVecInteger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Clear")]
  public static extern void VecDouble_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Add")]
  public static extern void VecDouble_Add(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_size")]
  public static extern uint VecDouble_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_capacity")]
  public static extern uint VecDouble_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_reserve")]
  public static extern void VecDouble_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecDouble__SWIG_0")]
  public static extern global::System.IntPtr new_VecDouble__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecDouble__SWIG_1")]
  public static extern global::System.IntPtr new_VecDouble__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecDouble__SWIG_2")]
  public static extern global::System.IntPtr new_VecDouble__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_getitemcopy")]
  public static extern double VecDouble_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_getitem")]
  public static extern double VecDouble_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_setitem")]
  public static extern void VecDouble_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_AddRange")]
  public static extern void VecDouble_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_GetRange")]
  public static extern global::System.IntPtr VecDouble_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Insert")]
  public static extern void VecDouble_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_InsertRange")]
  public static extern void VecDouble_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_RemoveAt")]
  public static extern void VecDouble_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_RemoveRange")]
  public static extern void VecDouble_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Repeat")]
  public static extern global::System.IntPtr VecDouble_Repeat(double jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Reverse__SWIG_0")]
  public static extern void VecDouble_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Reverse__SWIG_1")]
  public static extern void VecDouble_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_SetRange")]
  public static extern void VecDouble_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Contains")]
  public static extern bool VecDouble_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_IndexOf")]
  public static extern int VecDouble_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_LastIndexOf")]
  public static extern int VecDouble_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecDouble_Remove")]
  public static extern bool VecDouble_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecDouble")]
  public static extern void delete_VecDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Clear")]
  public static extern void VecVecDouble_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Add")]
  public static extern void VecVecDouble_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_size")]
  public static extern uint VecVecDouble_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_capacity")]
  public static extern uint VecVecDouble_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_reserve")]
  public static extern void VecVecDouble_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecDouble__SWIG_0")]
  public static extern global::System.IntPtr new_VecVecDouble__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecDouble__SWIG_1")]
  public static extern global::System.IntPtr new_VecVecDouble__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecDouble__SWIG_2")]
  public static extern global::System.IntPtr new_VecVecDouble__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_getitemcopy")]
  public static extern global::System.IntPtr VecVecDouble_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_getitem")]
  public static extern global::System.IntPtr VecVecDouble_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_setitem")]
  public static extern void VecVecDouble_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_AddRange")]
  public static extern void VecVecDouble_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_GetRange")]
  public static extern global::System.IntPtr VecVecDouble_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Insert")]
  public static extern void VecVecDouble_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_InsertRange")]
  public static extern void VecVecDouble_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_RemoveAt")]
  public static extern void VecVecDouble_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_RemoveRange")]
  public static extern void VecVecDouble_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Repeat")]
  public static extern global::System.IntPtr VecVecDouble_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Reverse__SWIG_0")]
  public static extern void VecVecDouble_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_Reverse__SWIG_1")]
  public static extern void VecVecDouble_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecDouble_SetRange")]
  public static extern void VecVecDouble_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecVecDouble")]
  public static extern void delete_VecVecDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Clear")]
  public static extern void VecString_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Add")]
  public static extern void VecString_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_size")]
  public static extern uint VecString_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_capacity")]
  public static extern uint VecString_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_reserve")]
  public static extern void VecString_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecString__SWIG_0")]
  public static extern global::System.IntPtr new_VecString__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecString__SWIG_1")]
  public static extern global::System.IntPtr new_VecString__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecString__SWIG_2")]
  public static extern global::System.IntPtr new_VecString__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_getitemcopy")]
  public static extern string VecString_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_getitem")]
  public static extern string VecString_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_setitem")]
  public static extern void VecString_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_AddRange")]
  public static extern void VecString_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_GetRange")]
  public static extern global::System.IntPtr VecString_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Insert")]
  public static extern void VecString_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_InsertRange")]
  public static extern void VecString_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_RemoveAt")]
  public static extern void VecString_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_RemoveRange")]
  public static extern void VecString_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Repeat")]
  public static extern global::System.IntPtr VecString_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Reverse__SWIG_0")]
  public static extern void VecString_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Reverse__SWIG_1")]
  public static extern void VecString_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_SetRange")]
  public static extern void VecString_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Contains")]
  public static extern bool VecString_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_IndexOf")]
  public static extern int VecString_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_LastIndexOf")]
  public static extern int VecString_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecString_Remove")]
  public static extern bool VecString_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecString")]
  public static extern void delete_VecString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Clear")]
  public static extern void VecVecString_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Add")]
  public static extern void VecVecString_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_size")]
  public static extern uint VecVecString_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_capacity")]
  public static extern uint VecVecString_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_reserve")]
  public static extern void VecVecString_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecString__SWIG_0")]
  public static extern global::System.IntPtr new_VecVecString__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecString__SWIG_1")]
  public static extern global::System.IntPtr new_VecVecString__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_new_VecVecString__SWIG_2")]
  public static extern global::System.IntPtr new_VecVecString__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_getitemcopy")]
  public static extern global::System.IntPtr VecVecString_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_getitem")]
  public static extern global::System.IntPtr VecVecString_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_setitem")]
  public static extern void VecVecString_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_AddRange")]
  public static extern void VecVecString_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_GetRange")]
  public static extern global::System.IntPtr VecVecString_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Insert")]
  public static extern void VecVecString_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_InsertRange")]
  public static extern void VecVecString_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_RemoveAt")]
  public static extern void VecVecString_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_RemoveRange")]
  public static extern void VecVecString_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Repeat")]
  public static extern global::System.IntPtr VecVecString_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Reverse__SWIG_0")]
  public static extern void VecVecString_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_Reverse__SWIG_1")]
  public static extern void VecVecString_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_VecVecString_SetRange")]
  public static extern void VecVecString_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_delete_VecVecString")]
  public static extern void delete_VecVecString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getInt")]
  public static extern int getInt();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getDouble")]
  public static extern double getDouble();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getChar")]
  public static extern char getChar();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getBool")]
  public static extern bool getBool();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getConstChar")]
  public static extern string getConstChar();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getStdString")]
  public static extern string getStdString();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfInt")]
  public static extern global::System.IntPtr getVectorOfInt();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfVectorOfInt")]
  public static extern global::System.IntPtr getVectorOfVectorOfInt();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfDouble")]
  public static extern global::System.IntPtr getVectorOfDouble();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfVectorOfDouble")]
  public static extern global::System.IntPtr getVectorOfVectorOfDouble();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfString")]
  public static extern global::System.IntPtr getVectorOfString();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_getVectorOfVectorOfString")]
  public static extern global::System.IntPtr getVectorOfVectorOfString();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_testVectorOfVectorOfDoubles")]
  public static extern string testVectorOfVectorOfDoubles(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_throwAnException")]
  public static extern int throwAnException();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_throwAnIllegalArgumentException")]
  public static extern int throwAnIllegalArgumentException();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_sumUp__SWIG_0")]
  public static extern double sumUp__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_sumUp__SWIG_1")]
  public static extern double sumUp__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_doSomeFormula")]
  public static extern double doSomeFormula(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_setUpMLIB")]
  public static extern string setUpMLIB(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_tearDownMLIB")]
  public static extern string tearDownMLIB();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetUpOISCurve")]
  public static extern string mirSetUpOISCurve(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, string jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetUpSwapCurve")]
  public static extern string mirSetUpSwapCurve(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11, global::System.Runtime.InteropServices.HandleRef jarg12, global::System.Runtime.InteropServices.HandleRef jarg13, global::System.Runtime.InteropServices.HandleRef jarg14, global::System.Runtime.InteropServices.HandleRef jarg15, string jarg16, string jarg17);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetUpBasisSwapCurve__SWIG_0")]
  public static extern string mirSetUpBasisSwapCurve__SWIG_0(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, string jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetUpBasisSwapCurve__SWIG_1")]
  public static extern string mirSetUpBasisSwapCurve__SWIG_1(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, string jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDateFromTerm")]
  public static extern string mirGetDateFromTerm(string jarg1, double jarg2, string jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDate__SWIG_0")]
  public static extern string mirGetDate__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDate__SWIG_1")]
  public static extern global::System.IntPtr mirGetDate__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetIMMDate1")]
  public static extern string mirGetIMMDate1(int jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetIMMDate2")]
  public static extern string mirGetIMMDate2(int jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetIMMDate3")]
  public static extern string mirGetIMMDate3(string jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetParRate4")]
  public static extern double mirGetParRate4(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, string jarg16, string jarg17, string jarg18, string jarg19, string jarg20, double jarg21, double jarg22, string jarg23, string jarg24, string jarg25, string jarg26, string jarg27, bool jarg28, bool jarg29, double jarg30, bool jarg31);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetParRate5")]
  public static extern double mirGetParRate5(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, string jarg16, string jarg17, string jarg18, string jarg19, string jarg20, double jarg21, double jarg22, string jarg23, string jarg24, string jarg25, string jarg26, string jarg27, bool jarg28, bool jarg29, double jarg30, bool jarg31, string jarg32);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetParRate3")]
  public static extern double mirGetParRate3(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, bool jarg14, bool jarg15);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirOISParRate")]
  public static extern double mirOISParRate(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, string jarg16, string jarg17, string jarg18, string jarg19, string jarg20, double jarg21, double jarg22, string jarg23, string jarg24, string jarg25, string jarg26, string jarg27, bool jarg28, double jarg29, string jarg30);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirOISSwapPV")]
  public static extern double mirOISSwapPV(double jarg1, string jarg2, string jarg3, string jarg4, string jarg5, double jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, double jarg16, string jarg17, string jarg18, string jarg19, string jarg20, string jarg21, string jarg22, string jarg23, string jarg24, double jarg25, double jarg26, string jarg27, string jarg28, string jarg29, string jarg30, string jarg31, bool jarg32, string jarg33);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSwapPV")]
  public static extern double mirSwapPV(double jarg1, string jarg2, string jarg3, string jarg4, string jarg5, double jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, double jarg16, string jarg17, string jarg18, string jarg19, string jarg20, string jarg21, string jarg22, string jarg23, string jarg24, double jarg25, double jarg26, string jarg27, string jarg28, string jarg29, string jarg30, string jarg31, bool jarg32, bool jarg33);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF1__SWIG_0")]
  public static extern double mirGetDF1__SWIG_0(double jarg1, string jarg2, string jarg3, string jarg4, bool jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF1__SWIG_1")]
  public static extern global::System.IntPtr mirGetDF1__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, bool jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF2__SWIG_0")]
  public static extern double mirGetDF2__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, bool jarg7, string jarg8);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF2__SWIG_1")]
  public static extern global::System.IntPtr mirGetDF2__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, bool jarg7, string jarg8);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF3__SWIG_0")]
  public static extern double mirGetDF3__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF3__SWIG_1")]
  public static extern global::System.IntPtr mirGetDF3__SWIG_1(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF4__SWIG_0")]
  public static extern double mirGetDF4__SWIG_0(string jarg1, double jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF4__SWIG_1")]
  public static extern global::System.IntPtr mirGetDF4__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF5__SWIG_0")]
  public static extern double mirGetDF5__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetDF5__SWIG_1")]
  public static extern global::System.IntPtr mirGetDF5__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, bool jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetPCAResults")]
  public static extern global::System.IntPtr mirGetPCAResults(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetupPCA")]
  public static extern string mirSetupPCA(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirInterpolation")]
  public static extern double mirInterpolation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetForwardRate2")]
  public static extern global::System.IntPtr mirGetForwardRate2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, bool jarg10, bool jarg11);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSetUpFwdFXConstantCurve")]
  public static extern string mirSetUpFwdFXConstantCurve(string jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSwapStubRate")]
  public static extern double mirSwapStubRate(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7, string jarg8, bool jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, global::System.Runtime.InteropServices.HandleRef jarg15, global::System.Runtime.InteropServices.HandleRef jarg16, global::System.Runtime.InteropServices.HandleRef jarg17, string jarg18, string jarg19, bool jarg20, bool jarg21);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetZeroRate1__SWIG_0")]
  public static extern double mirGetZeroRate1__SWIG_0(double jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetZeroRate1__SWIG_1")]
  public static extern global::System.IntPtr mirGetZeroRate1__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetZeroRate2__SWIG_0")]
  public static extern double mirGetZeroRate2__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, bool jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetZeroRate2__SWIG_1")]
  public static extern global::System.IntPtr mirGetZeroRate2__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, bool jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirOutputCurve")]
  public static extern global::System.IntPtr mirOutputCurve(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSwapPV01")]
  public static extern double mirSwapPV01(double jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, double jarg15, string jarg16, string jarg17, string jarg18, string jarg19, string jarg20, string jarg21, string jarg22, string jarg23, double jarg24, double jarg25, string jarg26, string jarg27, string jarg28, string jarg29, string jarg30, bool jarg31, bool jarg32);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirCompound3__SWIG_0")]
  public static extern global::System.IntPtr mirCompound3__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5, double jarg6, bool jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirCompound3__SWIG_1")]
  public static extern double mirCompound3__SWIG_1(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, double jarg6, bool jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetAnnuity1")]
  public static extern double mirGetAnnuity1(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetAnnuity2")]
  public static extern double mirGetAnnuity2(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetBusinessDays")]
  public static extern int mirGetBusinessDays(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetECBStartDate")]
  public static extern string mirGetECBStartDate(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetNextCBDate")]
  public static extern string mirGetNextCBDate(string jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetNextECBDate")]
  public static extern string mirGetNextECBDate(string jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirGetTerm")]
  public static extern double mirGetTerm(string jarg1, string jarg2, string jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirSwapSchedule")]
  public static extern global::System.IntPtr mirSwapSchedule(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15, string jarg16, string jarg17, bool jarg18);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_mirClearEntityPool")]
  public static extern string mirClearEntityPool();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCalibrateBasis__SWIG_0")]
  public static extern string meCurveCalibrateBasis__SWIG_0(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCalibrateBasis__SWIG_1")]
  public static extern string meCurveCalibrateBasis__SWIG_1(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCalibrateFXForwards")]
  public static extern string meCurveCalibrateFXForwards(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCalibrateOIS")]
  public static extern string meCurveCalibrateOIS(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCalibrateSwap")]
  public static extern string meCurveCalibrateSwap(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9, global::System.Runtime.InteropServices.HandleRef jarg10, global::System.Runtime.InteropServices.HandleRef jarg11, global::System.Runtime.InteropServices.HandleRef jarg12, global::System.Runtime.InteropServices.HandleRef jarg13, global::System.Runtime.InteropServices.HandleRef jarg14, global::System.Runtime.InteropServices.HandleRef jarg15, global::System.Runtime.InteropServices.HandleRef jarg16);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCompoundRate__SWIG_0")]
  public static extern global::System.IntPtr meCurveCompoundRate__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5, double jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveCompoundRate__SWIG_1")]
  public static extern double meCurveCompoundRate__SWIG_1(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, double jarg6, string jarg7, string jarg8, string jarg9, string jarg10, string jarg11, string jarg12, string jarg13, string jarg14, string jarg15);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsFromYearFractions__SWIG_0")]
  public static extern double meCurveDiscountFactorsFromYearFractions__SWIG_0(double jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsFromYearFractions__SWIG_1")]
  public static extern global::System.IntPtr meCurveDiscountFactorsFromYearFractions__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsFromTenors__SWIG_0")]
  public static extern double meCurveDiscountFactorsFromTenors__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsFromTenors__SWIG_1")]
  public static extern global::System.IntPtr meCurveDiscountFactorsFromTenors__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStarting__SWIG_0")]
  public static extern double meCurveDiscountFactorsForwardStarting__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStarting__SWIG_1")]
  public static extern global::System.IntPtr meCurveDiscountFactorsForwardStarting__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_0")]
  public static extern double meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_0(string jarg1, double jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_1")]
  public static extern global::System.IntPtr meCurveDiscountFactorsForwardStartingFromYearFractions__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStartingFromTenor__SWIG_0")]
  public static extern double meCurveDiscountFactorsForwardStartingFromTenor__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDiscountFactorsForwardStartingFromTenor__SWIG_1")]
  public static extern global::System.IntPtr meCurveDiscountFactorsForwardStartingFromTenor__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveDisplay")]
  public static extern global::System.IntPtr meCurveDisplay(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveForwardRatesFromYearFraction")]
  public static extern global::System.IntPtr meCurveForwardRatesFromYearFraction(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveForwardRates")]
  public static extern global::System.IntPtr meCurveForwardRates(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveZeroRatesFromYearFractions__SWIG_0")]
  public static extern double meCurveZeroRatesFromYearFractions__SWIG_0(double jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveZeroRatesFromYearFractions__SWIG_1")]
  public static extern global::System.IntPtr meCurveZeroRatesFromYearFractions__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveZeroRatesFromTenors__SWIG_0")]
  public static extern double meCurveZeroRatesFromTenors__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meCurveZeroRatesFromTenors__SWIG_1")]
  public static extern global::System.IntPtr meCurveZeroRatesFromTenors__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateFromTenor__SWIG_0")]
  public static extern string meDateFromTenor__SWIG_0(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateFromTenor__SWIG_1")]
  public static extern global::System.IntPtr meDateFromTenor__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateFromYearFraction")]
  public static extern string meDateFromYearFraction(string jarg1, double jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateBusinessDays")]
  public static extern int meDateBusinessDays(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateCentralBank")]
  public static extern string meDateCentralBank(string jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateECB")]
  public static extern string meDateECB(string jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateECBSwapStart")]
  public static extern string meDateECBSwapStart(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateECBSwapEnd")]
  public static extern string meDateECBSwapEnd(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateIMMFromMonth")]
  public static extern string meDateIMMFromMonth(int jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateNthIMM")]
  public static extern string meDateNthIMM(int jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meDateNthIMMFromStartDate")]
  public static extern string meDateNthIMMFromStartDate(string jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductAssetSwapSpread__SWIG_0")]
  public static extern double meProductAssetSwapSpread__SWIG_0(double jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductAssetSwapSpread__SWIG_1")]
  public static extern double meProductAssetSwapSpread__SWIG_1(double jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductAssetSwapSpreadLVBKeys")]
  public static extern global::System.IntPtr meProductAssetSwapSpreadLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISParRate__SWIG_0")]
  public static extern double meProductOISParRate__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISParRate__SWIG_1")]
  public static extern double meProductOISParRate__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISParRateLVBKeys")]
  public static extern global::System.IntPtr meProductOISParRateLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISPV__SWIG_0")]
  public static extern double meProductOISPV__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISPV__SWIG_1")]
  public static extern double meProductOISPV__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductOISPVLVBKeys")]
  public static extern global::System.IntPtr meProductOISPVLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapDV01__SWIG_0")]
  public static extern double meProductSwapDV01__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapDV01__SWIG_1")]
  public static extern double meProductSwapDV01__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapDV01LVBKeys")]
  public static extern global::System.IntPtr meProductSwapDV01LVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapParRate__SWIG_0")]
  public static extern double meProductSwapParRate__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapParRate__SWIG_1")]
  public static extern double meProductSwapParRate__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapParRateLVBKeys")]
  public static extern global::System.IntPtr meProductSwapParRateLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapPV__SWIG_0")]
  public static extern double meProductSwapPV__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapPV__SWIG_1")]
  public static extern double meProductSwapPV__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_tryMeProductSwapPVLVBKeys")]
  public static extern global::System.IntPtr tryMeProductSwapPVLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapPV01__SWIG_0")]
  public static extern double meProductSwapPV01__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapPV01__SWIG_1")]
  public static extern double meProductSwapPV01__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapPV01LVBKeys")]
  public static extern global::System.IntPtr meProductSwapPV01LVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapSchedule__SWIG_0")]
  public static extern global::System.IntPtr meProductSwapSchedule__SWIG_0(bool jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapSchedule__SWIG_1")]
  public static extern global::System.IntPtr meProductSwapSchedule__SWIG_1(bool jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapScheduleLVBKeys")]
  public static extern global::System.IntPtr meProductSwapScheduleLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapStubRate")]
  public static extern double meProductSwapStubRate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meProductSwapStubRateLVBKeys")]
  public static extern global::System.IntPtr meProductSwapStubRateLVBKeys();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityInterpolation")]
  public static extern double meUtilityInterpolation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityPCA")]
  public static extern global::System.IntPtr meUtilityPCA(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityClearEntityPool")]
  public static extern string meUtilityClearEntityPool();

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityLoadCalendarFile")]
  public static extern string meUtilityLoadCalendarFile(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityLoadStaticData")]
  public static extern string meUtilityLoadStaticData(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("MLIB_CLIENT_API", EntryPoint="CSharp_meUtilityVersion")]
  public static extern string meUtilityVersion(int jarg1, int jarg2);
}
