//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VecVecInteger : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<VecInteger>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VecVecInteger(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VecVecInteger obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VecVecInteger() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MLIB_CLIENT_APIPINVOKE.delete_VecVecInteger(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VecVecInteger(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VecInteger element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VecInteger this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VecInteger[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VecInteger[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VecInteger[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<VecInteger> global::System.Collections.Generic.IEnumerable<VecInteger>.GetEnumerator() {
    return new VecVecIntegerEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VecVecIntegerEnumerator(this);
  }

  public VecVecIntegerEnumerator GetEnumerator() {
    return new VecVecIntegerEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VecVecIntegerEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VecInteger>
  {
    private VecVecInteger collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VecVecIntegerEnumerator(VecVecInteger collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VecInteger Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VecInteger)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_Clear(swigCPtr);
  }

  public void Add(VecInteger x) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_Add(swigCPtr, VecInteger.getCPtr(x));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = MLIB_CLIENT_APIPINVOKE.VecVecInteger_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = MLIB_CLIENT_APIPINVOKE.VecVecInteger_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_reserve(swigCPtr, n);
  }

  public VecVecInteger() : this(MLIB_CLIENT_APIPINVOKE.new_VecVecInteger__SWIG_0(), true) {
  }

  public VecVecInteger(VecVecInteger other) : this(MLIB_CLIENT_APIPINVOKE.new_VecVecInteger__SWIG_1(VecVecInteger.getCPtr(other)), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecInteger(int capacity) : this(MLIB_CLIENT_APIPINVOKE.new_VecVecInteger__SWIG_2(capacity), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  private VecInteger getitemcopy(int index) {
    VecInteger ret = new VecInteger(MLIB_CLIENT_APIPINVOKE.VecVecInteger_getitemcopy(swigCPtr, index), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VecInteger getitem(int index) {
    VecInteger ret = new VecInteger(MLIB_CLIENT_APIPINVOKE.VecVecInteger_getitem(swigCPtr, index), false);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VecInteger val) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_setitem(swigCPtr, index, VecInteger.getCPtr(val));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VecVecInteger values) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_AddRange(swigCPtr, VecVecInteger.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecInteger GetRange(int index, int count) {
    global::System.IntPtr cPtr = MLIB_CLIENT_APIPINVOKE.VecVecInteger_GetRange(swigCPtr, index, count);
    VecVecInteger ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecVecInteger(cPtr, true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VecInteger x) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_Insert(swigCPtr, index, VecInteger.getCPtr(x));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VecVecInteger values) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_InsertRange(swigCPtr, index, VecVecInteger.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_RemoveAt(swigCPtr, index);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_RemoveRange(swigCPtr, index, count);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VecVecInteger Repeat(VecInteger value, int count) {
    global::System.IntPtr cPtr = MLIB_CLIENT_APIPINVOKE.VecVecInteger_Repeat(VecInteger.getCPtr(value), count);
    VecVecInteger ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecVecInteger(cPtr, true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_Reverse__SWIG_1(swigCPtr, index, count);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VecVecInteger values) {
    MLIB_CLIENT_APIPINVOKE.VecVecInteger_SetRange(swigCPtr, index, VecVecInteger.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

}
