#pragma once

#include "LADefinitions.h"

#define CREDIT_KEY_HZD_INTERPOLATION	".sde.hzd.interpolation"
#define CREDIT_KEY_HZD_RECOVERYRATE ".sde.hzd.recoveryrate"	// For xva calculation
#define CREDIT_KEY_HZD_CDS_CURRENCY	".sde.hzd.cds.currency"
#define CREDIT_KEY_HZD_CDS_CALENDAR	".sde.hzd.cds.calendar"
#define CREDIT_KEY_HZD_CDS_DISCOUNTCURVE	".sde.hzd.cds.discountcurve"
#define CREDIT_KEY_HZD_CDS_DISCOUNTCURVE_STD	".sde.hzd.cds.discountcurve.std"
#define CREDIT_KEY_HZD_CDS_PRICE_FILE	".sde.hzd.cds.price.file"
#define CREDIT_KEY_HZD_CDS_PRICE_USEGRID	".sde.hzd.cds.price.usegrid"
#define CREDIT_KEY_HZD_CDS_PRICE_TYPE	".sde.hzd.cds.price.type"
#define CREDIT_KEY_HZD_CDS_RECOVERYRATE ".sde.hzd.cds.recoveryrate"
#define CREDIT_KEY_HZD_CDS_SPOTLAG	".sde.hzd.cds.spotlag"
#define CREDIT_KEY_HZD_CDS_ISHOLIDAYADJUST	".sde.hzd.cds.isholidayadjust"
#define CREDIT_KEY_HZD_CDS_DIRECTION	".sde.hzd.cds.direction"
#define CREDIT_KEY_HZD_CDS_FREQUENCY	".sde.hzd.cds.frequency"
#define CREDIT_KEY_HZD_CDS_SLIDINGRULE	".sde.hzd.cds.slidingrule"
#define CREDIT_KEY_HZD_CDS_DAYCOUNT	".sde.hzd.cds.daycount"
#define CREDIT_KEY_HZD_CDS_ISBOTHEND	".sde.hzd.cds.isbothend"
#define CREDIT_KEY_HZD_CDS_PAYMENTTIMING	".sde.hzd.cds.paymenttiming"
#define CREDIT_KEY_HZD_CDS_ISDEFAULTACCRUAL	".sde.hzd.cds.isdefaultaccrual"
#define CREDIT_KEY_HZD_CDS_DETDAY	".sde.hzd.cds.detday"
#define CREDIT_KEY_HZD_CDS_ISINPUTCRVEDATA	".sde.hzd.cds.isinputcurvedata"
#define CREDIT_KEY_HZD_CDS_ISINPUTCRVEDATA_STD	".sde.hzd.cds.isinputcurvedata.std"
