@echo off

TITLE Setting MLIBQ_LOCATION Environment Variable
setlocal EnableDelayedExpansion

:REPEAT
ECHO.
ECHO.
ECHO PLEASE SELECT YOUR LOCATION
ECHO -----------------------------------------
ECHO TOKYO=1
ECHO LONDON=2
ECHO NEW YORK=3
ECHO.
SET /P SELECTED_LOCATION="SELECT LOCATION : "

IF %SELECTED_LOCATION%==1 ( 
	SET LOCATION_STRING=JP 
	GOTO :SET_ENVIRONMENT_VARIABLE )

IF %SELECTED_LOCATION%==2 ( 
	SET LOCATION_STRING=UK 
	GOTO :SET_ENVIRONMENT_VARIABLE )

IF %SELECTED_LOCATION%==3 ( 
	SET LOCATION_STRING=US 
	GOTO :SET_ENVIRONMENT_VARIABLE )	

REM REPEAT SELECTION CHOICE IF RESPONSE IS INVALID	
GOTO :REPEAT

:SET_ENVIRONMENT_VARIABLE
ECHO.
ECHO.
ECHO Setting LOCATION Environment Variable
ECHO -----------------------------------------

setx MLIBQ_LOCATION %LOCATION_STRING%
ECHO MLIBQ_LOCATION=%LOCATION_STRING%
ECHO.

PAUSE