"""Generate the per-function enable header for the Release_XL_Manifest AQ_XLL config.

Every AQ_XLL worksheet function is wrapped `#if AQ_XLL_ENABLED(name) ... #endif`
(CLAUDE.md Sec 4.4/9.5, MIGRATION_PLAN.md manifest-build section). AQ_XLL_ENABLED
is defined once in src\\AQ_XLL\\include\\aqXllTools.h as:

    #define AQ_XLL_ENABLED(name)  (!AQ_XLL_MANIFEST_BUILD || AQ_XLL_ENABLE_##name)

For every other configuration AQ_XLL_MANIFEST_BUILD is 0, so the guard is always
true regardless of this script. Only the Release_XL_Manifest configuration
defines AQ_XLL_MANIFEST_BUILD=1 and force-includes (/FI) the header this script
writes, which lists one AQ_XLL_ENABLE_<name> 0/1 per known function. The header
is generated (via a PreBuildEvent), not checked in.

Ground truth for "known function names" is the AQ_XLL source itself (every
XLO_FUNC_START(name...) site), not docs\\api_map.csv, so this script has no
dependency on that file staying in sync with the XLL port.

Manifest "functions" is either an explicit list of names, or the literal
string "*" meaning "every function known today" -- resolved fresh from the
source scan above at generation time, so a full/default edition never needs a
hand-maintained list that can go stale as functions are added or renamed.

Usage:
  python resources/scripts/generate_xll_manifest_header.py <manifest.json> <output_header.h>

Exit status 1 if the manifest names a function that does not exist in AQ_XLL.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
XLL_SRC_DIR = os.path.join(ROOT, "src", "AQ_XLL", "src")

START_RE = re.compile(r'^XLO_FUNC_START\(\s*([A-Za-z_][A-Za-z0-9_]*)', re.MULTILINE)


def known_functions():
    names = []
    for fname in sorted(os.listdir(XLL_SRC_DIR)):
        if not fname.endswith(".cpp"):
            continue
        with open(os.path.join(XLL_SRC_DIR, fname), encoding="utf-8") as f:
            text = f.read()
        names.extend(START_RE.findall(text))
    return names


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    manifest_path, out_path = sys.argv[1], sys.argv[2]

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    requested = manifest.get("functions", [])
    edition = manifest.get("edition", os.path.splitext(os.path.basename(manifest_path))[0])

    all_names = known_functions()
    all_names_set = set(all_names)

    if requested == "*":
        requested_set = set(all_names_set)
    else:
        unknown = sorted(set(requested) - all_names_set)
        if unknown:
            print("ERROR: manifest names functions that do not exist in AQ_XLL:")
            for name in unknown:
                print(f"  {name}")
            return 1
        requested_set = set(requested)

    lines = [
        "#pragma once",
        "",
        f"// GENERATED by resources/scripts/generate_xll_manifest_header.py -- do not edit.",
        f"// Source manifest: {os.path.relpath(manifest_path, ROOT)}  (edition: {edition})",
        f"// {len(requested_set)} of {len(all_names_set)} known AQ_XLL functions enabled.",
        "",
    ]
    for name in all_names:
        lines.append(f"#define AQ_XLL_ENABLE_{name} {1 if name in requested_set else 0}")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Wrote {out_path}: {len(requested_set)}/{len(all_names_set)} functions enabled for edition '{edition}'.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
