@echo off

REM Read Folder Control variables
IF NOT DEFINED FOLDERS_UPDATED CALL %~dp0..\FolderControl\MLIBQ_FOLDERS_MASTER.bat

TITLE DEPLOY LONDON MLIBQ RELEASE TO TOKYO
ECHO PLEASE ENTER THE MLIB EXCEL ADDIN VERSION
ECHO -------------------------------------------------------------------------
ECHO Please Specify the Build Date YYYY-MM-DD and Version Number N (if any)
ECHO In the following Format : YYYY-MM-DD.N for example 2017-02-14.1
ECHO -------------------------------------------------------------------------

SET /P VERSION="Enter the MLIBQ EXCEL VERSION : "

:SELECT_BIT
ECHO.
ECHO Select Excel Version Bit Architecture 32/64 to Deploy:
ECHO 1) 32 BIT ONLY
ECHO 2) 64 BIT ONLY
ECHO 3) 32 AND 64 BIT

SET /P ARCH="Enter 1, 2 or 3 : "

IF  %ARCH% == 1 GOTO :BIT_OK
IF  %ARCH% == 2 GOTO :BIT_OK
IF  %ARCH% == 3 GOTO :BIT_OK
GOTO :SELECT_BIT

:BIT_OK

REM SET TOKYO FOLDER VARIABLES
set TOKYO32="%DEPLOYMENT_FOLDER_TOKYO_MLIBQ_PRODUCTION%\%VERSION%"
set TOKYO64="%DEPLOYMENT_FOLDER_TOKYO_MLIBQ_PRODUCTION_X64%\%VERSION%"

REM SET LONDON FOLDER VARIABLES
IF %ARCH% == 1 ( 
set LONDON32="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION%\%VERSION%"
set LONDON64=""
)

IF %ARCH% == 2 ( 
set LONDON32=""
set LONDON64="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION_X64%\%VERSION%"
)

IF %ARCH% == 3 ( 
set LONDON32="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION%\%VERSION%"
set LONDON64="%DEPLOYMENT_FOLDER_MLIBQ_PRODUCTION_X64%\%VERSION%"
)

REM COPY AND DEPLOY EXCEL ADDIN FROM LONDON TO TOKYO IF THE FILE EXISTS
IF NOT %LONDON32% == "" (
IF NOT EXIST "%LONDON32%" (
ECHO. 
ECHO UNABLE TO COPY THE LONDON X32 ADDIN
ECHO LONDON X32 ADDIN DOES NOT EXIST:
ECHO %LONDON32%
ECHO.
GOTO :FAILURE )
)

IF NOT %LONDON32% == "" (
IF EXIST "%TOKYO32%" (
ECHO. 
ECHO UNABLE TO COPY THE LONDON X86 ADDIN
ECHO THE TOKYO X86 VERSION ALREADY EXISTS
ECHO "%TOKYO32%"
ECHO.
GOTO :FAILURE )
)

IF NOT %LONDON64% == "" (
IF NOT EXIST "%LONDON64%" (
ECHO. 
ECHO UNABLE TO COPY THE LONDON X64 ADDIN
ECHO LONDON X64 ADDIN DOES NOT EXIST:
ECHO %LONDON64%
ECHO.
GOTO :FAILURE )
)

IF NOT %LONDON64% == "" (
IF EXIST "%TOKYO64%" (
ECHO. 
ECHO UNABLE TO COPY THE LONDON X64 ADDIN
ECHO THE TOKYO X64 VERSION ALREADY EXISTS
ECHO "%TOKYO64%"
ECHO.
GOTO :FAILURE )
)

IF NOT %LONDON32% == "" (
TITLE DEPLOYING MLIBQ EXCEL ADDIN X86
ECHO.
ECHO DEPLOYING MLIBQ EXCEL ADDIN X86 
ECHO --------------------------------
ECHO Copying from: "%LONDON32%"
ECHO Copying to: "%TOKYO32%\"
ECHO.
mkdir "%TOKYO32%"
xcopy /s /y "%LONDON32%" "%TOKYO32%\"
)

IF NOT %LONDON64% == "" (
TITLE DEPLOYING MLIBQ EXCEL ADDIN X64
ECHO.
ECHO DEPLOYING MLIBQ EXCEL ADDIN X64 
ECHO --------------------------------
ECHO Copying from: "%LONDON64%"
ECHO Copying to:"%TOKYO64%\"
ECHO.
mkdir "%TOKYO64%"
xcopy /s /y "%LONDON64%" "%TOKYO64%\"
)

:SUCCESS
TITLE SUCCESS
ECHO.
ECHO SUCCESS DEPLOYED LONDON MLIBQ EXCEL ADDINS TO TOKYO
PAUSE
EXIT

:FAILURE
TITLE FAILURE
ECHO.
ECHO. FAILED TO DEPLOY LONDON MLIBQ EXCEL ADDINS TO TOKYO
PAUSE
EXIT
