@echo off

REM READ FOLDER CONTROL VARIABLES
IF NOT DEFINED FOLDERS_UPDATED CALL %~dp0\..\FolderControl\MLIB_FOLDERS_MASTER.bat

REM THE ORIGINAL FOLDER IS PASSED TO THIS FILE AS THE FIRST ARGUMENT
SET ORIGINAL_FOLDER_PATH=%1

REM CREATE A NEW FOLDER NAME AS THE ORIGINAL FOLDER WITH A SUFFIX FOR THE NEXT AVAILABLE VERSION NUMBER
REM E.G. COPYFILE -> COPYFILE.1
SET VERSION_COUNTER=0

REM WHILE LOOP UPDATE THE VERSION COUNTER TO THE NEXT FREE VERSION NUMBER
:WHILE_LOOP
SET /A VERSION_COUNTER=VERSION_COUNTER+1
SET NEW_FOLDER_PATH="%ORIGINAL_FOLDER_PATH%.%VERSION_COUNTER%"
IF EXIST "%NEW_FOLDER_PATH%" GOTO :WHILE_LOOP

REM REMOVE SURROUNDING QUOTES FROM THE FOLDER PATH
set NEW_FOLDER_PATH=%NEW_FOLDER_PATH:"=%

REM WE END HERE AND RETURN THE NEW_FOLDER_PATH