# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_MLIB_CLIENT_API', [dirname(__file__)])
        except ImportError:
            import _MLIB_CLIENT_API
            return _MLIB_CLIENT_API
        if fp is not None:
            try:
                _mod = imp.load_module('_MLIB_CLIENT_API', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _MLIB_CLIENT_API = swig_import_helper()
    del swig_import_helper
else:
    import _MLIB_CLIENT_API
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _MLIB_CLIENT_API.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _MLIB_CLIENT_API.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _MLIB_CLIENT_API.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _MLIB_CLIENT_API.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _MLIB_CLIENT_API.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _MLIB_CLIENT_API.SwigPyIterator_equal(self, x)

    def copy(self):
        return _MLIB_CLIENT_API.SwigPyIterator_copy(self)

    def next(self):
        return _MLIB_CLIENT_API.SwigPyIterator_next(self)

    def __next__(self):
        return _MLIB_CLIENT_API.SwigPyIterator___next__(self)

    def previous(self):
        return _MLIB_CLIENT_API.SwigPyIterator_previous(self)

    def advance(self, n):
        return _MLIB_CLIENT_API.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _MLIB_CLIENT_API.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _MLIB_CLIENT_API.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _MLIB_CLIENT_API.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _MLIB_CLIENT_API.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _MLIB_CLIENT_API.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _MLIB_CLIENT_API.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _MLIB_CLIENT_API.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VecInteger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecInteger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecInteger, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecInteger_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecInteger___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecInteger___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecInteger___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecInteger___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecInteger___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecInteger___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecInteger___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecInteger___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecInteger___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecInteger_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecInteger_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecInteger_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecInteger_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecInteger_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecInteger_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecInteger_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecInteger_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecInteger_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecInteger_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecInteger_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecInteger_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecInteger_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecInteger(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecInteger_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecInteger_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecInteger_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecInteger_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecInteger_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecInteger_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecInteger_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecInteger_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecInteger
    __del__ = lambda self: None
VecInteger_swigregister = _MLIB_CLIENT_API.VecInteger_swigregister
VecInteger_swigregister(VecInteger)

class VecVecInteger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecInteger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecInteger, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecVecInteger_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecVecInteger___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecVecInteger___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecVecInteger___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecInteger___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecInteger___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecVecInteger_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecVecInteger_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecVecInteger_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecVecInteger_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecVecInteger_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecVecInteger_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecVecInteger_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecVecInteger_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecVecInteger_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecVecInteger_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecVecInteger_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecVecInteger_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecVecInteger(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecVecInteger_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecVecInteger_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecVecInteger_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecVecInteger_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecVecInteger_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecVecInteger_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecVecInteger_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecVecInteger
    __del__ = lambda self: None
VecVecInteger_swigregister = _MLIB_CLIENT_API.VecVecInteger_swigregister
VecVecInteger_swigregister(VecVecInteger)

class VecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecDouble___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecDouble___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecDouble___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecDouble_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecDouble_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecDouble_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecDouble_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecDouble_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecDouble_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecDouble_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecDouble_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecDouble_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecDouble_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecDouble_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecDouble_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecDouble_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecDouble(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecDouble_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecDouble_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecDouble_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecDouble_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecDouble_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecDouble
    __del__ = lambda self: None
VecDouble_swigregister = _MLIB_CLIENT_API.VecDouble_swigregister
VecDouble_swigregister(VecDouble)

class VecVecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecVecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecVecDouble___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecVecDouble___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecVecDouble___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecVecDouble_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecVecDouble_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecVecDouble_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecVecDouble_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecVecDouble_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecVecDouble_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecVecDouble_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecVecDouble_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecVecDouble_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecVecDouble_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecVecDouble_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecVecDouble_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecVecDouble(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecVecDouble_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecVecDouble_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecVecDouble_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecVecDouble_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecVecDouble_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecVecDouble_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecVecDouble_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecVecDouble
    __del__ = lambda self: None
VecVecDouble_swigregister = _MLIB_CLIENT_API.VecVecDouble_swigregister
VecVecDouble_swigregister(VecVecDouble)

class VecString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecString, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecString___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecString___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecString___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecString___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecString___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecString___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecString___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecString___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecString___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecString_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecString_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecString_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecString_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecString_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecString_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecString_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecString_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecString_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecString_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecString_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecString_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecString_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecString(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecString_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecString_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecString_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecString_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecString_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecString_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecString_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecString_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecString
    __del__ = lambda self: None
VecString_swigregister = _MLIB_CLIENT_API.VecString_swigregister
VecString_swigregister(VecString)

class VecVecString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecString, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _MLIB_CLIENT_API.VecVecString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _MLIB_CLIENT_API.VecVecString___nonzero__(self)

    def __bool__(self):
        return _MLIB_CLIENT_API.VecVecString___bool__(self)

    def __len__(self):
        return _MLIB_CLIENT_API.VecVecString___len__(self)

    def __getslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecString___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _MLIB_CLIENT_API.VecVecString___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _MLIB_CLIENT_API.VecVecString___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecString___delitem__(self, *args)

    def __getitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecString___getitem__(self, *args)

    def __setitem__(self, *args):
        return _MLIB_CLIENT_API.VecVecString___setitem__(self, *args)

    def pop(self):
        return _MLIB_CLIENT_API.VecVecString_pop(self)

    def append(self, x):
        return _MLIB_CLIENT_API.VecVecString_append(self, x)

    def empty(self):
        return _MLIB_CLIENT_API.VecVecString_empty(self)

    def size(self):
        return _MLIB_CLIENT_API.VecVecString_size(self)

    def swap(self, v):
        return _MLIB_CLIENT_API.VecVecString_swap(self, v)

    def begin(self):
        return _MLIB_CLIENT_API.VecVecString_begin(self)

    def end(self):
        return _MLIB_CLIENT_API.VecVecString_end(self)

    def rbegin(self):
        return _MLIB_CLIENT_API.VecVecString_rbegin(self)

    def rend(self):
        return _MLIB_CLIENT_API.VecVecString_rend(self)

    def clear(self):
        return _MLIB_CLIENT_API.VecVecString_clear(self)

    def get_allocator(self):
        return _MLIB_CLIENT_API.VecVecString_get_allocator(self)

    def pop_back(self):
        return _MLIB_CLIENT_API.VecVecString_pop_back(self)

    def erase(self, *args):
        return _MLIB_CLIENT_API.VecVecString_erase(self, *args)

    def __init__(self, *args):
        this = _MLIB_CLIENT_API.new_VecVecString(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _MLIB_CLIENT_API.VecVecString_push_back(self, x)

    def front(self):
        return _MLIB_CLIENT_API.VecVecString_front(self)

    def back(self):
        return _MLIB_CLIENT_API.VecVecString_back(self)

    def assign(self, n, x):
        return _MLIB_CLIENT_API.VecVecString_assign(self, n, x)

    def resize(self, *args):
        return _MLIB_CLIENT_API.VecVecString_resize(self, *args)

    def insert(self, *args):
        return _MLIB_CLIENT_API.VecVecString_insert(self, *args)

    def reserve(self, n):
        return _MLIB_CLIENT_API.VecVecString_reserve(self, n)

    def capacity(self):
        return _MLIB_CLIENT_API.VecVecString_capacity(self)
    __swig_destroy__ = _MLIB_CLIENT_API.delete_VecVecString
    __del__ = lambda self: None
VecVecString_swigregister = _MLIB_CLIENT_API.VecVecString_swigregister
VecVecString_swigregister(VecVecString)


def setUpMLIB(irPropsFullFilePath, calendarFullFilePath):
    return _MLIB_CLIENT_API.setUpMLIB(irPropsFullFilePath, calendarFullFilePath)
setUpMLIB = _MLIB_CLIENT_API.setUpMLIB

def setupMLIB():
    return _MLIB_CLIENT_API.setupMLIB()
setupMLIB = _MLIB_CLIENT_API.setupMLIB

def initMLIB():
    return _MLIB_CLIENT_API.initMLIB()
initMLIB = _MLIB_CLIENT_API.initMLIB

def tearDownMLIB():
    return _MLIB_CLIENT_API.tearDownMLIB()
tearDownMLIB = _MLIB_CLIENT_API.tearDownMLIB

def exampleInt():
    return _MLIB_CLIENT_API.exampleInt()
exampleInt = _MLIB_CLIENT_API.exampleInt

def exampleDouble():
    return _MLIB_CLIENT_API.exampleDouble()
exampleDouble = _MLIB_CLIENT_API.exampleDouble

def exampleChar():
    return _MLIB_CLIENT_API.exampleChar()
exampleChar = _MLIB_CLIENT_API.exampleChar

def exampleBool():
    return _MLIB_CLIENT_API.exampleBool()
exampleBool = _MLIB_CLIENT_API.exampleBool

def exampleConstChar():
    return _MLIB_CLIENT_API.exampleConstChar()
exampleConstChar = _MLIB_CLIENT_API.exampleConstChar

def exampleString():
    return _MLIB_CLIENT_API.exampleString()
exampleString = _MLIB_CLIENT_API.exampleString

def exampleVectorInt():
    return _MLIB_CLIENT_API.exampleVectorInt()
exampleVectorInt = _MLIB_CLIENT_API.exampleVectorInt

def exampleVectorDouble():
    return _MLIB_CLIENT_API.exampleVectorDouble()
exampleVectorDouble = _MLIB_CLIENT_API.exampleVectorDouble

def exampleVectorString():
    return _MLIB_CLIENT_API.exampleVectorString()
exampleVectorString = _MLIB_CLIENT_API.exampleVectorString

def exampleMatrixInt():
    return _MLIB_CLIENT_API.exampleMatrixInt()
exampleMatrixInt = _MLIB_CLIENT_API.exampleMatrixInt

def exampleMatrixDouble():
    return _MLIB_CLIENT_API.exampleMatrixDouble()
exampleMatrixDouble = _MLIB_CLIENT_API.exampleMatrixDouble

def exampleMatrixString():
    return _MLIB_CLIENT_API.exampleMatrixString()
exampleMatrixString = _MLIB_CLIENT_API.exampleMatrixString

def getInt():
    return _MLIB_CLIENT_API.getInt()
getInt = _MLIB_CLIENT_API.getInt

def getDouble():
    return _MLIB_CLIENT_API.getDouble()
getDouble = _MLIB_CLIENT_API.getDouble

def getChar():
    return _MLIB_CLIENT_API.getChar()
getChar = _MLIB_CLIENT_API.getChar

def getBool():
    return _MLIB_CLIENT_API.getBool()
getBool = _MLIB_CLIENT_API.getBool

def getConstChar():
    return _MLIB_CLIENT_API.getConstChar()
getConstChar = _MLIB_CLIENT_API.getConstChar

def getStdString():
    return _MLIB_CLIENT_API.getStdString()
getStdString = _MLIB_CLIENT_API.getStdString

def getVectorOfInt():
    return _MLIB_CLIENT_API.getVectorOfInt()
getVectorOfInt = _MLIB_CLIENT_API.getVectorOfInt

def getVectorOfVectorOfInt():
    return _MLIB_CLIENT_API.getVectorOfVectorOfInt()
getVectorOfVectorOfInt = _MLIB_CLIENT_API.getVectorOfVectorOfInt

def getVectorOfDouble():
    return _MLIB_CLIENT_API.getVectorOfDouble()
getVectorOfDouble = _MLIB_CLIENT_API.getVectorOfDouble

def getVectorOfVectorOfDouble():
    return _MLIB_CLIENT_API.getVectorOfVectorOfDouble()
getVectorOfVectorOfDouble = _MLIB_CLIENT_API.getVectorOfVectorOfDouble

def getVectorOfString():
    return _MLIB_CLIENT_API.getVectorOfString()
getVectorOfString = _MLIB_CLIENT_API.getVectorOfString

def getVectorOfVectorOfString():
    return _MLIB_CLIENT_API.getVectorOfVectorOfString()
getVectorOfVectorOfString = _MLIB_CLIENT_API.getVectorOfVectorOfString

def testVectorOfVectorOfDoubles(arg1):
    return _MLIB_CLIENT_API.testVectorOfVectorOfDoubles(arg1)
testVectorOfVectorOfDoubles = _MLIB_CLIENT_API.testVectorOfVectorOfDoubles

def throwAnException():
    return _MLIB_CLIENT_API.throwAnException()
throwAnException = _MLIB_CLIENT_API.throwAnException

def throwAnIllegalArgumentException():
    return _MLIB_CLIENT_API.throwAnIllegalArgumentException()
throwAnIllegalArgumentException = _MLIB_CLIENT_API.throwAnIllegalArgumentException

def sumUp(*args):
    return _MLIB_CLIENT_API.sumUp(*args)
sumUp = _MLIB_CLIENT_API.sumUp

def doSomeFormula(z):
    return _MLIB_CLIENT_API.doSomeFormula(z)
doSomeFormula = _MLIB_CLIENT_API.doSomeFormula

def mirSetUpOISCurve(CurveID, MarketName, GeneralProps, OISConv, OISRates, CurveNames, OISHistRates, LOBasisRates, SwapConv, SwapRates, LOBasisConv):
    return _MLIB_CLIENT_API.mirSetUpOISCurve(CurveID, MarketName, GeneralProps, OISConv, OISRates, CurveNames, OISHistRates, LOBasisRates, SwapConv, SwapRates, LOBasisConv)
mirSetUpOISCurve = _MLIB_CLIENT_API.mirSetUpOISCurve

def mirSetUpSwapCurve(CurveID, MarketName, YldData, MData, LData, LGrid, SData, SGrid, FRAData, FRA3MGrid, FRA6MGrid, FData, FGrid, AdjData, AdjGrid, CurveNames, CurveName_DF2):
    return _MLIB_CLIENT_API.mirSetUpSwapCurve(CurveID, MarketName, YldData, MData, LData, LGrid, SData, SGrid, FRAData, FRA3MGrid, FRA6MGrid, FData, FGrid, AdjData, AdjGrid, CurveNames, CurveName_DF2)
mirSetUpSwapCurve = _MLIB_CLIENT_API.mirSetUpSwapCurve

def mirSetUpBasisSwapCurve(*args):
    return _MLIB_CLIENT_API.mirSetUpBasisSwapCurve(*args)
mirSetUpBasisSwapCurve = _MLIB_CLIENT_API.mirSetUpBasisSwapCurve

def mirGetDateFromTerm(FromDate, TermY, DayCount, IncludeLast):
    return _MLIB_CLIENT_API.mirGetDateFromTerm(FromDate, TermY, DayCount, IncludeLast)
mirGetDateFromTerm = _MLIB_CLIENT_API.mirGetDateFromTerm

def mirGetDate(*args):
    return _MLIB_CLIENT_API.mirGetDate(*args)
mirGetDate = _MLIB_CLIENT_API.mirGetDate

def mirGetIMMDate1(Year, Month, Calendar, SlidingRule):
    return _MLIB_CLIENT_API.mirGetIMMDate1(Year, Month, Calendar, SlidingRule)
mirGetIMMDate1 = _MLIB_CLIENT_API.mirGetIMMDate1

def mirGetIMMDate2(Year, Number, Calendar, SlidingRule):
    return _MLIB_CLIENT_API.mirGetIMMDate2(Year, Number, Calendar, SlidingRule)
mirGetIMMDate2 = _MLIB_CLIENT_API.mirGetIMMDate2

def mirGetIMMDate3(BaseDate, Number, Calendar, SlidingRule):
    return _MLIB_CLIENT_API.mirGetIMMDate3(BaseDate, Number, Calendar, SlidingRule)
mirGetIMMDate3 = _MLIB_CLIENT_API.mirGetIMMDate3

def mirGetParRate4(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData):
    return _MLIB_CLIENT_API.mirGetParRate4(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData)
mirGetParRate4 = _MLIB_CLIENT_API.mirGetParRate4

def mirGetParRate5(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData, TFixCalc):
    return _MLIB_CLIENT_API.mirGetParRate5(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll, TSpd, UseFwdData, TFixCalc)
mirGetParRate5 = _MLIB_CLIENT_API.mirGetParRate5

def mirGetParRate3(fromDate, toDate, curveId, frequency, dayCount, slidingRule, calendar, interpolation, firstOddDate, lastOddDate, paymentDay, foreCurveName, dfCurveName, interpFwds, eomRoll):
    return _MLIB_CLIENT_API.mirGetParRate3(fromDate, toDate, curveId, frequency, dayCount, slidingRule, calendar, interpolation, firstOddDate, lastOddDate, paymentDay, foreCurveName, dfCurveName, interpFwds, eomRoll)
mirGetParRate3 = _MLIB_CLIENT_API.mirGetParRate3

def mirOISParRate(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, TSpd, CompMethod):
    return _MLIB_CLIENT_API.mirOISParRate(EffDt, Mat, CrvID, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, TSpd, CompMethod)
mirOISParRate = _MLIB_CLIENT_API.mirOISParRate

def mirOISSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, CompMethod):
    return _MLIB_CLIENT_API.mirOISSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, EomRoll, CompMethod)
mirOISSwapPV = _MLIB_CLIENT_API.mirOISSwapPV

def mirSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll):
    return _MLIB_CLIENT_API.mirSwapPV(notional, PayRec, EffDt, Mat, CrvID, XRt, XFreq, XDayCt, XRollCnv, XCal, XFirstStub, XLastStub, XRollDay, XPayLag, XStub, TSpd, TFreq, TDayCt, TRollCnv, TCal, TFirstStub, TLastStub, TRollDay, TFixLag, TFirstFix, TLastFix, TPayLag, TStub, Interp, Fcrv, Dcrv, InterpFwds, EomRoll)
mirSwapPV = _MLIB_CLIENT_API.mirSwapPV

def mirGetDF1(*args):
    return _MLIB_CLIENT_API.mirGetDF1(*args)
mirGetDF1 = _MLIB_CLIENT_API.mirGetDF1

def mirGetDF2(*args):
    return _MLIB_CLIENT_API.mirGetDF2(*args)
mirGetDF2 = _MLIB_CLIENT_API.mirGetDF2

def mirGetDF3(*args):
    return _MLIB_CLIENT_API.mirGetDF3(*args)
mirGetDF3 = _MLIB_CLIENT_API.mirGetDF3

def mirGetDF4(*args):
    return _MLIB_CLIENT_API.mirGetDF4(*args)
mirGetDF4 = _MLIB_CLIENT_API.mirGetDF4

def mirGetDF5(*args):
    return _MLIB_CLIENT_API.mirGetDF5(*args)
mirGetDF5 = _MLIB_CLIENT_API.mirGetDF5

def mirGetPCAResults(ID, update):
    return _MLIB_CLIENT_API.mirGetPCAResults(ID, update)
mirGetPCAResults = _MLIB_CLIENT_API.mirGetPCAResults

def mirSetupPCA(ID, data, IsScale, FactorNum):
    return _MLIB_CLIENT_API.mirSetupPCA(ID, data, IsScale, FactorNum)
mirSetupPCA = _MLIB_CLIENT_API.mirSetupPCA

def mirInterpolation(array1, array2, point, interpolation):
    return _MLIB_CLIENT_API.mirInterpolation(array1, array2, point, interpolation)
mirInterpolation = _MLIB_CLIENT_API.mirInterpolation

def mirGetForwardRate2(fromDates, toDates, curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp, useFwdData):
    return _MLIB_CLIENT_API.mirGetForwardRate2(fromDates, toDates, curveId, frequency, dayCount, slidingRule, calendar, interpolation, curveName, isFwdInterp, useFwdData)
mirGetForwardRate2 = _MLIB_CLIENT_API.mirGetForwardRate2

def mirSetUpFwdFXConstantCurve(CurveID, MarketName, GeneralProps, FwdFXConstantConv, CurveNames):
    return _MLIB_CLIENT_API.mirSetUpFwdFXConstantCurve(CurveID, MarketName, GeneralProps, FwdFXConstantConv, CurveNames)
mirSetUpFwdFXConstantCurve = _MLIB_CLIENT_API.mirSetUpFwdFXConstantCurve

def mirSwapStubRate(EffDt, Mat, Freq, DayCt, RollCnv, Cal, RollDay, FixLag, EomRoll, Interpolation, FirstStub, LastStub, StubType, CrvID, CurveNames, CurveTenors, TenorCurveFixings, UseCurveName, ToleranceTenor, IsFwdInterp, UseFwdData):
    return _MLIB_CLIENT_API.mirSwapStubRate(EffDt, Mat, Freq, DayCt, RollCnv, Cal, RollDay, FixLag, EomRoll, Interpolation, FirstStub, LastStub, StubType, CrvID, CurveNames, CurveTenors, TenorCurveFixings, UseCurveName, ToleranceTenor, IsFwdInterp, UseFwdData)
mirSwapStubRate = _MLIB_CLIENT_API.mirSwapStubRate

def mirGetZeroRate1(*args):
    return _MLIB_CLIENT_API.mirGetZeroRate1(*args)
mirGetZeroRate1 = _MLIB_CLIENT_API.mirGetZeroRate1

def mirGetZeroRate2(*args):
    return _MLIB_CLIENT_API.mirGetZeroRate2(*args)
mirGetZeroRate2 = _MLIB_CLIENT_API.mirGetZeroRate2

def mirOutputCurve(curveId, curveName):
    return _MLIB_CLIENT_API.mirOutputCurve(curveId, curveName)
mirOutputCurve = _MLIB_CLIENT_API.mirOutputCurve

def mirSwapPV01(notional, payRec, effectDt, maturity, curveId, xFreq, xDayCount, xRollCnv, xCalendar, xFirstStub, xLastStub, xRollDay, xPayLag, xStub, tSpread, tFreq, tDayCount, tRollCnv, tCalendar, tFirstStub, tLastStub, tRollDay, tFixLag, tFirstFix, tLastFix, tPayLag, tStub, interpolation, forecastCurve, discountCurve, interpFwds, eomRoll):
    return _MLIB_CLIENT_API.mirSwapPV01(notional, payRec, effectDt, maturity, curveId, xFreq, xDayCount, xRollCnv, xCalendar, xFirstStub, xLastStub, xRollDay, xPayLag, xStub, tSpread, tFreq, tDayCount, tRollCnv, tCalendar, tFirstStub, tLastStub, tRollDay, tFixLag, tFirstFix, tLastFix, tPayLag, tStub, interpolation, forecastCurve, discountCurve, interpFwds, eomRoll)
mirSwapPV01 = _MLIB_CLIENT_API.mirSwapPV01

def mirCompound3(*args):
    return _MLIB_CLIENT_API.mirCompound3(*args)
mirCompound3 = _MLIB_CLIENT_API.mirCompound3

def mirGetAnnuity1(fromDate, toDate, curveId, frequency, slidingRule, calendar, firstOddDate, lastOddDate, paymentDay, dayCount, interpolation, curveName):
    return _MLIB_CLIENT_API.mirGetAnnuity1(fromDate, toDate, curveId, frequency, slidingRule, calendar, firstOddDate, lastOddDate, paymentDay, dayCount, interpolation, curveName)
mirGetAnnuity1 = _MLIB_CLIENT_API.mirGetAnnuity1

def mirGetAnnuity2(curveId, dates, dayCount, interpolation, curveName):
    return _MLIB_CLIENT_API.mirGetAnnuity2(curveId, dates, dayCount, interpolation, curveName)
mirGetAnnuity2 = _MLIB_CLIENT_API.mirGetAnnuity2

def mirGetBusinessDays(fromDate, toDate, calendar):
    return _MLIB_CLIENT_API.mirGetBusinessDays(fromDate, toDate, calendar)
mirGetBusinessDays = _MLIB_CLIENT_API.mirGetBusinessDays

def mirGetECBStartDate(ecbDate):
    return _MLIB_CLIENT_API.mirGetECBStartDate(ecbDate)
mirGetECBStartDate = _MLIB_CLIENT_API.mirGetECBStartDate

def mirGetNextCBDate(centralBankId, baseDate, strictlyAfter):
    return _MLIB_CLIENT_API.mirGetNextCBDate(centralBankId, baseDate, strictlyAfter)
mirGetNextCBDate = _MLIB_CLIENT_API.mirGetNextCBDate

def mirGetNextECBDate(baseDate, strictlyAfter):
    return _MLIB_CLIENT_API.mirGetNextECBDate(baseDate, strictlyAfter)
mirGetNextECBDate = _MLIB_CLIENT_API.mirGetNextECBDate

def mirGetTerm(fromDate, toDate, dayCount, includeLast):
    return _MLIB_CLIENT_API.mirGetTerm(fromDate, toDate, dayCount, includeLast)
mirGetTerm = _MLIB_CLIENT_API.mirGetTerm

def mirSwapSchedule(accrualStartDate, accrualEndDateOrTenor, accrualDaycount, accrualFrequency, accrualSlidingRule, accrualCalendar, paymentFrequency, paymentSlidingRule, paymentCalendar, paymentLag, fixingSlidingRule, fixingCalendar, fixingLag, fixingAdvanceOrArrears, firstStub, lastStub, paymentRollDay, showColumnHeaders):
    return _MLIB_CLIENT_API.mirSwapSchedule(accrualStartDate, accrualEndDateOrTenor, accrualDaycount, accrualFrequency, accrualSlidingRule, accrualCalendar, paymentFrequency, paymentSlidingRule, paymentCalendar, paymentLag, fixingSlidingRule, fixingCalendar, fixingLag, fixingAdvanceOrArrears, firstStub, lastStub, paymentRollDay, showColumnHeaders)
mirSwapSchedule = _MLIB_CLIENT_API.mirSwapSchedule

def mirClearEntityPool():
    return _MLIB_CLIENT_API.mirClearEntityPool()
mirClearEntityPool = _MLIB_CLIENT_API.mirClearEntityPool

def meCurveCalibrateBasis(*args):
    return _MLIB_CLIENT_API.meCurveCalibrateBasis(*args)
meCurveCalibrateBasis = _MLIB_CLIENT_API.meCurveCalibrateBasis

def meCurveCalibrateFXForwards(curveCollection, staticDataTable, curveIndex, curveConv, fxFwdConv):
    return _MLIB_CLIENT_API.meCurveCalibrateFXForwards(curveCollection, staticDataTable, curveIndex, curveConv, fxFwdConv)
meCurveCalibrateFXForwards = _MLIB_CLIENT_API.meCurveCalibrateFXForwards

def meCurveCalibrateOIS(curveCollection, staticDataTable, curveIndex, curveConv, oisConv, oisRates, oisHistoricalRates, liborOisBasisConv, liborOisBasisRates, swapConv, swapRates):
    return _MLIB_CLIENT_API.meCurveCalibrateOIS(curveCollection, staticDataTable, curveIndex, curveConv, oisConv, oisRates, oisHistoricalRates, liborOisBasisConv, liborOisBasisRates, swapConv, swapRates)
meCurveCalibrateOIS = _MLIB_CLIENT_API.meCurveCalibrateOIS

def meCurveCalibrateSwap(curveCollection, staticDataTable, curveIndex, curveConv, moneyMarketConv, liborConv, liborRates, swapConv, swapRates, fraConv, fra3mRates, fra6mRates, futureConv, futureRates, convexityAdjConv, convexityAdjRates):
    return _MLIB_CLIENT_API.meCurveCalibrateSwap(curveCollection, staticDataTable, curveIndex, curveConv, moneyMarketConv, liborConv, liborRates, swapConv, swapRates, fraConv, fra3mRates, fra6mRates, futureConv, futureRates, convexityAdjConv, convexityAdjRates)
meCurveCalibrateSwap = _MLIB_CLIENT_API.meCurveCalibrateSwap

def meCurveCompoundRate(*args):
    return _MLIB_CLIENT_API.meCurveCompoundRate(*args)
meCurveCompoundRate = _MLIB_CLIENT_API.meCurveCompoundRate

def meCurveDiscountFactorsFromYearFractions(*args):
    return _MLIB_CLIENT_API.meCurveDiscountFactorsFromYearFractions(*args)
meCurveDiscountFactorsFromYearFractions = _MLIB_CLIENT_API.meCurveDiscountFactorsFromYearFractions

def meCurveDiscountFactorsFromTenors(*args):
    return _MLIB_CLIENT_API.meCurveDiscountFactorsFromTenors(*args)
meCurveDiscountFactorsFromTenors = _MLIB_CLIENT_API.meCurveDiscountFactorsFromTenors

def meCurveDiscountFactorsForwardStarting(*args):
    return _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStarting(*args)
meCurveDiscountFactorsForwardStarting = _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStarting

def meCurveDiscountFactorsForwardStartingFromYearFractions(*args):
    return _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStartingFromYearFractions(*args)
meCurveDiscountFactorsForwardStartingFromYearFractions = _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStartingFromYearFractions

def meCurveDiscountFactorsForwardStartingFromTenor(*args):
    return _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStartingFromTenor(*args)
meCurveDiscountFactorsForwardStartingFromTenor = _MLIB_CLIENT_API.meCurveDiscountFactorsForwardStartingFromTenor

def meCurveDisplay(curveCollection, curveIndex):
    return _MLIB_CLIENT_API.meCurveDisplay(curveCollection, curveIndex)
meCurveDisplay = _MLIB_CLIENT_API.meCurveDisplay

def meCurveForwardRatesFromYearFraction(fromDates, yearFraction, curveCollection, curveIndex, dayCount):
    return _MLIB_CLIENT_API.meCurveForwardRatesFromYearFraction(fromDates, yearFraction, curveCollection, curveIndex, dayCount)
meCurveForwardRatesFromYearFraction = _MLIB_CLIENT_API.meCurveForwardRatesFromYearFraction

def meCurveForwardRates(fixingDates, curveCollection, curveIndex):
    return _MLIB_CLIENT_API.meCurveForwardRates(fixingDates, curveCollection, curveIndex)
meCurveForwardRates = _MLIB_CLIENT_API.meCurveForwardRates

def meCurveForwardRatesFromForwardDates(fromDates, toDates, curveCollection, curveIndex):
    return _MLIB_CLIENT_API.meCurveForwardRatesFromForwardDates(fromDates, toDates, curveCollection, curveIndex)
meCurveForwardRatesFromForwardDates = _MLIB_CLIENT_API.meCurveForwardRatesFromForwardDates

def meCurveZeroRatesFromYearFractions(*args):
    return _MLIB_CLIENT_API.meCurveZeroRatesFromYearFractions(*args)
meCurveZeroRatesFromYearFractions = _MLIB_CLIENT_API.meCurveZeroRatesFromYearFractions

def meCurveZeroRatesFromTenors(*args):
    return _MLIB_CLIENT_API.meCurveZeroRatesFromTenors(*args)
meCurveZeroRatesFromTenors = _MLIB_CLIENT_API.meCurveZeroRatesFromTenors

def meDateFromTenor(*args):
    return _MLIB_CLIENT_API.meDateFromTenor(*args)
meDateFromTenor = _MLIB_CLIENT_API.meDateFromTenor

def meDateFromYearFraction(startDate, yearFraction, dayCount):
    return _MLIB_CLIENT_API.meDateFromYearFraction(startDate, yearFraction, dayCount)
meDateFromYearFraction = _MLIB_CLIENT_API.meDateFromYearFraction

def meDateBusinessDays(fromDate, toDate, calendar):
    return _MLIB_CLIENT_API.meDateBusinessDays(fromDate, toDate, calendar)
meDateBusinessDays = _MLIB_CLIENT_API.meDateBusinessDays

def meDateCentralBank(centralBankId, date, strictlyAfter):
    return _MLIB_CLIENT_API.meDateCentralBank(centralBankId, date, strictlyAfter)
meDateCentralBank = _MLIB_CLIENT_API.meDateCentralBank

def meDateECB(date, strictlyAfter):
    return _MLIB_CLIENT_API.meDateECB(date, strictlyAfter)
meDateECB = _MLIB_CLIENT_API.meDateECB

def meDateECBSwapStart(date):
    return _MLIB_CLIENT_API.meDateECBSwapStart(date)
meDateECBSwapStart = _MLIB_CLIENT_API.meDateECBSwapStart

def meDateECBSwapEnd(date):
    return _MLIB_CLIENT_API.meDateECBSwapEnd(date)
meDateECBSwapEnd = _MLIB_CLIENT_API.meDateECBSwapEnd

def meDateIMMFromMonth(year, month, calendar, businessDayAdj):
    return _MLIB_CLIENT_API.meDateIMMFromMonth(year, month, calendar, businessDayAdj)
meDateIMMFromMonth = _MLIB_CLIENT_API.meDateIMMFromMonth

def meDateNthIMM(year, nth, calendar, businessDayAdj):
    return _MLIB_CLIENT_API.meDateNthIMM(year, nth, calendar, businessDayAdj)
meDateNthIMM = _MLIB_CLIENT_API.meDateNthIMM

def meDateNthIMMFromStartDate(startDate, nth, calendar, businessDayAdj):
    return _MLIB_CLIENT_API.meDateNthIMMFromStartDate(startDate, nth, calendar, businessDayAdj)
meDateNthIMMFromStartDate = _MLIB_CLIENT_API.meDateNthIMMFromStartDate

def meProductAssetSwapSpread(bondCleanPrice, assetSwapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductAssetSwapSpread(bondCleanPrice, assetSwapLVB, validateKeys)
meProductAssetSwapSpread = _MLIB_CLIENT_API.meProductAssetSwapSpread

def meProductAssetSwapSpreadLVBKeys():
    return _MLIB_CLIENT_API.meProductAssetSwapSpreadLVBKeys()
meProductAssetSwapSpreadLVBKeys = _MLIB_CLIENT_API.meProductAssetSwapSpreadLVBKeys

def meProductOISParRate(oisSwapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductOISParRate(oisSwapLVB, validateKeys)
meProductOISParRate = _MLIB_CLIENT_API.meProductOISParRate

def meProductOISParRateLVBKeys():
    return _MLIB_CLIENT_API.meProductOISParRateLVBKeys()
meProductOISParRateLVBKeys = _MLIB_CLIENT_API.meProductOISParRateLVBKeys

def meProductOISPV(oisSwapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductOISPV(oisSwapLVB, validateKeys)
meProductOISPV = _MLIB_CLIENT_API.meProductOISPV

def meProductOISPVLVBKeys():
    return _MLIB_CLIENT_API.meProductOISPVLVBKeys()
meProductOISPVLVBKeys = _MLIB_CLIENT_API.meProductOISPVLVBKeys

def meProductSwapDV01(swapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductSwapDV01(swapLVB, validateKeys)
meProductSwapDV01 = _MLIB_CLIENT_API.meProductSwapDV01

def meProductSwapDV01LVBKeys():
    return _MLIB_CLIENT_API.meProductSwapDV01LVBKeys()
meProductSwapDV01LVBKeys = _MLIB_CLIENT_API.meProductSwapDV01LVBKeys

def meProductSwapParRate(swapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductSwapParRate(swapLVB, validateKeys)
meProductSwapParRate = _MLIB_CLIENT_API.meProductSwapParRate

def meProductSwapParRateLVBKeys():
    return _MLIB_CLIENT_API.meProductSwapParRateLVBKeys()
meProductSwapParRateLVBKeys = _MLIB_CLIENT_API.meProductSwapParRateLVBKeys

def meProductSwapPV(swapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductSwapPV(swapLVB, validateKeys)
meProductSwapPV = _MLIB_CLIENT_API.meProductSwapPV

def tryMeProductSwapPVLVBKeys():
    return _MLIB_CLIENT_API.tryMeProductSwapPVLVBKeys()
tryMeProductSwapPVLVBKeys = _MLIB_CLIENT_API.tryMeProductSwapPVLVBKeys

def meProductSwapPV01(swapLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductSwapPV01(swapLVB, validateKeys)
meProductSwapPV01 = _MLIB_CLIENT_API.meProductSwapPV01

def meProductSwapPV01LVBKeys():
    return _MLIB_CLIENT_API.meProductSwapPV01LVBKeys()
meProductSwapPV01LVBKeys = _MLIB_CLIENT_API.meProductSwapPV01LVBKeys

def meProductSwapSchedule(showColumnHeaders, swapScheduleLVB, validateKeys=True):
    return _MLIB_CLIENT_API.meProductSwapSchedule(showColumnHeaders, swapScheduleLVB, validateKeys)
meProductSwapSchedule = _MLIB_CLIENT_API.meProductSwapSchedule

def meProductSwapScheduleLVBKeys():
    return _MLIB_CLIENT_API.meProductSwapScheduleLVBKeys()
meProductSwapScheduleLVBKeys = _MLIB_CLIENT_API.meProductSwapScheduleLVBKeys

def meProductSwapStubRate(curveIndices, curveTenors, tenorCurveFixings, swapLVB, validateKeys):
    return _MLIB_CLIENT_API.meProductSwapStubRate(curveIndices, curveTenors, tenorCurveFixings, swapLVB, validateKeys)
meProductSwapStubRate = _MLIB_CLIENT_API.meProductSwapStubRate

def meProductSwapStubRateLVBKeys():
    return _MLIB_CLIENT_API.meProductSwapStubRateLVBKeys()
meProductSwapStubRateLVBKeys = _MLIB_CLIENT_API.meProductSwapStubRateLVBKeys

def meUtilityInterpolation(array1, array2, point, interpolation):
    return _MLIB_CLIENT_API.meUtilityInterpolation(array1, array2, point, interpolation)
meUtilityInterpolation = _MLIB_CLIENT_API.meUtilityInterpolation

def meUtilityPCA(key, data, useCorrelationMatrix, nFactors):
    return _MLIB_CLIENT_API.meUtilityPCA(key, data, useCorrelationMatrix, nFactors)
meUtilityPCA = _MLIB_CLIENT_API.meUtilityPCA

def tryMeUtilityRecord(enable, folder, repeat, startIndex, maxIndex):
    return _MLIB_CLIENT_API.tryMeUtilityRecord(enable, folder, repeat, startIndex, maxIndex)
tryMeUtilityRecord = _MLIB_CLIENT_API.tryMeUtilityRecord

def meUtilityClearEntityPool():
    return _MLIB_CLIENT_API.meUtilityClearEntityPool()
meUtilityClearEntityPool = _MLIB_CLIENT_API.meUtilityClearEntityPool

def meUtilityLoadCalendarFile(filepath):
    return _MLIB_CLIENT_API.meUtilityLoadCalendarFile(filepath)
meUtilityLoadCalendarFile = _MLIB_CLIENT_API.meUtilityLoadCalendarFile

def meUtilityLoadStaticData(filepath):
    return _MLIB_CLIENT_API.meUtilityLoadStaticData(filepath)
meUtilityLoadStaticData = _MLIB_CLIENT_API.meUtilityLoadStaticData

def meUtilityVersion():
    return _MLIB_CLIENT_API.meUtilityVersion()
meUtilityVersion = _MLIB_CLIENT_API.meUtilityVersion
# This file is compatible with both classic and new-style classes.


