using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Windows.Forms;  // For ListItem. Use the ListItem as a handy container

namespace TestDrive
{
    // Intended for common utility functions

    class Utilities
    {

        static object MyLock = new object();

        // Try to parse the input string into an int number of threads.
        // If the parse fails, use the number of CPU cores in this machine
        static public int getNumThreadsToUse(string threadsInput)
        {
            int numberOfThreadsToUse;
            if (!Int32.TryParse(threadsInput, out numberOfThreadsToUse))
            {
                numberOfThreadsToUse = Environment.ProcessorCount;
            }
            return numberOfThreadsToUse;
        }

        /* Constructs tthe path to the google_test executable, based on
        * the user-supplied workspace, architecture and build settings
        */
        static public string constructPathToTestExecutable(string workspace, string visualStudio, string architecture, string buildType )
        {
            string targetPath = "\\targets";
            string archNumber = architecture.Equals("Win32", StringComparison.OrdinalIgnoreCase) ? "32" : "64";
            string build      = buildType.Equals("LeakCheck", StringComparison.OrdinalIgnoreCase) ? "Debug" : buildType;

            string command = Environment.ExpandEnvironmentVariables(workspace)
                                + targetPath + "\\"
                                + archNumber + "\\"
                                + build + "\\GTEST\\out\\GTEST.exe";
            return command;
        }

        /* @brief Runs the specified shell command and collects the output and exitCode
         *        The exitCode is used to check if the test has passed or failed.
         * @param[in] command       The full path to an exe to run, excluding any command line arguments
         * @param[in] commandArg    The command line arguments to pass
         * @param[out] output       The output generated by the command
         * @param[out] Returns the exitCode of the command
         */
        static public int runExternalCommand(string command, string commandArg, bool debugRequested, string summaryLogPath, out string output)
        {
            Console.WriteLine("Run: " + command + " " + commandArg);

            Process process = new Process();
            process.StartInfo.FileName = command;
            process.StartInfo.Arguments = commandArg;
            process.StartInfo.CreateNoWindow = true;
            process.StartInfo.UseShellExecute = false;

            process.StartInfo.RedirectStandardOutput = true;
            process.StartInfo.RedirectStandardError = true;
            process.StartInfo.RedirectStandardInput = true;

            try
            {
                process.Start();
                //runningProcesses.TryAdd(process, 0); // Keep track of all running processes. The int is just a dummy value
            }
            catch (Exception)
            {
                output = "Unable to execute command: " + command;
                //MessageBox.Show(output);
                return -1;
            }

            if (debugRequested)
            {
                //MessageBox.Show("Attach your debugger to the GOOGLE_TEST.EXE with process id [ " + process.Id + " ] and then click OK");
                process.StandardInput.WriteLine();
            }

            // Send a return character which will un-pause the executable, in case it is waiting for user input
            process.StandardInput.WriteLine();

            // Read all the output generated by the command
            output = process.StandardOutput.ReadToEnd();

            // Wait until the process exits and capture the exitCode
            process.WaitForExit();
            int exitCode = process.ExitCode;
            process.Close();

            // Any memory leaks will be considered a test failure
            if (output.Contains("detected memory leaks"))
            {
                exitCode = 2;
            }
            if (output.Contains("#Warning"))
            {
                exitCode = 3;
            }

            if (exitCode > 0)
            {
                Console.Out.WriteLine("FAIL: " + output);

                // Serialize access to the log file
                lock (MyLock)
                {
                    Utilities.LogAppend(summaryLogPath, output);
                }

            }

            return exitCode;
        }

        static public string constructGTestFilter(ListViewItem row)
        {
            string testFolder = row.SubItems[1].Text;
            string testName = row.SubItems[2].Text;
            string commandArg = "--gtest_filter=\"" + testFolder + "." + testName + "\"";
            return commandArg;
        }

        static public string getSummaryLogFilePath(string logFolder, string architecture, string buildType)
        {
            string summaryLogPath = "";

            // If the logFolder has been specified, go ahead and construct a full summary-log file path
            if (logFolder.Length > 0)
            {
                string archNumber = architecture.Equals("Win32", StringComparison.OrdinalIgnoreCase) ? "32" : "64";

                summaryLogPath = Environment.ExpandEnvironmentVariables(logFolder) + "\\"
                                                                                   + "TestDrive_Failures_"
                                                                                   + archNumber + "_" + buildType + ".txt";
            }
            return summaryLogPath;
        }

        static public string getFailureLogPath(string logFolder, string architecture, string buildType, ListViewItem row)
        {
            string testFailureLogPath = "";

            // If the logFolder has been specified, go ahead and construct a full failure-log file path
            if (logFolder.Length > 0)
            {
                string archNumber = architecture.Equals("Win32", StringComparison.OrdinalIgnoreCase) ? "32" : "64";

                testFailureLogPath = Environment.ExpandEnvironmentVariables(logFolder) + "\\"
                                                                                       + archNumber + "_"
                                                                                       + buildType + "_"
                                                                                       + row.SubItems[0].Text + "_"
                                                                                       + row.SubItems[1].Text + "."
                                                                                       + row.SubItems[2].Text + ".txt";
            }
            return testFailureLogPath;
        }

        // Creates the directory that a log file lives in, if it does not already
        // exist, so that writing to a freshly-configured log folder does not throw.
        static private void ensureLogDirectoryExists(string logFilePath)
        {
            string logDirectory = Path.GetDirectoryName(logFilePath);
            if (!string.IsNullOrEmpty(logDirectory) && !Directory.Exists(logDirectory))
            {
                Directory.CreateDirectory(logDirectory);
            }
        }

        static public void LogAppend(string logFilePath, string logMessage)
        {
            if (logFilePath.Length > 0)
            {
                try
                {
                    ensureLogDirectoryExists(logFilePath);
                    File.AppendAllText(logFilePath, logMessage);
                }
                catch (Exception e)
                {
                    // A logging failure must never abort a test run - report it and continue.
                    Console.Out.WriteLine("#Warning: could not write log file '" + logFilePath + "': " + e.Message);
                }
            }
        }

        static public void LogWrite(string logFilePath, string logMessage)
        {
            if (logFilePath.Length > 0)
            {
                try
                {
                    ensureLogDirectoryExists(logFilePath);
                    File.WriteAllText(logFilePath, logMessage);
                }
                catch (Exception e)
                {
                    // A logging failure must never abort a test run - report it and continue.
                    Console.Out.WriteLine("#Warning: could not write log file '" + logFilePath + "': " + e.Message);
                }
            }
        }

        static public void LogDelete( string logFilePath)
        {
            if (logFilePath.Length > 0)
            {
                try
                {
                    File.Delete(logFilePath);
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine("#Warning: could not delete log file '" + logFilePath + "': " + e.Message);
                }
            }
        }
    }
}
