
#ifdef __GNUG__
#pragma implementation
#endif

#include "LACoreSystemError.h"
#include <cstring>
#include <cerrno>
#include <string.h>

/*!
    @brief constructor

    set error data. msg is set to add at the beginning of the error messages generated by the system.

    @param[in] msg additional error message
    @param[in] file file name that error occurs
    @param[in] line line number of the file that error occurs
    
*/
LACoreSystemError::LACoreSystemError(const char_t* msg, const char_t* file, unsigned int line)
: LACoreError(strerror(errno), file, line)
{
    addMsg(msg);
}

/*!
    @brief constructor

    set error data. msg is set as it is

    @param[in] file file name that error occurs
    @param[in] line line number of the file that error occurs
    
*/
LACoreSystemError::LACoreSystemError(const char_t* file, unsigned int line)
:LACoreError(strerror(errno), file, line)
{
}

/*!
    @brief copy constructor
    @param[in] e original error object
*/
LACoreSystemError::LACoreSystemError(const LACoreSystemError& e)
:LACoreError(e)
{
}
