//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NelsonSiegelSvenssonParameters : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NelsonSiegelSvenssonParameters(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NelsonSiegelSvenssonParameters obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NelsonSiegelSvenssonParameters() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MLIB_CLIENT_APIPINVOKE.delete_NelsonSiegelSvenssonParameters(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double beta0_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta0__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta0__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double beta1_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta1__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta1__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double beta2_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta2__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta2__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double lambda1_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_lambda1__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_lambda1__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double beta3_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta3__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_beta3__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double lambda2_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_lambda2__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonParameters_lambda2__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NelsonSiegelSvenssonParameters() : this(MLIB_CLIENT_APIPINVOKE.new_NelsonSiegelSvenssonParameters__SWIG_0(), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public NelsonSiegelSvenssonParameters(double beta0, double beta1, double beta2, double beta3, double lambda1, double lambda2) : this(MLIB_CLIENT_APIPINVOKE.new_NelsonSiegelSvenssonParameters__SWIG_1(beta0, beta1, beta2, beta3, lambda1, lambda2), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

}
