//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NelsonSiegelSvenssonCalibrationResults : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NelsonSiegelSvenssonCalibrationResults(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NelsonSiegelSvenssonCalibrationResults obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NelsonSiegelSvenssonCalibrationResults() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MLIB_CLIENT_APIPINVOKE.delete_NelsonSiegelSvenssonCalibrationResults(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public NelsonSiegelSvenssonParameters parameters_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_parameters__set(swigCPtr, NelsonSiegelSvenssonParameters.getCPtr(value));
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_parameters__get(swigCPtr);
      NelsonSiegelSvenssonParameters ret = (cPtr == global::System.IntPtr.Zero) ? null : new NelsonSiegelSvenssonParameters(cPtr, false);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double leastSquaresError_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_leastSquaresError__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_leastSquaresError__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double iterations_ {
    set {
      MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_iterations__set(swigCPtr, value);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = MLIB_CLIENT_APIPINVOKE.NelsonSiegelSvenssonCalibrationResults_iterations__get(swigCPtr);
      if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NelsonSiegelSvenssonCalibrationResults() : this(MLIB_CLIENT_APIPINVOKE.new_NelsonSiegelSvenssonCalibrationResults(), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

}
