//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VecVecString : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VecString>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VecVecString(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VecVecString obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VecVecString() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MLIB_CLIENT_APIPINVOKE.delete_VecVecString(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VecVecString(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VecString element in c) {
      this.Add(element);
    }
  }

  public VecVecString(global::System.Collections.Generic.IEnumerable<VecString> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VecString element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VecString this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VecString[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VecString[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VecString[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VecString[] ToArray() {
    VecString[] array = new VecString[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VecString> global::System.Collections.Generic.IEnumerable<VecString>.GetEnumerator() {
    return new VecVecStringEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VecVecStringEnumerator(this);
  }

  public VecVecStringEnumerator GetEnumerator() {
    return new VecVecStringEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VecVecStringEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VecString>
  {
    private VecVecString collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VecVecStringEnumerator(VecVecString collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VecString Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VecString)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    MLIB_CLIENT_APIPINVOKE.VecVecString_Clear(swigCPtr);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(VecString x) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_Add(swigCPtr, VecString.getCPtr(x));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = MLIB_CLIENT_APIPINVOKE.VecVecString_size(swigCPtr);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = MLIB_CLIENT_APIPINVOKE.VecVecString_capacity(swigCPtr);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_reserve(swigCPtr, n);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecString() : this(MLIB_CLIENT_APIPINVOKE.new_VecVecString__SWIG_0(), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecString(VecVecString other) : this(MLIB_CLIENT_APIPINVOKE.new_VecVecString__SWIG_1(VecVecString.getCPtr(other)), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecString(int capacity) : this(MLIB_CLIENT_APIPINVOKE.new_VecVecString__SWIG_2(capacity), true) {
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  private VecString getitemcopy(int index) {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.VecVecString_getitemcopy(swigCPtr, index), true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VecString getitem(int index) {
    VecString ret = new VecString(MLIB_CLIENT_APIPINVOKE.VecVecString_getitem(swigCPtr, index), false);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VecString val) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_setitem(swigCPtr, index, VecString.getCPtr(val));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VecVecString values) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_AddRange(swigCPtr, VecVecString.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecVecString GetRange(int index, int count) {
    global::System.IntPtr cPtr = MLIB_CLIENT_APIPINVOKE.VecVecString_GetRange(swigCPtr, index, count);
    VecVecString ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecVecString(cPtr, true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VecString x) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_Insert(swigCPtr, index, VecString.getCPtr(x));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VecVecString values) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_InsertRange(swigCPtr, index, VecVecString.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_RemoveAt(swigCPtr, index);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_RemoveRange(swigCPtr, index, count);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VecVecString Repeat(VecString value, int count) {
    global::System.IntPtr cPtr = MLIB_CLIENT_APIPINVOKE.VecVecString_Repeat(VecString.getCPtr(value), count);
    VecVecString ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecVecString(cPtr, true);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    MLIB_CLIENT_APIPINVOKE.VecVecString_Reverse__SWIG_0(swigCPtr);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_Reverse__SWIG_1(swigCPtr, index, count);
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VecVecString values) {
    MLIB_CLIENT_APIPINVOKE.VecVecString_SetRange(swigCPtr, index, VecVecString.getCPtr(values));
    if (MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Pending) throw MLIB_CLIENT_APIPINVOKE.SWIGPendingException.Retrieve();
  }

}
