@echo off

REM EXCEL_VERSIONS
set EXCEL_OFFICE2016_X64="C:\Program Files\Microsoft Office\Office16\EXCEL.exe"
set EXCEL_OFFICE2016_X86="C:\Program Files (x86)\Microsoft Office\Office16\EXCEL.exe"
set EXCEL_OFFICE2010_X64="C:\Program Files\Microsoft Office\Office14\EXCEL.exe"
set EXCEL_OFFICE2010_X86="C:\Program Files (x86)\Microsoft Office\Office14\EXCEL.exe"

REM RAPTOR VERSION
set RAPTOR_X64="\\fs002\Global\Secure\DIR_Raptor\RaptorExcelAddin\20191007-1.0.22.820\RaptorXlAddin64-PRD.xll"
set RAPTOR_X86="\\fs002\Global\Secure\DIR_Raptor\RaptorExcelAddin\20191007-1.0.22.820\RaptorXlAddin-PRD.xll"

REM SET THE EXCEL VERSION
if EXIST %EXCEL_OFFICE2016_X64% (
	set EXCEL=%EXCEL_OFFICE2016_X64%
	set IS_64_BIT=TRUE
	set ARCHITECTURE=PRODUCTION_X64
	set RAPTOR_ADDIN=%RAPTOR_X64%
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2016_X86% (
	set EXCEL=%EXCEL_OFFICE2016_X86%
	set IS_64_BIT=FALSE
	set ARCHITECTURE=PRODUCTION
	set RAPTOR_ADDIN=%RAPTOR_X86%
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2010_X64% (
	set EXCEL=%EXCEL_OFFICE2010_X64%
	set IS_64_BIT=TRUE
	set ARCHITECTURE=PRODUCTION_X64
	set RAPTOR_ADDIN=%RAPTOR_X64%
	GOTO :EXCEL_SET
)

if EXIST %EXCEL_OFFICE2010_X86% (
	set EXCEL=%EXCEL_OFFICE2010_X86%
	set IS_64_BIT=FALSE
	set ARCHITECTURE=PRODUCTION
	set RAPTOR_ADDIN=%RAPTOR_X86%
	GOTO :EXCEL_SET
)

:EXCEL_NOT_SET
echo .
echo Failed to Detect Excel Version
echo .
EXIT

:EXCEL_SET

echo .
echo EXCEL Configuration
echo -------------------
echo Excel Version: %EXCEL%
echo Using 64 Bit Excel: %IS_64_BIT%
echo .

REM EXCEL ADDIN & PRICING TOOLKIT FOLDERS
set EXCEL_ADDIN=\\fs002\Global\Secure\DIR_MLib_Analytics\MLIB_Excel_Addin\MLIBQ_ADDIN
set PRICING_TOOLKIT=\\fs002\Global\Secure\DIR_MLib_Analytics\PricingTools
set UTILITIES=\\fs002\Global\Secure\DIR_MLib_Analytics\Utilities

REM MLIB VERSION CONTROL FOR UAT
set MLIB_CURRENT="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-23.1\MLIBQ_ADDIN.xll"
set MLIB_BACKUP="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-09.1\MLIBQ_ADDIN.xll"

REM MLIB VERSION CONTROL FOR TRADING DESKS
set MLIB_AUD_BOND_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_EUR_SWAPS_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_GBP_SWAPS_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_USD_SWAPS_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"
set MLIB_JGB_DESK="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-27.1\MLIBQ_ADDIN.xll"

REM MLIB TOOLBAR VERSION CONTROL
set MLIB_TOOLBAR="%UTILITIES%\Toolbar\ExcelToolbar.xlam"

REM CURVE BUDDY VERSION CONTROL
set CURVE_BUDDY_MLIB_VERSION="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.3\MLIBQ_ADDIN.xll"
set CURVE_BUDDY_APP="%PRICING_TOOLKIT%\CurveBuddy\bin\CurveBuilderTool.exe"

REM CURVE CALIBRATION TOOL
SET CURVE_BUILDER="%PRICING_TOOLKIT%\CurveCalibrationTool\CurveCalibrationTool-12.9.xlsb"

REM SWAP PRICER VERSION CONTROL
set MLIB_SWAP_PRICER="%EXCEL_ADDIN%\%ARCHITECTURE%\2019-11-08.1\MLIBQ_ADDIN.xll"
set SWAP_PRICER="%PRICING_TOOLKIT%\SwapsPricer\SwapsPricerV2.3.xlsm"

REM BOND PRICER VERSION CONTROL
set BOND_PRICER="%PRICING_TOOLKIT%\BondPricer\BondPricer-0.2.xlsm"

REM USD PRICER VERSION CONTROL
set MLIB_USD_PRICER="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.3\MLIBQ_ADDIN.xll"
set USD_PRICER="%PRICING_TOOLKIT%\USDPricer\USD Pricer 9.4.xlsm"

REM EUR PRICER VERSION CONTROL
set MLIB_EUR_PRICER="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.3\MLIBQ_ADDIN.xll"
set EUR_PRICER="%PRICING_TOOLKIT%\EURPricer\EUR Pricer-4.1.xlsm"

REM GBP PRICER VERSION CONTROL
set MLIB_GBP_PRICER="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.3\MLIBQ_ADDIN.xll"
set GBP_PRICER="%PRICING_TOOLKIT%\GBPPricer\GBP Pricer 7.8.xlsm"

REM EUR PRICER WITH GLOBAL CURVES VERSION CONTROL
set EUR_PRICER_GLOBAL_CURVES="%PRICING_TOOLKIT%\EURPricer\EUR Pricer-3.0 - Global Curves.xlsm"

REM FX PRICER VERSION CONTROL
set FX_PRICER="%PRICING_TOOLKIT%\FXPricer\FXPricer-0.1.xlsx"

REM XCCY_PRICER VERSION CONTROL
set MLIB_XCCY_DESK_PROD="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.1\MLIBQ_ADDIN.xll"
set XCCY_PRICER_PROD="%PRICING_TOOLKIT%\XccyPricer\XccyPricerV7.4.xlsb"

set MLIB_XCCY_DESK_UAT="%EXCEL_ADDIN%\%ARCHITECTURE%\2020-01-06.1\MLIBQ_ADDIN.xll"
set XCCY_PRICER_UAT="%PRICING_TOOLKIT%\XccyPricer\XccyPricerV7.4.xlsb"

REM
